### ISSUE TITLE
scalene doesn't work with JAX on GPU

### ISSUE THREAD

**Issue by clemisch** [plasma-umass/scalene#106]
**Describe the bug**

scalene does not work with [JAX](https://github.com/google/jax) on GPU. It hangs (seemingly) indefinitely and never returns. Without scalene, the script executes quicky in <5 seconds. 

In contrast, scalene works fine with JAX on CPU 

* on CPU host or
* with `jax.config.update("jax_platform_name", "cpu")` on GPU host

**To Reproduce**

```
$ scalene script.py
```

with following example script:

```python
import numpy as np
import jax
import jax.numpy as jnp

def reg_square(x):
    cost = 0.0
    for i in range(x.ndim):
        xd = jnp.diff(x, axis=i)
        cost += jnp.sum(jnp.square(xd))
    return cost

vol = jax.device_put(np.random.rand(100, 200, 300))

reg_square(vol).block_until_ready();
```

**Expected behavior**

Not getting stuck, i.e. not having "infinite" overhead. 

**Additional context**

I'm on Ubuntu 18.04 with 

* Python 3.6
* `scalene==1.1.12`
* `jax==0.2.7`
* `jaxlib==0.1.58`

**Comment by emeryberger** [comment]
As of the most recent release, this works *and* attributes GPU time, though for such a short run, you need to increase the `--cpu-sampling-rate` (below is for 0.001):

<img width="1084" alt="Screen Shot 2021-03-13 at 5 49 04 PM" src="https://user-images.githubusercontent.com/1612723/111051891-71ed5380-8424-11eb-80d8-4db3466e4cbe.png">

**Comment by clemisch** [comment]
Thank you for checking in on this. I see you used `--cpu-only` as a profiler flag. Does this interfere with attributing GPU time? If not, why do we need this flag?

**Comment by clemisch** [comment]
Also: example still does not work for me on GPU host. Flags `--cpu-only` and/or `--cpu-sampling-rate` have no effect.

* Ubuntu 18.04
* `scalene==1.3.0`
* `jax==0.2.10`
* `jaxlib==0.1.62`
