### ISSUE TITLE
Can scalene support profiling on a running service

### ISSUE THREAD

**Issue by sharepusher** [plasma-umass/scalene#109]
I try to profile my tornado service, but it failed with "Scalene error: received signal SIGSEGV"

scalene ./xxxxx.py --port=9111

Scalene error: received signal SIGSEGV

Is it possible that scalene supports attaching a process just like py-spy does

It's also acceptable that I can run a web service together with scalene

**Comment by emeryberger** [comment]
Can you provide a minimal reproducible case? I just tried Scalene with the "hello, world" example given here and it worked fine (printing a profile once I hit ctrl-c). (Note that Scalene does not currently allow attachment to an already-running process.)

     
                                                                         Memory usage: ▅▆▇▇▇████████████ (max:  20.61MB, growth rate:  27%)                                                                    
                                                                                test-tornado.py: % of time = 100.00% out of  22.99s.                                                                           
             ╷       ╷       ╷     ╷       ╷      ╷              ╷       ╷                                                                                                                                     
        Line │Time % │Time % │Sys  │Mem %  │Net   │Memory usage  │Copy   │                                                                                                                                     
             │Python │native │%    │Python │(MB)  │over time / % │(MB/s) │test-tornado.py                                                                                                                      
     ╺━━━━━━━┿━━━━━━━┿━━━━━━━┿━━━━━┿━━━━━━━┿━━━━━━┿━━━━━━━━━━━━━━┿━━━━━━━┿━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸
           1 │       │       │     │   61% │   15 │▃▄▄▄▄▄▄ 62%   │       │import tornado.ioloop                                                                                                                
           2 │       │       │     │       │    5 │▂▂▂▂▂▂        │       │import tornado.web                                                                                                                   
           3 │       │       │     │       │      │              │       │                                                                                                                                     
           4 │       │       │     │       │      │              │       │class MainHandler(tornado.web.RequestHandler):                                                                                       
           5 │       │       │     │       │      │              │       │    def get(self):                                                                                                                   
           6 │       │       │     │       │      │              │       │        self.write("Hello, world")                                                                                                   
           7 │       │       │     │       │      │              │       │                                                                                                                                     
           8 │       │       │     │       │      │              │       │def make_app():                                                                                                                      
           9 │       │       │     │       │      │              │       │    return tornado.web.Application([                                                                                                 
          10 │       │       │     │       │      │              │       │        (r"/", MainHandler),                                                                                                         
          11 │       │       │     │       │      │              │       │    ])                                                                                                                               
          12 │       │       │     │       │      │              │       │                                                                                                                                     
          13 │       │       │     │       │      │              │       │if __name__ == "__main__":                                                                                                           
          14 │       │       │     │       │      │              │       │    app = make_app()                                                                                                                 
          15 │       │       │     │       │   -1 │              │       │    app.listen(8888)                                                                                                                 
          16 │  100% │       │ 99% │       │    1 │▂▂▂▂▂▂▂▂▂     │       │    tornado.ioloop.IOLoop.current().start()                                                                                          
             ╵       ╵       ╵     ╵       ╵      ╵              ╵       ╵

**Comment by emeryberger** [comment]
Closing for lack of response.

**Comment by sanathpholla** [comment]
+1 It would be great if we can attach scalene to a running python process to profile(both cpu and memory) the python program.
Something like, how linux perf tools allows profiling on any pid with "perf [record|top] -p <pid>"

The reason for this request is, we have multiple python processes running in the system. We would only like to profile some of the python process only when we see some anomaly in its CPU/memory usage.

The method to run the program using scalene in background and send pause/resume profiling signals cannot be used in my case.

Thanks,
Sanath
