### ISSUE TITLE
Mem % Python column is empty

### ISSUE THREAD

**Issue by iwita** [plasma-umass/scalene#124]
**Describe the bug**
I tried to run a benchmark from pyperformance and the output of the profiler in the `Mem % Python` column is empty.

**To Reproduce**
1. Run scalene script.py

**Expected behavior**
Get Memory utilization per line

**Screenshots**

**Desktop**
 - OS: Ubuntu 20.04.1

**Comment by emeryberger** [comment]
Which benchmark?

**Comment by iwita** [comment]
The bm_sympy.py

https://github.com/python/pyperformance/blob/master/pyperformance/benchmarks/bm_sympy.py

**Comment by cyberic99** [comment]
I have the same issue on ArchLinux, even for simple scripts.
This happens on version 1.3.0 and on git-e829f94
```
$ scalene --malloc-threshold=0 ./p.py 
done
                  ./p.py: % of time = 100.00% out of   5.00s.                  
        ╷        ╷       ╷     ╷     ╷                                         
   Line │Time %  │Time % │Sys  │GPU  │                                         
        │Python  │native │%    │%    │./p.py                                   
╺━━━━━━━┿━━━━━━━━┿━━━━━━━┿━━━━━┿━━━━━┿━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸
      1 │        │       │     │nan% │#!/usr/bin/env python3                   
      2 │        │       │     │nan% │                                         
      3 │        │       │     │nan% │import time                              
      4 │  100%  │       │ 99% │nan% │time.sleep(5)                            
      5 │        │       │     │nan% │print("done")  
```
```
$ cat p.py
#!/usr/bin/env python3

import time
time.sleep(5)
print("done")
```

**Comment by emeryberger** [comment]
The current version in the repository _should_ fix this (https://github.com/plasma-umass/scalene/commit/2a850e5fd281ce4c9fdc8d169c21a6e099214344). Please give it a try (previous versions elided the memory columns when no samples were reported; this version always includes it unless it is disabled via `--cpu-only`). Note, I am concerned and surprised by the `nan%` showing up for GPU time -- are you on a system with an nVidia GPU?

**Comment by cyberic99** [comment]
I'll test the latest version soon and report back, thanks.

> are you on a system with an nVidia GPU?

yes:
```
01:00.0 VGA compatible controller: NVIDIA Corporation GK104 [GeForce GTX 660 Ti] (rev a1)
```

**Comment by emeryberger** [comment]
I suspect your GPU card is too old to be covered by `GPUtil`, so I added a fix to suppress `nan`s. Please take a look (just committed). Thanks!

**Comment by cyberic99** [comment]
I tried with version 99c87f0d and I can now see the ``Mem %`` column, thank you. But how is it related to my GPU card?

**Comment by emeryberger** [comment]
The `nan` listed in the `GPU` column presumably was because your model is not supported -- hopefully this is not showing up now!

**Comment by emeryberger** [comment]
If the `nan` is cleared, then this issue I believe can safely be closed -- please re-open if this is not the case!

**Comment by iwita** [comment]
Thank you, the `Mem %` column is now filled for my case as well.
