### ISSUE TITLE
errors on ArchLinux and python3.9 

### ISSUE THREAD

**Issue by cyberic99** [plasma-umass/scalene#145]
**Describe the bug**
I get these errors when running my code:
```python
Exception ignored in: <function _after_fork at 0x559984ec9880>
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 1496, in _after_fork
    thread._reset_internal_locks(False)
  File "/usr/lib/python3.9/threading.py", line 827, in _reset_internal_locks
    self._started._at_fork_reinit()
  File "/usr/lib/python3.9/threading.py", line 527, in _at_fork_reinit
    self._cond._at_fork_reinit()
  File "/usr/lib/python3.9/threading.py", line 253, in _at_fork_reinit
    self._lock._at_fork_reinit()
AttributeError: 'ReplacementLock' object has no attribute '_at_fork_reinit'
```

**To Reproduce**
I cannot post the whole code, but here is  what it does, at least:
- creating threads, processes, using the 'forkserver' start method, on linux, and ``multiprocessing.get_context()``
- overriding ``threading.Thread.run``
- creating multiprocessing,queues

**Expected behavior**
The different processes and threads I create start normally

**Desktop**
 - OS: ArchLinux

**Additional context**
Python version: 3.9

**Comment by sternj** [comment]
A possible fix is forthcoming!

**Comment by cyberic99** [comment]
Thank you!

If you want be to try development branches or patches, tell me.

**Comment by emeryberger** [comment]
Please try the current version (in this repo)!

**Comment by cyberic99** [comment]
yes, it works much better!

I am still able to produce some errors but I'll open separate issues.

But strangely, I have no 'memory' column at all.

even with  ``--malloc-threshold=1``

**Comment by emeryberger** [comment]
Thanks - see https://github.com/plasma-umass/scalene/issues/124#issuecomment-802457194.
