### ISSUE TITLE
Profiling hangs. Way to see internal progress? 

### ISSUE THREAD

**Issue by beroe** [plasma-umass/scalene#150]
Thanks for this great resource with amazing potential. 

I have a script that runs in about 30 seconds (or up to 2h with different input files), but when I try to profile it, it just hangs on one step (for up to 8 hours now) , and I can't tell what the problem is. 

I've tried the `--profile-interval` option, but it never outputs anything. 

Is there something in the `/tmp/scalene######/` folder or elsewhere that could give an idea?

Should I try setting the cpu-sampling-rate slower?

I am currently running it on Ubuntu 18 with python 3.8 and these options: 
     --reduced-profile --cpu-only --outfile pppscalene.txt  --cpu-percent-threshold 3 
 
`top` reports that the associated python process is taking only 1% cpu

I have gotten it to successfully profile the `benchmark.py` program, although it seemed to also fail on that if I didn't specify `--cpu-only`

Does it have issues with multiprocessing? I have it set to one thread at the moment, but this script does use the multiprocessing library.

Suggestions on where to look?

**Comment by emeryberger** [comment]
We have a test for multiprocessing: `test/multiprocessing_test.py`. If that doesn't work, something is seriously amiss on your system. What version of Scalene are you using? Current repo version or?

**Comment by beroe** [comment]
Thanks for the reply. 

I installed via pip not from the repo so I'm not sure which version is there. (I'm the one who posted about python 3.8 and signal); I don't see any `--version` reported. I could try grabbing the latest code and replacing the corresponding `.py` files but I don't know if there are other steps that would have to occur.

Your multiprocessing test works fine. 

One other observation: when I interrupt the process with ctrl-C, a few times I've seen this message... Maybe more like a broken pipe than actual error?
```
Scalene: An exception of type FileNotFoundError occurred. Arguments:
(2, 'No such file or directory')
Traceback (most recent call last):
  File "~/.local/lib/python3.8/site-packages/scalene/scalene_profiler.py", line 1517, in run_profiler
    exit_status = profiler.profile_code(
  File "~/.local/lib/python3.8/site-packages/scalene/scalene_profiler.py", line 1434, in profile_code
    if Scalene.__output.output_profiles(
  File "~/.local/lib/python3.8/site-packages/scalene/scalene_output.py", line 377, in output_profiles
    stats.output_stats(pid, python_alias_dir_name)
  File "/home/haddock/.local/lib/python3.8/site-packages/scalene/scalene_statistics.py", line 260, in output_stats
    with open(out_fname, "wb") as out_file:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/scalenevh9zjpa8/scalene71820-72093'

```

**Comment by emeryberger** [comment]
To see a version number, try `python3 -m pip show scalene` (this works for any pip installed package). In the meanwhile, might as well get the latest release: `python3 -m pip install -U scalene`.

**Comment by beroe** [comment]
Thanks. I didn't know about that `show` command. Handy...
Before updating:

```Name: scalene
Version: 1.3.0
Summary: Scalene: A high-resolution, low-overhead CPU, GPU, and memory profiler for Python
Home-page: https://github.com/emeryberger/scalene
Author: Emery Berger
Author-email: emery@cs.umass.edu
License: Apache License 2.0
Location: /home/myuser/.local/lib/python3.6/site-packages
Requires: numpy, cloudpickle, gputil, rich
```
No change after updating, and it is also installed at the same relative path in python3.8. I've been running with `python3.8` because of the `signal` issue mentioned in #148

**Comment by emeryberger** [comment]
Hi @beroe - any hope of getting your code so we can try to reproduce locally?

**Comment by beroe** [comment]
Hi. Thanks. I'm profiling this program: https://gitlab.com/fethalen/phylopypruner
I went back in and "manually" added profiling (running clock totals), so I figured out the bottlenecks, but would still be curious to have it work with scalene.

**Comment by emeryberger** [comment]
Excellent - can you provide a sample command line and point to some inputs?

**Comment by beroe** [comment]
Did you get the example/demo working? Sorry to leave that to you to figure out :^)

**Comment by emeryberger** [comment]
Yep, got it, thanks -- I was able to reproduce the problem, so we should be able to find a solution soon!

**Comment by beroe** [comment]
That is so great. Thanks!

**Comment by emeryberger** [comment]
@beroe please give this a try (current repo version):
`python3 -m pip install -U git+https://github.com/plasma-umass/scalene`

**Comment by beroe** [comment]
Thanks! Is there a version 1.3.2? That is what shows on pypi, but when I installed I am getting 1.3.1.

BTW, the embedded images on https://pypi.org/project/scalene/ (which is the first search result) are 404

**Comment by beroe** [comment]
WORKS PERFECTLY! Thanks so much. :^)
