### ISSUE TITLE
Individual lines in a function are blank

### ISSUE THREAD

**Issue by zacqed** [plasma-umass/scalene#153]
It shows EAD_ takes 1% time
![image](https://user-images.githubusercontent.com/1675591/111982550-1cedc380-8b2f-11eb-98ac-d8b8f17df0c5.png)

However everything under it is coming blank:
![image](https://user-images.githubusercontent.com/1675591/111983292-fbd9a280-8b2f-11eb-9ea8-a3ecc7f3b4a5.png)

**Comment by emeryberger** [comment]
This is the expected behavior; if times for individual lines are (rounded down) 0%, they are not displayed.
