### ISSUE TITLE
Command line argument to profile a specific module and any of its submodules

### ISSUE THREAD

**Issue by ogrisel** [plasma-umass/scalene#160]
It would be nice to have command line flags to focus the profiling report to specific modules and their sub-modules, for instance:

```
scalene --profile-module sklearn.neighbors --profile-model numpy my_code.py
```

**Comment by emeryberger** [comment]
If you say `--profile-all --profile-only sklearn`, you will get only code from files in directories that contain `sklearn`, which _may_ do the trick. Please verify. (Of course, this is only one module and not multiple modules.)

**Comment by ogrisel** [comment]
Ok I did not understand that you had to use both options together by reading the doc. Maybe this could be clarified:

```
% scalene --help
[...]
  --profile-all         profile all executed code, not just the target program (default: only the target program)
  --profile-only PROFILE_ONLY
                        profile only code in files that contain the given string (default: no restrictions)
[...]
```

Also it's not possible to pass several values for `--profile-only`, such as `-profile-all --profile-only sklearn --profile-only-numpy`.

**Comment by emeryberger** [comment]
With https://github.com/plasma-umass/scalene/commit/9b2c85e08f4e218bd067604f8a3e4f7ca7e67fd4, I've now extended how `--profile-only` works: you can now say `--profile-all --profile-only sklearn,numpy` and you should get the desired results.
