### ISSUE TITLE
Python 3.6: __init__() got an unexpected keyword argument 'allow_abbrev'

### ISSUE THREAD

**Issue by andreas-zeller** [plasma-umass/scalene#182]
**Describe the bug**
If I invoke scalene 1.3.3 with Python 3.6 in any way, say

```sh
python3.6 -m scalene --help
```
I get
```
TypeError: __init__() got an unexpected keyword argument 'allow_abbrev'
```

The label at the top of the README lists Python 3.6 as a possible environment.

**Expected behavior**
Scalene starts.

**Desktop (please complete the following information):**
 - OS: macOS 11.3.1

**Comment by jaltmayerpizzorno** [comment]
This (scalene 1.3.3, macOS 11.3.1) works for me using Python 3.6.10 from Anaconda.
How (Anaconda, MacPorts, brew, ...) did you get your Python 3.6 environment?

Thinking out loud: `allow_abbrev` is an argument to python's `argparse`; that argument was new in python 3.5, so should have been there in 3.6...

**Comment by emeryberger** [comment]
Yes, that argument was per the docs in 3.6:

https://docs.python.org/3.6/library/argparse.html#argumentparser-objects

**Comment by emeryberger** [comment]
Bump @andreas-zeller - we'd love to get to the bottom of this!

**Comment by emeryberger** [comment]
Closing for lack of response. We will soon be abandoning 3.6 support (its official end of life is December 2021 - see https://endoflife.date/python).
