### ISSUE TITLE
Add a data output option

### ISSUE THREAD

**Issue by tirthajyoti** [plasma-umass/scalene#197]
Please add an option to extract raw data (perhaps in the form of a dictionary) from a Scalene run. If this already exists, please point me to that. Basically `scalene <myscript.py> --dict` should produce a dictionary with all the relevant data which comes in the HTML table.

This will facilitate running many code experiments and collect the data and statistics in a systematic way.

**Comment by emeryberger** [comment]
We've thought about doing this (the plan would be to export JSON) to decouple the output from Scalene internals, so this is a feature that is definitely on our radar.

**Comment by emeryberger** [comment]
Scalene now (in the repository version) has a `--json` flag.

**Comment by shashank-srikant** [comment]
Great timing! Was looking for this option. Glad this search pointed me to this post.
