### ISSUE TITLE
start with profiling disabled

### ISSUE THREAD

**Issue by belm0** [plasma-umass/scalene#198]
**Is your feature request related to a problem? Please describe.**
I'd like to start profiling once the program reaches steady state (after most of the imports, jitting, etc.).

**Describe the solution you'd like**
Option to start scalene with profiling disabled.

**Describe alternatives you've considered**
If I'm reading the help correctly, using a background run, the profiling will start in the "on" state.
```
When running Scalene in the background, you can suspend/resume profiling
for the process ID that Scalene reports. For example:

   % python3 -m scalene [options] yourprogram.py &
 Scalene now profiling process 12345
   to suspend profiling: python3 -m scalene.profile --off --pid 12345
   to resume profiling:  python3 -m scalene.profile --on  --pid 12345
```

**Comment by emeryberger** [comment]
I'm considering doing this by adding a `--off` switch for starting Scalene with profiling disabled (also `--on`, the default, meaning Scalene would start with profiling enabled). What do you think?

**Comment by belm0** [comment]
Sounds good!

**Comment by emeryberger** [comment]
Added with https://github.com/plasma-umass/scalene/commit/b77af52f5e288e80c23d5cb61698a3d995124928. Let us know how it goes! (You'll need to install from the repo, as in `pip install -U git+https://github.com/plasma-umass/scalene`)

**Comment by belm0** [comment]
`--off` is working, thank you!
