### ISSUE TITLE
hangs at 100% CPU after a few seconds

### ISSUE THREAD

**Issue by belm0** [plasma-umass/scalene#199]
**Describe the bug**
Even with `--cpu-only`, scalene causes my app to hang and the process consumes 100% CPU, and SIGKILL is required.  Usually it happens within the first 2 seconds.  Rarely I can make it out to 10 seconds or so.

This is a proprietary, single-threaded, async heavy app with 100's of concurrent tasks.

**Environment**
 - OS: [e.g. iOS]  Linux x86_64
 - scalene 1.3.4.7
 - Python 3.7.9

**Comment by jaltmayerpizzorno** [comment]
Thank you for reaching out. Any chance you could extract a portion that reproduces the problem?

**Comment by belm0** [comment]
I suspect it would be difficult in this case.  Given that the symptom is random hanging with a high probability per unit of time, it could be anything, or scalene having a problem with high coroutine activity.

I notice that hanging is a typical symptom of scalene when things go wrong.  Is there some kind of debug instrumentation that could be added to narrow things down in such cases?

https://github.com/plasma-umass/scalene/issues?q=is%3Aissue+hang+

**Comment by emeryberger** [comment]
We _think_ the latest changes in the signal handling logic may have resolved this issue. Can you try again with the latest repo version (`python3 -m pip install -U git+https://github.com/plasma-umass/scalene`)?

**Comment by belm0** [comment]
It seems to be resolved, thank you.
