### ISSUE TITLE
pprof output format

### ISSUE THREAD

**Issue by jzelinskie** [plasma-umass/scalene#214]
**Is your feature request related to a problem? Please describe.**
There are a variety of analysis tools built around the [pprof format](https://github.com/google/pprof) that I'd like to use with scalene.

**Describe the solution you'd like**
- An added flag similar to one for HTML output, but for pprof output
- A simple way to embed a webserver to serve profiles live similar to [Go's net/http/pprof](https://pkg.go.dev/net/http/pprof) (although this could be another library or out of scope)

Thanks again for an awesome project. Profiling has been a pain in Python for so long.

**Comment by emeryberger** [comment]
Thanks for your request. This format seems incompatible with Scalene in a number of dimensions, but I'd welcome clarification of how to fit even a subset of the output that Scalene produces into [the pprof format](https://github.com/google/pprof/blob/master/proto/profile.proto) (please re-open if you have comments / suggestions). Meanwhile, Scalene now offers JSON output (`--json`), which may be of some use in the interim.
