### ISSUE TITLE
import cv2 failed

### ISSUE THREAD

**Issue by Bovey0809** [plasma-umass/scalene#224]
**Describe the bug**

**To Reproduce**
1. Go to 'bug.py'
2. Click on 'import cv2'
3. Scroll down to 'scalene bug.py'

```
(base) root@431528a52692:/yangxin# scalene memory_leak_tutorial.py 
ImportError: numpy.core.multiarray failed to import
Error in program being profiled:
 numpy.core.multiarray failed to import
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/scalene/scalene_profiler.py", line 1237, in profile_code
    exec(code, the_globals, the_locals)
  File "memory_leak_tutorial.py", line 1, in <module>
    import cv2
  File "/opt/conda/lib/python3.6/site-packages/cv2/__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: numpy.core.multiarray failed to import
```

**Expected behavior**
profile my code.

**Screenshots**

**Desktop (please complete the following information):**
docker: nvcr.io/nvidia/pytorch:20.06

**Additional context**

**Comment by drewm1980** [comment]
This is impacting me too; we have a lot of direct and transitive dependencies on my opencv in my company's code, so this renders scalene unusable for us. 

I'm working in a similar docker container.

**Comment by drewm1980** [comment]
Scalene was able to profile the same script in a conda environment outside the container, so it seems this is something environment specific.

In the failing containerized environment:
Python 3.6.9
In [3]: cv2.__version__
Out[3]: '4.1.1'
In [5]: numpy.__version__
Out[5]: '1.19.5'

In the passing conda environment:
Python 3.7.6
In [3]: cv2.__version__                                                                        
Out[3]: '4.1.1'
In [6]: numpy.__version__                                                                      
Out[6]: '1.18.5'

I see @Bovey0809 's environment is also python 3.6... maybe that.

**Comment by drewm1980** [comment]
Another passing non-containerized conda environment:
Python 3.6.9
In [2]: cv2.__version__                                                                        
Out[2]: '4.1.1'
In [4]: numpy.__version__                                                                      
Out[4]: '1.17.4'

**Comment by drewm1980** [comment]
(after updating numpy to bring the above environment closer to the failing dockerized environment)

Another passing non-containerized conda environment:
Python 3.6.9
In [2]: cv2.version
Out[2]: '4.1.1'
In [4]: numpy.version
Out[4]: '1.19.5'

This matches the failing containerized environment. Maybe it's an issue with running scalene inside a container? 

Normally I wouldn't suspect the container, but profilers ~do usually need very deep OS integration to work.

**Comment by drewm1980** [comment]
There are no reported issues matching "docker" or "container". Is scalene known to work inside a docker container?

**Comment by jaltmayerpizzorno** [comment]
Scalene currently requires Python 3.7.

**Comment by emeryberger** [comment]
OpenCV works fine on the latest versions of Scalene (which, as stated above, require Python 3.7 or higher). Scalene runs fine in a Docker container (just verified), so closing.
