### ISSUE TITLE
AttributeError: module 'threading' has no attribute '_shutdown_locks_lock'

### ISSUE THREAD

**Issue by Bovey0809** [plasma-umass/scalene#225]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by RAbraham** [comment]
I'm not sure yet, but are you on Python 3.6?

**Comment by RAbraham** [comment]
yes, that was the issue for me. I was on PYthon3.6 and scalene needs a minimum of python 3.7. In 3.6, it picks up pythons standard `threading` library I guess.

**Comment by Bovey0809** [comment]
> yes, that was the issue for me. I was on PYthon3.6 and scalene needs a minimum of python 3.7. In 3.6, it picks up pythons standard `threading` library I guess.

Thanks, maybe it's better to include the Python version in the README.

**Comment by jennyandvictor** [comment]
For anybody else who lands here after trying to install and run Scalene for the first time in a Python 3.6 environment (e.g., Ubuntu 18.04): there's a simple solution, install a slightly older version of Scalene:
```
pip3 install scalene==1.3.3
```
