### ISSUE TITLE
Scalene: Program did not run for long enough to profile

### ISSUE THREAD

**Issue by pbl357** [plasma-umass/scalene#229]
**Describe the bug**
i meet two error when i run my code
if i run this example code

> import time
def test():
    i=3;
    while i>0:
        print("test")
        time.sleep(10)
        i=i-1
test()

it occur the error

> ...
 File "/usr/lib64/python3.6/site-packages/scalene/scalene_profiler.py", line 815, in allocation_signal_handler_helper
    if threading._active_limbo_lock.locked() or threading._shutdown_locks_lock.locked():  # type: ignore
AttributeError: module 'threading' has no attribute '_shutdown_locks_lock'

and then i run my project about `resnet50 model`, it occur 

> Scalene: Program did not run for long enough to profile

**Desktop (please complete the following information):**
Name: scalene
Version: 1.3.6
Summary: Scalene: A high-resolution, low-overhead CPU, GPU, and memory profiler for Python
Home-page: https://github.com/emeryberger/scalene
Author: Emery Berger
Author-email: emery@cs.umass.edu
License: Apache License 2.0
Location: /usr/local/lib/python3.7/site-packages
Requires: numpy, rich, cloudpickle, nvidia-ml-py
Required-by:

OS:CentOS Linux release 7.6.1810 (Core)

**Comment by jaltmayerpizzorno** [comment]
> > File "/usr/lib64/python3.6/site-packages/scalene/scalene_profiler.py", line 815, in allocation_signal_handler_helper
> > if threading._active_limbo_lock.locked() or threading._shutdown_locks_lock.locked():  # type: ignore
> > AttributeError: module 'threading' has no attribute '_shutdown_locks_lock'

That code isn't part of Scalene 1.3.6...  Could you refresh your scalene (`pip3 uninstall scalene; pip3 install scalene`) install and try again?

> and then i run my project about `resnet50 model`, it occur
> 
> > Scalene: Program did not run for long enough to profile

Scalene is a sampling profilers, so that can be normal, if the program didn't run long enough.  How long did it run for?

.. Juan

**Comment by emeryberger** [comment]
I think the problem is that Scalene doesn't support Python 3.6 (only 3.7 and up).

**Comment by pbl357** [comment]
> > > File "/usr/lib64/python3.6/site-packages/scalene/scalene_profiler.py", line 815, in allocation_signal_handler_helper
> > > if threading._active_limbo_lock.locked() or threading._shutdown_locks_lock.locked():  # type: ignore
> > > AttributeError: module 'threading' has no attribute '_shutdown_locks_lock'
> 
> That code isn't part of Scalene 1.3.6... Could you refresh your scalene (`pip3 uninstall scalene; pip3 install scalene`) install and try again?
> 
> > and then i run my project about `resnet50 model`, it occur
> > > Scalene: Program did not run for long enough to profile
> 
> Scalene is a sampling profilers, so that can be normal, if the program didn't run long enough. How long did it run for?
> 
> .. Juan

two or three minutes,maybe i should use loop

**Comment by pbl357** [comment]
> I think the problem is that Scalene doesn't support Python 3.6 (only 3.7 and up). In theory, this is supposed to be guaranteed by `pip`. We should probably add a message to that effect on startup.

yeah, i found it should be python 3.7 or up after scalene 1.3.4, so i install two python env
