### ISSUE TITLE
Detect that the profiled script failed

### ISSUE THREAD

**Issue by nixjdm** [plasma-umass/scalene#239]
**Is your feature request related to a problem? Please describe.**
I would like to profile a script and have scalene exit with the same exit code as the underlying script. That way, if this profiled script run was initiated by some sort of process scheduler, the error could be detected and dealt with.

mcve of the current state:

```python
# fail.py
def divide():
    5/0

if __name__ == "__main__":
    divide()
```

```
$ scalene fail.py
Error in program being profiled:
 division by zero
Traceback (most recent call last):
  File "/[path]/scalene/scalene_profiler.py", line 1198, in profile_code
    exec(code, the_globals, the_locals)
  File "fail.py", line 5, in <module>
    divide()
  File "fail.py", line 2, in divide
    5/0
ZeroDivisionError: division by zero
Scalene: Program did not run for long enough to profile.
$ echo $?
0
```

Ideally that last line would be `1`. Considering scalene ran correctly, perhaps we can enable exit code pass-through with a flag?

**Comment by emeryberger** [comment]
Thanks for your report! Fixed with https://github.com/plasma-umass/scalene/commit/5dd245a0a30c12db00f86ea89582c88f55572fb3.
