### ISSUE TITLE
Scalene: Program did not run for long enough to profile.

### ISSUE THREAD

**Issue by samanemami** [plasma-umass/scalene#242]
**Describe the bug**
Scalene does not work on any python script. When I am trying to run scalene, it produces the following error;
Scalene: Program did not run for long enough to profile.

**To Reproduce**
%scalene pythonfile.py

**Expected behavior**
The output of the profiler

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Editor VSCode
 - Version 1.3.11

**log**
<code>Python
Exception in thread Thread-1:
Traceback (most recent call last):
  File "c:\users\users\appdata\local\programs\python\python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "c:\users\users\appdata\local\programs\python\python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\users\appdata\local\programs\python\python37\lib\site-packages\scalene\scalene_profiler.py", line 304, in timer_thang
    signal.raise_signal(ScaleneSignals.cpu_signal)
AttributeError: module 'signal' has no attribute 'raise_signal'

Scalene: Program did not run for long enough to profile.
</code>

**Aditional information**
I also checked the [issue](https://github.com/plasma-umass/scalene/issues/51), and it seems the problem is still there!

**Comment by jaltmayerpizzorno** [comment]
I'm sorry about that, but scalene's native Windows port currently requires Python 3.8 or later.  It should be viewed as an "early alpha" port...  The current builds on pypi should enforce that requirement.
