### ISSUE TITLE
No memory allocation columns in output

### ISSUE THREAD

**Issue by GeorgeDoughty** [plasma-umass/scalene#243]
**Describe the bug**
When running scalene on a simple script there are no columns relating to memory allocation.

**To Reproduce**
1. Run basic_scalene.py through scalene.

**Expected behavior**
When running scalene for CPU, GPU and Memory Allocation data to be displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/74251029/126343640-d7c1b8fa-dcbf-4de2-b977-ce37816b63bd.png)
![image](https://user-images.githubusercontent.com/74251029/126343896-bf378955-afd2-4dbe-830e-8eacf6f20acc.png)
![image](https://user-images.githubusercontent.com/74251029/126344320-44dcdea3-0ecb-441d-99dc-f538a45e1ee7.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Python 3.8.5
 - Scalene 1.3.12 (pip installed)

**Additional context**
GPU data does show for larger operations.

**Comment by emeryberger** [comment]
Windows is not currently supported for memory profiling, so this is expected behavior.
