### ISSUE TITLE
Profiling python module

### ISSUE THREAD

**Issue by teristam** [plasma-umass/scalene#244]
**Is your feature request related to a problem? Please describe.**
I would like to profile my code as a module. I typically run it in command line like `python -m mypackage.mymodule`

**Describe the solution you'd like**
some addition flag to enable running as a module e.g. `scalene -m mypackage.mymodule`

**Describe alternatives you've considered**
We can create a wrapper script for the module and run it instead, but that's very inconvenient.

Thanks!

**Comment by dlopes7** [comment]
If anyone arrives here like me, this is how you work around it:

```
import runpy

runpy.run_module('<module_name>', run_name='__main__')
```
