### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by GIS-PuppetMaster** [plasma-umass/scalene#245]
**Describe the bug**
My work directory is like 
/work
-/A1
--/A2
---a.py
-/B1
--/B2
---main.py
The is `sys.path.append('../../')` in the top of main.py, I import a.py like `import A1.A2.a`. When using `scalene main.py` to launch profiler, there is an exception like 'can not found module A1.A2.a'

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - python 3.9.6

**Comment by emeryberger** [comment]
Works for me with repository version of Scalene, on both Mac and Ubuntu 20.

`work/A1/A2/a.py`:
```Python
print("a.py")
```

`work/B1/B2/main.py`:
```Python
import sys
sys.path.append('../..')

import A1.A2.a

print("successful import")
```

```shell
% cd work/B1/B2
% scalene main.py                            
a.py
successful import
Scalene: Program did not run for long enough to profile.
```
[issue245.tar.gz](https://github.com/plasma-umass/scalene/files/7842583/issue245.tar.gz)
