### ISSUE TITLE
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'

### ISSUE THREAD

**Issue by rmcgibbo** [plasma-umass/scalene#250]
**Describe the bug**
I got a traceback `TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'` while running profiling.

**To Reproduce**
Unfortunately, the code is proprietary so I can't share a full repo.

**Screenshots**
![image](https://user-images.githubusercontent.com/641278/128752560-9fb9975f-4ea4-4c18-a5c9-20ca5f7ed3ca.png)

**Desktop (please complete the following information):**
 - OS: CentOS 7 Linux
- Python: 3.7
- Scalene 2.5.2

**Additional context**
It's possible that the issue is that while the code was running under the profiler, I may have been (okay, I was) poking it with gdb and looking at the backtrace, and then quitting gdb.

**Comment by emeryberger** [comment]
Hi - 2.5.2 is not an actual version number for Scalene, which is 1.3.12 (at this writing). Can you clarify? Also, IIRC Scalene requires Python 3.8 for Windows. Please try installing via `pip` and let us know what happens.

**Comment by rmcgibbo** [comment]
Sorry, it looks like it's actually `1.3.12`. We appeared to just made an error in naming it in our system. But yes, it is python3.7 on Linux.

**Comment by emeryberger** [comment]
We now have an `assert` in place that should be triggered if this situation ever arises again (it never should...). You can update with `python3 -m pip install git+https://github.com/plasma-umass/scalene`. I suspect that gdb might be the culprit in that it could be interfering with the signals that Scalene relies on (these are all here: https://github.com/plasma-umass/scalene/blob/master/scalene/scalene_signals.py).

**Comment by rmcgibbo** [comment]
Sounds good. Thanks!
