### ISSUE TITLE
Installation via Brew on Apple M1 broken

### ISSUE THREAD

**Issue by HansBambel** [plasma-umass/scalene#252]
**Describe the bug**
I installed scalene via homebrew on my Apple M1, but I get the following error:
```
dyld: could not load inserted library '/opt/homebrew/Cellar/scalene/HEAD-f097186/lib/libscalene.dylib' because no suitable image found.  Did find:
	/opt/homebrew/Cellar/scalene/HEAD-f097186/lib/libscalene.dylib: mach-o, but wrong architecture
	/opt/homebrew/Cellar/scalene/HEAD-f097186/lib/libscalene.dylib: stat() failed with errno=1

/opt/homebrew/bin/scalene: line 2: 49740 Abort trap: 6           OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES DYLD_INSERT_LIBRARIES=/opt/homebrew/Cellar/scalene/HEAD-f097186/lib/libscalene.dylib PYTHONMALLOC=malloc python3 -m scalene "$@"
```

**To Reproduce**
Enter in the terminal:
1. brew tap plasma-umass/scalene
2. brew install --head plasma-umass/scalene/scalene
3. scalene

**Expected behavior**
Profiling works

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.5.1
 - Chip: Apple M1

**Additional context**
I am guessing it is due to the M1-chip architecture. But how would I be able to install a working version of scalene?

**Comment by HansBambel** [comment]
Installing via pip works (after uninstalling the brew version again)

**Comment by emeryberger** [comment]
Could not reproduce on my M1 using the same sequence of commands (I just updated the homebrew HEAD but that shouldn't affect anything), same version of MacOS Big Sur. What version does `g++ --version` report?

**Comment by HansBambel** [comment]
Sorry for only getting back now.
```
Apple clang version 12.0.5 (clang-1205.0.22.11)
Target: arm64-apple-darwin20.6.0
Thread model: posix
```

**Comment by emeryberger** [comment]
Removing homebrew support (see https://github.com/plasma-umass/scalene/issues/747).
