### ISSUE TITLE
Memory consumption of iterators and tempory variables

### ISSUE THREAD

**Issue by JulianWgs** [plasma-umass/scalene#256]
As there is no scalene tag on Stackoverflow and I guess nobody from the maintainers is monitoring Stackoverflow I will post my question here. If that's the wrong place, feel free to close the issue and direct me to the right place. Thank you!

**Describe the bug**
I'm not understanding why a line of code produces such a large memory consumption.

**To Reproduce**

Real use case:
```python
import candas as cd

dbc_db = cd.load_dbc("can/LR17/")

filename = "test.blf"

cd.from_file(dbc_db, filename, always_convert=True)
```
![screenshot](https://user-images.githubusercontent.com/31596773/129526775-ee31b699-fb68-4c69-9f8f-80bce24570d6.png)

Unfortunately I cant easily provide the data need to reproduce the benchmark. Code can be found [here](https://gitlab.com/lionsracing/candas/-/blob/74b12550c5e487161dbbd63edcbbbceb9078265b/candas/dataframe.py#L846-L880).

Therefore here is a simplified example:
```python
ret_value = dict()

for k in range(10**7):
    temp = k*2
    ret_value[k] = temp
```
![screenshot](https://user-images.githubusercontent.com/31596773/129527439-8fcf3fa4-cdc9-45d9-a873-ea88382c52f4.png)

Why do the iterators (log and range) and the temporary variables (dec and temp) have such a large memory footprint?

**Expected behavior**
I expecting that iterators and temporary assignments dont have a large memory consumption. To my understanding they allocate a lot of memory, but its freed and doesnt attribute to memory usage.

**Screenshots**
See above.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.2 LTS
 - Scalene: 1.3.12
 - Python: 3.8.10

**Additional context**
I want to overhaul the decode step anyway reducing the runtime by 50% and probably the memory usage too using chunking.

**Comment by emeryberger** [comment]
Thanks very much for what was actually a tremendously valuable issue! It led to a major overhaul in how Scalene handles memory attribution, which required a fair amount of innovation. Here's the output now (repo version) for your second example:

                                                                     Memory usage: ▁▁▁▁▁▁▁▂▃▄▃▆█▇▆ (max: 958.03MB, growth rate:   0%)                                                                 
                                                                     test/issues/test-issue256.py: % of time =  98.93% out of   1.23s.                                                                
            ╷       ╷       ╷       ╷        ╷       ╷               ╷       ╷                                                                                                                        
       Line │Time   │–––––– │–––––– │Memory  │–––––– │–––––––––––    │Copy   │                                                                                                                        
            │Python │native │system │Python  │avg    │timeline/%     │(MB/s) │test/issues/test-issue256.py                                                                                            
     ╺━━━━━━┿━━━━━━━┿━━━━━━━┿━━━━━━━┿━━━━━━━━┿━━━━━━━┿━━━━━━━━━━━━━━━┿━━━━━━━┿━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸
          1 │       │       │       │        │       │               │       │ret_value = dict()                                                                                                      
          2 │       │       │       │        │       │               │       │                                                                                                                        
          3 │   14% │    2% │   2%  │        │       │               │       │for k in range(10**7):                                                                                                  
          4 │   30% │    5% │   3%  │        │       │               │       │    temp = k*2                                                                                                          
          5 │   25% │   10% │   7%  │  66%   │  213M │▁▂▄▃▆█▇▆▁ 100% │   226 │    ret_value[k] = temp                                                                                                 
          6 │       │       │       │        │       │               │       │                                                                                                                        
            ╵       ╵       ╵       ╵        ╵       ╵               ╵       ╵                                                                                                                        
     Top net memory consumption, by line:
     (1)     5:   640 MB                                                                                                                                                                               

We hope to release this as a new version to PyPi in short order; if you would like to try it out now, just install it directly from the repo (`python3 -m pip install git+https://github.com/plasma-umass/scalene`).

**Comment by JulianWgs** [comment]
Awesome! Glad I could help :)
