### ISSUE TITLE
Possible Bug

### ISSUE THREAD

**Issue by DKenefake** [plasma-umass/scalene#258]
**Describe the bug**
I was using this to profile an optimization solver I am developing and have run into what I think is a memory leak.  I created a minimal reproducible example where we solve large linear systems. I have blue screened with a STORE_DATA_STRUCTURE_CORRUPTION error once and soft-locked the computer when I tried to repeat the minimal example. 

This anomalous behavior did not happen when not profiling. However, I am not ruling out that this behavior could also be caused by system instability on my side, where the profiler is stressing the system in a 'perfect storm' scenario. 

**To Reproduce**

Run the Following Command in the terminal with example.py in the same directory

```bash
scalene .\example.py
```

example.py
```python
import numpy

def work(n:int):

    for i in range(n):
        A = numpy.random.randn(20000,20000)
        b = numpy.random.randn(20000,1)
        numpy.linalg.solve(A.T@A, b)
        
work(10)
```

**Expected behavior**
A profile of the above code.

**Desktop (please complete the following information):**

This occurred when running on a terminal in JupyterLab 3.0.11.

 - OS: Windows 10 
 - Browser Chrome
 - Version Python 3.9.1

If you need any more information, please feel free to reach out.

**Comment by emeryberger** [comment]
Great catch! I may have tracked it down. Please try `python3 -m pip install git+https://github.com/plasma-umass/scalene` and verify that it solved your problem (it solves it on my end).

**Comment by emeryberger** [comment]
I ran this for hours with the latest version and the memory leak is gone, so I am closing this issue. Thanks again!
