### ISSUE TITLE
Scalene - accumulative memory vs instant memory

### ISSUE THREAD

**Issue by emeryberger** [plasma-umass/scalene#266]
### Discussed in https://github.com/plasma-umass/scalene/discussions/265

<div type='discussions-op-text'>

<sup>Originally posted by **sjvdm** September  7, 2021</sup>
Scalene is really a super useful tool - thanks to the author!

I wanted to discuss clarity around accumulative memory vs instant memory. See Sample code below. When looped once, scalene profiles the functions using 4GB. When looped 5 times,  scalene profiles the function as using 20GB (which is accumulative). is there a way to get the max instant (aka 4GB) from the profile without only running the loop once?

```
import pandas as pd
import numpy as np
import gc

def f():
    print('called f')
    #Uses around 4GB of memory when looped once
    df = np.ones(500000000)
    
#Uses around 20GB of memory when looped 5 times
for i in range(0,5):
    f()
```</div>

**Comment by emeryberger** [comment]
This is not currently possible in Scalene, but it could be an option.

The only approach I am aware of for counting lines is via `https://docs.python.org/3/library/sys.html#sys.settrace`. In my tests, this can slow down pure Python execution by almost 10x, which makes it a dealbreaker as a default. On the other hand, for programs like the one above that make extensive use of native modules like numpy and Pandas, the overhead is negligible, so it could be optionally activated.

**Comment by corleyma** [comment]
@emeryberger Does Scalene not track de-allocations?

**Comment by emeryberger** [comment]
It does, but these often occur well after the line where the allocations took place.

**Comment by emeryberger** [comment]
This behavior is now fixed in the repository: we came up with an efficient way to get this information (!) and now Scalene reports average ("instant") memory consumption.

[test-issue266.txt](https://github.com/plasma-umass/scalene/files/7220137/test-issue266.txt)
.

**Comment by sjvdm** [comment]
Ahh awesome. Thanks so much - this would make profiling and optimizing recurring functions a lot easier.

**Comment by AADeLucia** [comment]
I know this is closed, but I'm wondering if there is possibly an issue with this accumulation memory with the `--profile-interval` flag? This might be program-specific but the setup/issue is as follows:

- Training a PyTorch model in a loop
- OOM (swap/RAM OOM, not CUDA) after about 20 hours of training (about 90% through epoch 1)
- Scalene is showing max memory growing very quickly (# at the top) but attributing the accumulation to a specific line within the loop... but the actual MB at that line is very low, only about 3MB

Example with the HTML printout:

```shell
scalene byte_model.py \
  --outfile "scalene.html" \
  --html \
  --profile-interval 1 \
  --data-dir "${DATA_DIR}" \
  --output-dir "${WORK_DIR}" \
  --batchsize 15 \
  --epochs 1 \
  --debug
```

[scalene.html.pdf](https://github.com/plasma-umass/scalene/files/7622676/scalene.html.pdf)

**Comment by emeryberger** [comment]
Looks like I accidentally disabled updating the velocity statistic while temporarily disabling an experimental leak detector, sigh. I just restored the velocity stats in the latest commit.

It's worth noting that the average memory reported is just the average amount of memory allocated by a particular line: it is agnostic to whether it is eventually reclaimed or not.

However, as I said, there's code in Scalene designed to find leaks; it's disabled because it has been a bit too over-sensitive in our tests, but you can enable it by changing the `if False` on line 1101 of `scalene/scalene_profiler.py` to `if True`. Let me know how it works; also, please feel free to join the Scalene Slack to discuss, since you seem to have a nasty issue! Thanks.

**Comment by AADeLucia** [comment]
I pulled the latest version and Scalene seems to be making my code hang. I see this at the beginning of my output

```shell
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/aadelucia/miniconda3/envs/minerva-proj/lib/python3.8/threading.py", line 932, 
in _bootstrap_inner
    self.run()
  File "/home/aadelucia/miniconda3/envs/minerva-proj/lib/python3.8/threading.py", line 870, 
in run
    self._target(*self._args, **self._kwargs)
  File "/home/aadelucia/scalene/scalene/scalene_sigqueue.py", line 41, in run
    self.process(*item)
  File "/home/aadelucia/scalene/scalene/scalene_profiler.py", line 695, in cpu_sigqueue_proc
essor
    Scalene.output_profile()
  File "/home/aadelucia/scalene/scalene/scalene_profiler.py", line 633, in output_profile
    did_output: bool = output.output_profiles(
  File "/home/aadelucia/scalene/scalene/scalene_output.py", line 672, in output_profiles
    avg_mallocs[keys[index]],
KeyError: 101
```

**Comment by emeryberger** [comment]
I've tried but failed to reproduce your error, so a minimum working example would be helpful. In the meanwhile, for ease of testing, I've promoted `--memory-leak-detector` to an experimental command-line parameter (disabled unless this parameter appears).

**Comment by AADeLucia** [comment]
I pulled the latest version again and it's working! Thank you!

**Comment by emeryberger** [comment]
Super! Thanks for your reports and please let us know if Scalene solves your problem (or not!).
