### ISSUE TITLE
Scalene doesn't generate output in case of SIGTERM

### ISSUE THREAD

**Issue by ScientiaEtVeritas** [plasma-umass/scalene#268]
I'm running some kind of daemon/webserver via `python -m scalene --html --outfile profile.html main.py &`, i.e., there is no defined end of the process. Instead, I usually end the process with `kill <pid>` (resulting in a SIGTERM signal), however it seems scalene doesn't generate the output file in this case. Instead, it's printing `Scalene error: received signal SIGTERM`. I'm not sure this should be the expected behaviour. For now, is there any way to trigger the generation of the file manually?

**Comment by emeryberger** [comment]
Right now, Scalene doesn't handle `SIGTERM` specially: it certainly could force output of profiles.

However, Scalene does have support for profiling long-running processes. It explicitly supports periodic output of profiling with `--profile-interval`, so you can get a profile every N seconds (overwriting past profiles, if writing to a file via `--outfile`).

>  `--profile-interval` PROFILE_INTERVAL
>                        output profiles every so many seconds (default: inf)

Seems easy enough to catch `SIGTERM` and ensure we output profiles, but perhaps this is good enough in the interim?

**Comment by emeryberger** [comment]
This feature is now implemented in the repository version. We hope to release a new version to PyPi shortly. Thanks for the suggestion!
