### ISSUE TITLE
Scalene error out when a third party process is spawned `Scalene error: received signal SIGSEGV`

### ISSUE THREAD

**Issue by kouros51** [plasma-umass/scalene#276]
**Describe the bug**

We are developing a home grown sanity test suite for some web application that we have. We developed and engine that is using selenium and  chrome-driver to to pilot those tests and running in parallel using a `ThreadPoolExecutor`. All the test are scheduled using a third party library called `apscheduler`.

We wanted to profile the application to make sure that we don't have any memory leaks or issues in the orchestration of the tests. Since we spawn several browser, do the tests, return a result and kill them, we wanted to make sure that we free resources as expected.

That said when we run scalene to profile the engine we run into a `SIGSEGV` error.

Please note, I'm on Mac OS Big Sur and tested it also on Linux and in a docker environment.

**To Reproduce**
1. Prepare the environment `cd <working_dir> && python3.9 -m venv venv && source venv/bin/activate`
2. Install chrome driver for your system with the appropriate chrome version to be used with the driver in our case we are using `94.0.4606.61` for both
3. Install the python requirements
```
APScheduler==3.7.0
selenium==3.141.0
scalene==1.3.12
```
4.  Test this script before profiling
```python
from concurrent.futures import Future
from concurrent.futures import ThreadPoolExecutor
from concurrent.futures import as_completed
from datetime import datetime
from typing import List

from apscheduler.schedulers.blocking import BlockingScheduler
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.remote.webdriver import WebDriver


def create_browser() -> WebDriver:
    chrome_options = Options()

    chrome_options.add_argument('--headless')
    chrome_options.add_argument('--disable-gpu')
    chrome_options.add_argument('--no-sandbox')
    chrome_options.add_argument('--disable-setuid-sandbox')
    chrome_options.add_argument('--disable-dev-shm-usage')
    chrome_options.add_argument('--start-maximized')
    chrome_options.add_argument('--window-size=1920,1080')
    chrome_options.add_argument(
        '--user-agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 '
        '(KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36'
    )
    chrome_options.add_argument('ignore-certificate-errors')
    chrome_options.add_experimental_option('prefs', {
        'download': {
            'prompt_for_download': False,
            'default_directory': './'
        }
    })

    return webdriver.Chrome(options=chrome_options)


def first_test(url: str) -> str:
    with create_browser() as browser:
        browser.get(url)

    return f'Test for {url} succeeded'


def second_test(url: str) -> str:
    with create_browser() as browser:
        browser.get(url)

    return f'Test for {url} failed'


def third_test(url: str) -> str:
    with create_browser() as browser:
        browser.get(url)

    return f'Test for {url} succeeded'


def master_test_aggregator() -> None:
    with ThreadPoolExecutor(max_workers=3) as executor:
        futures_results: List[Future[str]] = [
            executor.submit(first_test, 'https://google.com'),
            executor.submit(second_test, 'https://duckduckgo.com/'),
            executor.submit(third_test, 'https://slack.com'),
        ]

        for future in as_completed(futures_results):
            print(future.result())


if __name__ == '__main__':
    scheduler = BlockingScheduler()

    scheduler.add_job(
        func=master_test_aggregator,
        trigger='interval',
        seconds=15,
        next_run_time=datetime.now(),
        coalesce=True
    )

    try:
        scheduler.start()
    except (KeyboardInterrupt, SystemExit):
        scheduler.shutdown()

```
You will see that the script works perfectly, and simulate that using three workers we visiting some site and returning a result.
5. Now, try to profile the script with:
```bash
scalene --reduced-profile repro.py
```
and you would be able to see an error like:
```
Scalene error: received signal SIGBUS
```

**Expected behaviour**
We were expecting that scalene will succeed to profile the application without errors.

**Desktop (please complete the following information):**
 - OS: Mac OS, Linux, Docker
 - Browser: Chrome(94.0.4606.61), chromedriver(94.0.4606.61)
 - Version: Scalene 1.3.12

**Comment by emeryberger** [comment]
Bug does not reproduce with current (repository) version of Scalene - I was able to successfully run this code under Scalene. I am using a more recent version of Chrome and chromedriver (96) but I believe this was an issue that was fixed in a previous release of Scalene. Please upgrade - thanks!
