### ISSUE TITLE
`Scalene error: received signal SIGSEGV` on Windows Linux Subsystem

### ISSUE THREAD

**Issue by leshchenko1979** [plasma-umass/scalene#284]
**Describe the bug**
Running Scalene on any python script results in this error. I'm running Ubuntu 20 on a Windows Linux Subsystem on Windows 10.

**To Reproduce**
1. Install Windows Linux Subsystem
2. Install Scalene
3. Run Scalene with any script

**Desktop (please complete the following information):**
 - OS: Windows 10 running Ubuntu 20 in a Windows Linux Subsystem

**Comment by leshchenko1979** [comment]
Installed python 3.9 instead of 3.10 -- now it works fine.

**Comment by an99990** [comment]
hi so i am using python 3.8.12 and i still have the issue, any tips on how to solve it ?
