### ISSUE TITLE
When calling Scalene programmatically, it throws error: `python AttributeError: type object 'Scalene' has no attribute '_Scalene__sigqueues'`

### ISSUE THREAD

**Issue by nayana-prashanth** [plasma-umass/scalene#296]
**Describe the bug**
My requirement is to call Scalene programmatically. So, I followed the below steps:
1. pip install -U scalene
2. Import scalene `import scalene` in my program
3. Add import line `from scalene import scalene_profiler` in the program
3. Added the line `scalene_profiler.start()` in my main method.

**To Reproduce**
1. pip install -U scalene
2. Import scalene `import scalene` in my program
3. Add import line `from scalene import scalene_profiler` in the program
3. Added the line `scalene_profiler.start()` in my main method.

**Expected behavior**
My service should have started without any errors.

I see the below error:
```Traceback (most recent call last):
  File "/Users/nayana.rajanna/Projects/example.py", line 48, in <module>
    scalene_profiler.start()
  File "/Users/nayana.rajanna/concord/venv-3.8.5/lib/python3.8/site-packages/scalene/scalene_profiler.py", line 98, in start
    Scalene.start()
  File "/Users/nayana.rajanna/concord/venv-3.8.5/lib/python3.8/site-packages/scalene/scalene_profiler.py", line 1233, in start
    Scalene.enable_signals()
  File "/Users/nayana.rajanna/concord/venv-3.8.5/lib/python3.8/site-packages/scalene/scalene_profiler.py", line 388, in enable_signals
    Scalene.start_signal_queues()
  File "/Users/nayana.rajanna/concord/venv-3.8.5/lib/python3.8/site-packages/scalene/scalene_profiler.py", line 331, in start_signal_queues
    for sigq in Scalene.__sigqueues:
AttributeError: type object 'Scalene' has no attribute '_Scalene__sigqueues'
```

**Screenshots**
![image](https://user-images.githubusercontent.com/6901356/141954788-289b039d-f145-4f80-9b10-5b5d3daa88d0.png)

Version: 
![image](https://user-images.githubusercontent.com/6901356/141954904-f247e097-0a06-464a-b291-7918a47ebd6d.png)

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Version  1.3.16

**Additional context**

**Comment by emeryberger** [comment]
Are you invoking it with `scalene` or `python3 -m scalene`? It won't work just by invoking it with `python3`.

**Comment by emeryberger** [comment]
Clarified with https://github.com/plasma-umass/scalene/commit/14812329dfb07b9d03e1fbbc0392446f064fce1e

**Comment by nayana-prashanth** [comment]
Hi Emery,
Thank you so much for the quick response. So does that mean I have to first use scalene from the command line to run the program and only then I can call it from inside the program to switch profiling on and off? I was hoping to be able to use it just programmatically. 

Thanks,
Nayana

**Comment by emeryberger** [comment]
Yes, that is the current state of affairs. One way or the other, Scalene needs to be able to launch the process using its own environment variable settings (which lets it monitor memory usage).

**Comment by emeryberger** [comment]
See https://github.com/plasma-umass/scalene/issues/240 for more

**Comment by nayana-prashanth** [comment]
> Yes, that is the current state of affairs. One way or the other, Scalene needs to be able to launch the process using its own environment variable settings (which lets it monitor memory usage).

How can I run Scalene within a docker image where I have just my *.whl files copied(not the entire code, so no *.py files)?

**Comment by nayana-prashanth** [comment]
Hi @emeryberger . Can  Scalene run inside docker container in Kubernetes? I tried but it only gives html report for python program passed in the command line. Report does not include details for other sub-programs called by the main program.
Running scalene locally gives all sub-programs memory usage details in addition to the main program.
