### ISSUE TITLE
Truncated timeline display

### ISSUE THREAD

**Issue by AADeLucia** [plasma-umass/scalene#300]
**Describe the bug**
I am running scalene with the --html and --outfile options but the resulting file has truncated display for the timeline. 

**To Reproduce**

I am calling scalene with 
```shell
#!/bin/bash

scalene byte_model.py \
  --outfile "scalene.html" \
  --html \
  --profile-interval 1 \
  --data-dir "${DATA_DIR}" \
  --output-dir "${WORK_DIR}" \
  --batchsize 15 \
  --epochs 1 \
  --debug
```

**Expected behavior**
I expect it to look more like the printouts in #188 

**Screenshots**
![image](https://user-images.githubusercontent.com/13154289/143932456-205d1f3f-b92a-4d2e-9b5b-acb1b817fead.png)

**Desktop (please complete the following information):**
 - Ubuntu 20.04.3 LTS
 - Version 1.3.16 (cloned the repo and installed)

**Comment by emeryberger** [comment]
This looks like a simple formatting issue, but if you can send along a minimum working example, that would help (the code you are running is fine if you are willing to share and if the dataset is publicly available). Thanks!

**Comment by emeryberger** [comment]
I just pushed a change that adds one character to the length of the timeline column, which affects the case when 100% of the allocations come from one line (as above). Please pull and see if this resolves your issue. Thanks.

**Comment by AADeLucia** [comment]
That worked, I can see the full line now. Thank you! 
![image](https://user-images.githubusercontent.com/13154289/143978315-6e1fe7c4-81b0-4706-b7ea-bd5937fccb62.png)
