### ISSUE TITLE
Install failed on MacOS 10.13.6 (Unsupported arch.)

### ISSUE THREAD

**Issue by ridgeworks** [plasma-umass/scalene#307]
**Describe the bug**
Using pip to install scalene fails to build (compile) -  Unsupported architecture messages.

**To Reproduce**
1. python3 -m pip install -U scalene
2. See error:
```
    fatal error: too many errors emitted, stopping now [-ferror-limit=]
    20 errors generated.
    error: command '/usr/bin/clang' failed with exit code 1
```

**Expected behavior**
Successful install.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 10.13.6
 - Python: 3.10.1
 - pip: 21.3.1

**Additional context**
Compiler command line from terminal:
```
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -g -I. -Ivendor/Heap-Layers -Ivendor/Heap-Layers/utility -I/Library/Frameworks/Python.framework/Versions/3.10/include/python3.10 
-c src/source/get_line_atomic.cpp 
-o build/temp.macosx-10.9-universal2-3.10/src/source/get_line_atomic.o 
-std=c++14  -arch x86_64 -arch arm64

  In file included from src/source/get_line_atomic.cpp:2:
  In file included from /Library/Frameworks/Python.framework/Versions/3.10/include/python3.10/Python.h:11:
  In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/limits.h:58:
  In file included from /Library/Developer/CommandLineTools/usr/lib/clang/10.0.0/include/limits.h:37:
  In file included from /usr/include/limits.h:63:
  /usr/include/sys/cdefs.h:763:2: error: Unsupported architecture
  #error Unsupported architecture
   ^
  In file included from src/source/get_line_atomic.cpp:2:
  In file included from /Library/Frameworks/Python.framework/Versions/3.10/include/python3.10/Python.h:11:
  In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/limits.h:58:
  In file included from /Library/Developer/CommandLineTools/usr/lib/clang/10.0.0/include/limits.h:37:
  In file included from /usr/include/limits.h:64:
  /usr/include/machine/limits.h:8:2: error: architecture not supported
  #error architecture not supported
   ^
          etc ....
```
Note that compiler `arch` option specifies `arm64` which isn't supported on this version of MacOS tools.

`setup.py`  appears to check for OS > 10.15.4, so not sure why this is happening.

**Comment by emeryberger** [comment]
Thanks for the report. What's your version of clang?

`clang --version`

We probably need to test for older versions, so this is useful information. The solution will be to upgrade Xcode.

**Comment by ridgeworks** [comment]
$ clang --version
Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

I'm not a C programmer so I don't pay much attention to Xcode.

**Comment by emeryberger** [comment]
Yep, that's quite old. The current version is 13, though I expect version 12 would work fine. Please update Xcode and verify that this works for you - if that's the case, we'll add a test. Thanks!

**Comment by emeryberger** [comment]
I just pushed a change that should allow compilation to work without updating XCode, so if it's not too late, please try this:

`python3 -m pip install git+https://github.com/plasma-umass/scalene`

Thanks!

**Comment by ridgeworks** [comment]
Yes, thank you:

Successfully built scalene
Installing collected packages: scalene
  WARNING: The script scalene is installed in '/Library/Frameworks/Python.framework/Versions/3.10/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed scalene-1.3.16


It would have taken a while to find an XCode (command line tools) that was compatible.

**Comment by emeryberger** [comment]
Excellent - thanks again for the report and the test!
