### ISSUE TITLE
Slack Link Expired

### ISSUE THREAD

**Issue by atw1020** [plasma-umass/scalene#309]
This isn't exactly a bug, but an issue with the readme. The slack link has expired and no longer works. A new & permanent link ought to be posted.

**Comment by emeryberger** [comment]
Thanks! Fixed with https://github.com/plasma-umass/scalene/commit/754410f00776e5e229d6106211ebbb3ccfe27c01. Invite added to `README.md` and here for convenience: [Scalene community Slack](https://join.slack.com/t/scaleneprofil-jge3234/shared_invite/zt-110vzrdck-xJh5d4gHnp5vKXIjYD3Uwg)
