### ISSUE TITLE
Time based memory profiling possible?

### ISSUE THREAD

**Issue by ma-sadeghi** [plasma-umass/scalene#312]
Similar to `memory_profiler`'s `mprof` tool, is it possible to do time based memory profiling in `scalene`? and generate graphs like the one below:
![image](https://user-images.githubusercontent.com/14086031/147887388-a6375a90-d56a-4ccd-b47a-f968e538c120.png)

**Comment by emeryberger** [comment]
It might not be clear that Scalene already produces a reduced, approximate version of such a graph - these are the "sparklines" at the top and on every line with significant memory allocation activity.

**Comment by ma-sadeghi** [comment]
@emeryberger Thanks for your quick reply! Right, I almost missed that. It'd be cool if that graph could be sort of extracted as a standalone graph.

**Comment by emeryberger** [comment]
You might consider filing it as an issue / feature request. It'd help immensely to have some concrete reasons as to why it would be useful, esp. more useful than Scalene's existing functionality. Thanks!

**Comment by emeryberger** [comment]
We will soon be releasing a new version of Scalene with a nice web-based GUI; this is in the current repo. Check it out here: https://github.com/plasma-umass/scalene-gui. Each memory footprint is now high resolution, memory usage over execution time.

**Comment by emeryberger** [comment]
FYI the new GUI is now incorporated into the latest releases of Scalene.
