### ISSUE TITLE
Loosen up version requirements in install_requires

### ISSUE THREAD

**Issue by QuLogic** [plasma-umass/scalene#314]
**Describe the bug**
There are currently two explicit version pins in `setup.py`, for `nvidia-ml-py` and `wheel`. The version requirements in `install_requires` should not be so strict. [See the second last paragraph of this section from PyPA.](https://packaging.python.org/en/latest/discussions/install-requires-vs-requirements/#install-requires)

Additionally, `wheel` is not imported anywhere in this package. It is a _build_ requirement (and only if you're building a wheel), not a runtime requirement and should not be listed in `install_requires` at all.

**Expected behavior**
The latest version of `nvidia-ml-py` is installed when this package is installed. `wheel` is not touched at all.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Fedora
 - Browser [e.g. chrome, safari] why?

**Comment by emeryberger** [comment]
Thanks - we'd welcome a PR!

**Comment by emeryberger** [comment]
Updated with https://github.com/plasma-umass/scalene/commit/48f9ce9efee2c4916e72eb245f92058ac61fae80. Please re-open if this isn't sufficient. Thanks!

**Comment by QuLogic** [comment]
That is good, thanks!
