### ISSUE TITLE
Output only contains: Time Python, Native, System

### ISSUE THREAD

**Issue by KlausKrauss** [plasma-umass/scalene#326]
This is an awesome library- I pip installed today and tried running and adjusting the parameters to see the memory usage and I only get the time profiling.  I've looked through the documentation and the -help parameters and I was wondering if this is an issue or if you need to explicitly request this?  Thanks.

'scalene test.txt fake_flat_file.py'

![Capture](https://user-images.githubusercontent.com/75275099/149189968-4650876e-be99-4b72-9c98-adab0375a7be.JPG)

**Comment by emeryberger** [comment]
What OS are you using? If it's Windows, as I suspect, unfortunately, Scalene does not yet support memory/GPU/copy profiling. It does work on WSL2, though, if that's an option (as well as Mac and Linux).

**Comment by KlausKrauss** [comment]
I am using windows- this is good to know!  Thanks.
