### ISSUE TITLE
Cannot load ipython extension

### ISSUE THREAD

**Issue by luke-bassett** [plasma-umass/scalene#333]
**The bug**
Cannot load the scalene extension in a jupyter notebook.

```
!pip install scalene

Requirement already satisfied: scalene in ./env/lib/python3.8/site-packages (1.4.0)
Requirement already satisfied: numpy in ./env/lib/python3.8/site-packages (from scalene) (1.22.1)
Requirement already satisfied: nvidia-ml-py>=11.450.51 in ./env/lib/python3.8/site-packages (from scalene) (11.515.0)
Requirement already satisfied: rich>=9.2.0 in ./env/lib/python3.8/site-packages (from scalene) (11.0.0)
Requirement already satisfied: cloudpickle>=1.5.0 in ./env/lib/python3.8/site-packages (from scalene) (2.0.0)
Requirement already satisfied: commonmark<0.10.0,>=0.9.0 in ./env/lib/python3.8/site-packages (from rich>=9.2.0->scalene) (0.9.1)
Requirement already satisfied: colorama<0.5.0,>=0.4.0 in ./env/lib/python3.8/site-packages (from rich>=9.2.0->scalene) (0.4.4)
Requirement already satisfied: pygments<3.0.0,>=2.6.0 in ./env/lib/python3.8/site-packages (from rich>=9.2.0->scalene) (2.11.2)
```
```
%load_ext scalene

The scalene module is not an IPython extension.
```

**Desktop**
 - OS: macOS Monterey 12.1
 - Chip: Apple M1

**Comment by emeryberger** [comment]
Please try installing the latest version (1.4.1). Works for me on an M1, same OS.

**Comment by emeryberger** [comment]
Closing as it works for me; please re-open if you have any issues - thanks.

**Comment by luke-bassett** [comment]
Thanks for the quick reply.

I tried and it did not work. I also tried using scalene on the command line (using this command `scalene test.py`) and had an error there as well, here is the error text:

```
Traceback (most recent call last):
  File "<project_path>/env/bin/scalene", line 5, in <module>
    from scalene.__main__ import main
  File "<project_path>/env/lib/python3.8/site-packages/scalene/__main__.py", line 4, in <module>
    from scalene import scalene_profiler
  File "<project_path>/env/lib/python3.8/site-packages/scalene/scalene_profiler.py", line 46, in <module>
    from scalene.scalene_mapfile import ScaleneMapFile
  File "<project_path>/env/lib/python3.8/site-packages/scalene/scalene_mapfile.py", line 6, in <module>
    from scalene import get_line_atomic  # type: ignore
ImportError: dlopen(<project_path>/env/lib/python3.8/site-packages/scalene/get_line_atomic.abi3.so, 0x0002): tried: '<project_path>/env/lib/python3.8/site-packages/scalene/get_line_atomic.abi3.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/get_line_atomic.abi3.so' (no such file), '/usr/lib/get_line_atomic.abi3.so' (no such file)
```

It does seem somehow related to the M1 architecture.

More env info:
- Python 3.8.12
- pip freeze output:
```
appnope==0.1.2
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
asttokens==2.0.5
attrs==21.4.0
backcall==0.2.0
black==21.12b0
bleach==4.1.0
cffi==1.15.0
click==8.0.3
cloudpickle==2.0.0
colorama==0.4.4
commonmark==0.9.1
debugpy==1.5.1
decorator==5.1.1
defusedxml==0.7.1
entrypoints==0.3
executing==0.8.2
importlib-resources==5.4.0
ipykernel==6.7.0
ipython==8.0.1
ipython-genutils==0.2.0
jedi==0.18.1
Jinja2==3.0.3
jsonschema==4.4.0
jupyter-client==7.1.1
jupyter-core==4.9.1
jupyterlab-pygments==0.1.2
MarkupSafe==2.0.1
matplotlib-inline==0.1.3
mistune==0.8.4
mypy-extensions==0.4.3
nbclient==0.5.10
nbconvert==6.4.0
nbformat==5.1.3
nest-asyncio==1.5.4
notebook==6.4.7
numpy==1.22.1
nvidia-ml-py==11.515.0
packaging==21.3
pandas==1.3.5
pandocfilters==1.5.0
parso==0.8.3
pathspec==0.9.0
pexpect==4.8.0
pickleshare==0.7.5
platformdirs==2.4.1
prometheus-client==0.12.0
prompt-toolkit==3.0.24
ptyprocess==0.7.0
pure-eval==0.2.1
pycparser==2.21
Pygments==2.11.2
pymongo==4.0.1
pyparsing==3.0.6
pyrsistent==0.18.1
python-dateutil==2.8.2
pytz==2021.3
pyzmq==22.3.0
rich==11.0.0
scalene==1.4.1
Send2Trash==1.8.0
six==1.16.0
stack-data==0.1.4
terminado==0.12.1
testpath==0.5.0
tomli==1.2.3
tornado==6.1
traitlets==5.1.1
typing_extensions==4.0.1
wcwidth==0.2.5
webencodings==0.5.1
zipp==3.7.0
```

**Comment by luke-bassett** [comment]
@emeryberger I don't think I have permission to re-open this issue, however I am still having trouble getting scalene working on my M1 mac.

**Comment by emeryberger** [comment]
I am guessing you have an old version of XCode, though I thought we dealt with that issue. Please try to build from the repo - `python3 -m pip install git+https://github.com/plasma-umass/scalene`, and let us know what `clang++ --version` says.

**Comment by luke-bassett** [comment]
That worked! Thanks a bunch. 

Here is the output of `clang++ --version`

```
Apple clang version 13.0.0 (clang-1300.0.29.30)
Target: arm64-apple-darwin21.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by TeamDman** [comment]
Note that Google Colab uses python 3.7, pip install works but it fails to load under jupyter
![image](https://user-images.githubusercontent.com/9356891/197411811-d38604fe-7476-475e-babc-163fa790b1e9.png)

From the scalene readme the supported versions are ![](https://img.shields.io/pypi/pyversions/scalene.svg?style=flat-square)

Trying the above suggestion of installing from src expectedly fails

![image](https://user-images.githubusercontent.com/9356891/197411890-1ce93c6b-4991-49c9-8886-9035dfdf594c.png)

I tried [updating python](https://stackoverflow.com/questions/63168301/how-to-change-the-python-version-from-default-3-5-to-3-8-of-google-colab) in colab, but couldn't get it to use the newer python version

Also tried the manual invocation instead of the jupyter shortcut and was still unsuccessful

![image](https://user-images.githubusercontent.com/9356891/197412776-9a00729d-e8be-4d22-badf-0481b043b35f.png)

Unfortunate but understandable that it doesn't work in colab, just wanted to share my findings
