### ISSUE TITLE
Scalene: Program did not run for long enough to profile.

### ISSUE THREAD

**Issue by kdebrab** [plasma-umass/scalene#337]
When trying scalene inside a docker image, I don't get a report but only the message:
```
Scalene: Program did not run for long enough to profile.
```
I ran the script using `scalene [...]` (with the default scalene options). The script took ca. 8 minutes to finish and there were no errors raised.

When running the same script on my Windows laptop, I did get a scalene report (including CPU profiling only).

What are possible root causes for this message?

Maybe could it be that scalene is not working inside a docker image in general? Or just certain docker images (base image is `python:3.9-slim-buster` in my case)?

Any other suggestions?

**Comment by sternj** [comment]
I am unable to replicate this issue on an instance of `python:3.9-slim-buster` on my computer. Are you using signals at all in your program? Scalene uses several specific signals, and if you override the handlers it can lead to Scalene not getting any signals.

**Comment by sternj** [comment]
I think I narrowed down the issue-- if you can, could you please see if it works on the branch `add_warnings_to_signals`? It likely has nothing to do with the docker container, I suspect there was something weird happening with timer signals.

**Comment by kdebrab** [comment]
FYI, this issue remained present for me, but was finally solved when upgrading from v1.5.13 to v1.5.15. Thanks!

**Comment by kdebrab** [comment]
Unfortunately, I noticed that the issue reappears with v1.5.17 (and v1.5.18). So, only v1.5.14, v1.5.15 and v1.5.16 are not showing this message and thus working fine for me.

Similar as before, the message reappears only in the docker container (meanwhile `python:3.11-slim-bullseye`), and not when running the same command on my Windows laptop.

I don't use signals in my code (but maybe dependencies do).

**Comment by kdebrab** [comment]
Though the message is not shown for v1.5.16, the resulting report does not contain any profile information. The json output looks as follows:
```
{
    "alloc_samples": 75,
    "elapsed_time_sec": 6.468282222747803,
    "files": {},
    "gpu": false,
    "growth_rate": 0.0,
    "max_footprint_fname": null,
    "max_footprint_lineno": null,
    "max_footprint_mb": 0,
    "memory": true,
    "program": "/opt/venv/lib/python3.11/site-packages/eee/sq/plantacceptance/main.py",
    "samples": [
        [
            256256357,
            0.010275901030292486
        ],
        [
            256261724,
            0.009794318991785829
        ],
        [...many more samples...]
        [
            5080715954,
            0.0038291466874797384
    ]
}
```
Any idea what could be the cause of this?

**Comment by emeryberger** [comment]
The JSON file helped a lot. The issue is that Scalene deliberately filters out all installed libraries (under the directories like `site-packages`), under the assumption that you do not want to profile libraries.
