### ISSUE TITLE
multiprocessing support?

### ISSUE THREAD

**Issue by fjsj** [plasma-umass/scalene#34]
Hi, this tool looks amazing! A question: is there any multiprocessing support?
memory_profiler for example can track forked child processes memory: https://github.com/pythonprofilers/memory_profiler#tracking-forked-child-processes

**Comment by emeryberger** [comment]
Not yet. If you have a program you’d like to profile that you can share with me, it would help!

**Comment by emeryberger** [comment]
Note: this currently appears to not be working because the various lock methods need to be intercepted (as Scalene currently does for `threading.Lock`).

**Comment by emeryberger** [comment]
Scalene now supports `multiprocessing`.

**Comment by rojamit** [comment]
> Scalene now supports `multiprocessing`.
how to use multiprocessing support, i only getting report for master process..

**Comment by emeryberger** [comment]
Can you provide an example?
