### ISSUE TITLE
--web works exactly one time because port is blocked

### ISSUE THREAD

**Issue by ronny-rentner** [plasma-umass/scalene#342]
First of all, thanks a lot for your effort. Scalene looks really great and the reports are really useful.

**Describe the bug**
I run something like `scalene  --web --cpu-only --use-virtual-time ./loopback.py`

It works well. My program runs in an infinite loop until I stop it with CTRL-C which is catched in my program.

An HTML page with the report pops up in my web browser. That's great.

Now, the scalene process that's running the web server hangs around in the background forever and never quits until I manually kill the pid.

Thus, all subsequent runs to the same command fail (unless I manually kill the process):
```
  File "...venv/lib/python3.9/site-packages/scalene/scalene_profiler.py", line 1458, in profile_code
    with socketserver.TCPServer(("", PORT), Handler) as httpd:
  File "/usr/lib/python3.9/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.9/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
```

What's the intended way how this should work? When would scalene end the local webserver? Is scalene supposed to quit itself? Why does it need a webserver at all? Could it not render static HTML and show it in the browser without a webserver? 

**Expected behaviour**
I should be able to run `scalene  --web --cpu-only --use-virtual-time ./loopback.py` multiple times (one after another, not in parallel) without errors on the 2nd attempt because the port is blocked and without having to manually look up and kill the scalene process.

**Comment by emeryberger** [comment]
Thanks for your report. The current repo version (which adds Jupyter support for the new GUI) now kills the server after 5 seconds (magic number for now). Hopefully this will solve your current problem. Please verify by installing from the repo (`python3 -m pip install git+https://github.com/plasma-umass/scalene`).

The server is currently there to satisfy `fetch` requests to obtain the JSON file that the profiler produces.

**Comment by emeryberger** [comment]
Closing; please re-open if this doesn't solve your problem (now in the current release, 1.5.2).
