### ISSUE TITLE
TypeError in output_profile_line

### ISSUE THREAD

**Issue by matt-erhart** [plasma-umass/scalene#344]
**Describe the bug**
```bash
Scalene: An exception of type TypeError occurred. Arguments:
("output_profile_line() missing 1 required keyword-only argument: 'fname_print'",)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/scalene/scalene_profiler.py", line 1614, in run_profiler
    exit_status = profiler.profile_code(
  File "/opt/conda/lib/python3.9/site-packages/scalene/scalene_profiler.py", line 1439, in profile_code
    if not Scalene.output_profile():
  File "/opt/conda/lib/python3.9/site-packages/scalene/scalene_profiler.py", line 686, in output_profile
    did_output: bool = output.output_profiles(
  File "/opt/conda/lib/python3.9/site-packages/scalene/scalene_output.py", line 564, in output_profiles
    did_print = self.output_profile_line(
  File "/opt/conda/lib/python3.9/site-packages/scalene/scalene_output.py", line 109, in output_profile_line
    obj = json.output_profile_line(
TypeError: output_profile_line() missing 1 required keyword-only argument: 'fname_print'
```

**To Reproduce**
scalene myfile.py

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Docker on Windows
 - Version latest

**Additional context**
Docker file:
```docker
FROM continuumio/miniconda3
RUN apt-get -y update
RUN apt-get install -y python3-all-dev
RUN conda install -q -y pandas pyarrow python-snappy fastparquet snappy
```

**Comment by emeryberger** [comment]
Thanks for the report. Can you share the exact version of Python? (`python3 --version`)

**Comment by emeryberger** [comment]
Thanks for the report; can you verify that this works for you? (install from the repo - `python3 -m pip install git+https://github.com/plasma-umass/scalene`)

**Comment by cauliyang** [comment]
Get the same error: 

![image](https://user-images.githubusercontent.com/38903141/152469361-ccb26c55-8eac-4214-9c56-54b1136accb8.png)

Platform: Linux x86_64 
Environment: Conda 
Version: scalene-1.5.2  
Running CMD: scalene myfile.py

Updated:

Firstly, `pip uninstall scalene`
then use `python3 -m pip install git+https://github.com/plasma-umass/scalene` to install again.  The error I meet is fixed. 

Thanks for your effort ❤️

**Comment by emeryberger** [comment]
Just to clarify - this is now working for you, correct?

**Comment by cauliyang** [comment]
it works for me
