### ISSUE TITLE
nvidia-ml-py version 375.53.1

### ISSUE THREAD

**Issue by iakremnev** [plasma-umass/scalene#351]
**Describe the bug**
Commit https://github.com/plasma-umass/scalene/commit/48f9ce9efee2c4916e72eb245f92058ac61fae80 introduced unwanted behavior of installing an old `nvidia-ml-py` version 375.53.1, which is incompatible with Python 3.
Details on this problem with `nvidia-ml-py` packaging: https://forums.developer.nvidia.com/t/mistake-with-nvidia-ml-py-on-pypi/112942

**To Reproduce**
```bash
# make fresh venv for Python 3
pip install scalene==1.5.4
scalene --help  # fails on print statement in pynvml.py:1831.
```

**Expected behavior**
Install `nvidia-ml-py~=11`

**Comment by iakremnev** [comment]
It seems like 375.53.1 is the only odd version of `nvidia-ml-py` on PyPI, so one can explicitly exclude it from the requirements.

```bash
% pip install nvidia-ml-py==
ERROR: Could not find a version that satisfies the requirement nvidia-ml-py== (from versions: 1.0, 2.285.1, 3.295.0, 4.304.2, 4.304.3, 4.304.4, 6.340.0, 7.346.0, 7.352.0, 10.418.84, 11.450.51, 11.450.129, 11.460.79, 11.470.66, 11.495.46, 11.515.0, 375.53)
```

**Comment by emeryberger** [comment]
Closed with https://github.com/plasma-umass/scalene/pull/352.
