### ISSUE TITLE
Scalene error: received signal SIGSEGV [Python 3.7.5 + Ubuntu 18.04.6 LTS]

### ISSUE THREAD

**Issue by mleang** [plasma-umass/scalene#355]
**Describe the bug**
Under `Ubuntu 18.04.6 LTS`,  i'm using a virtual environment in which i installed `python 3.7.5 ` and i get this error 
`Scalene error: received signal SIGSEGV` while running Scalene.

**To Reproduce**
1. Set up a virtual environment with `python3 -m venv {name_of_your_virtual_env}`
2. Activate the virtual env : `source {name_of_your_virtual_env}/bin/activate`
3. Upgrade pip, setuptools, wheel: `pip install --upgrade pip setuptools wheel`
4. Install Scalene : `python3 -m pip install git+https://github.com/plasma-umass/scalene`
5. Run Scalene with `test.py` to measure CPU and GPU activity: `python3 -m scalene --cli --json --outfile profile.json test.py`

`test.py` contains: 
```
x = 0
for i in range(10):
    for j in range(1000):
        for k in range(1000):
            x += 1
            
```

**Expected behavior**
I expect that there is no error message and that `profile.json` contains CPU/GPU activity. 

**Desktop (please complete the following information):**
 - OS:  `Ubuntu 18.04.6 LTS`
 - Scalene Version : `1.5.4` (got this with `pip freeze`: `scalene @ git+https://github.com/plasma-umass/scalene@f25fd8e7cdbab591cd88be5320f2aa86bd92e16d`)
 - Python Version : `Python 3.7.5`

**Comment by mleang** [comment]
One solution is to install `Python 3.8` : this [tutorial](https://hackersandslackers.com/multiple-versions-python-ubuntu/) works for me.
Scalene works well, it does not complain and the `profile.json` looks fine.

**Comment by emeryberger** [comment]
Thanks for the details! We are deprecating 3.7; closing since the problem doesn't exist in 3.8.
