### ISSUE TITLE
"cannot import name 'get_line_atomic'(..)" on Ubuntu 20.04 (docker)

### ISSUE THREAD

**Issue by AdrK** [plasma-umass/scalene#359]
When running Scalene, in below described docker container, the import error related to `get_line_atomic` appears. It seems that the `libscalene.so` library is properly build, installed and preloaded and yet this error appears. Please see the Dockerfile for reproduction. Despite the error, Scalene is still able to get some samples and print the json. I wonder what is the reason of the error and if this is something in my env.

```
FROM ubuntu:20.04

RUN apt -y update && apt -y install python3 python3-pip git python3-all-dev vim

# Installing gpustat because of bug: https://github.com/wookayin/gpustat/issues/46
RUN python3 -m pip install django gpustat

RUN git clone https://github.com/devmahmud/Django-Poll-App
WORKDIR /Django-Poll-App
RUN python3 manage.py makemigrations && python3 manage.py migrate

WORKDIR /
RUN git clone https://github.com/plasma-umass/scalene.git
WORKDIR /scalene
RUN git checkout v1.5.4
RUN python3 setup.py install

ENV SCALENE_ALLOCATION_SAMPLING_WINDOW=1549351
ENV LD_PRELOAD=/usr/local/lib/python3.8/dist-packages/scalene-1.5.4-py3.8-linux-x86_64.egg/scalene/libscalene.so
ENTRYPOINT ["scalene", "--json", "--profile-interval", "1", "/Django-Poll-App/manage.py", "runserver"]
```

![image](https://user-images.githubusercontent.com/15175440/155196121-f1cdfa22-63b6-4ec4-8645-52dff75dd61f.png)

Ubuntu 20.04
Scalene v1.5.4

**Comment by sternj** [comment]
Thank you for the Dockerfile! I'm going to replicate.

**Comment by sternj** [comment]
Ok so as a stopgap, adding the directive
```
RUN pip3 install git+https://github.com/plasma-umass/scalene.git
``` 
instead of all the Scalene stuff should fix it. Also, absolutely no need to set the `LD_PRELOAD` variable yourself. We do that in the script. 

As for why your current approach isn't working... I'm looking into it more. This doesn't make any sense.

**Comment by sternj** [comment]
Ok I figured out the issue. Essentially, because you're still inside the working directory `/scalene`, since there exists a `/scalene/scalene/__init__.py`, the Python interpreter (which Scalene invokes) is parsing that as the true "scalene". The solution if you want to do it the way you were previously doing it is just add a `WORKDIR /` so that it doesn't see a Python module named `scalene`. You might run into a PyNVML issue but we're fixing that on the next release. 

Closing this issue because either fix that I set out will work, please reopen if you run into anything else!

**Comment by AdrK** [comment]
Thanks for the support, works like a charm ;)
I am running Scalene in this way, because I am working on this:
https://github.com/pyroscope-io/pyroscope/issues/316
So I just wanted to run the Scalene through pudb to learn how it works. I have added the LD_PRELOAD because I didn't want the Scalene to spawn itself in a separate subprocess, as it apparently does in order to do the preloading itself.

**Comment by guywilsonjr** [comment]
@AdrK Any luck with https://github.com/grafana/pyroscope/issues/316?
