### ISSUE TITLE
Out of memory error when viewing .json file in the web-view.

### ISSUE THREAD

**Issue by JCrane512** [plasma-umass/scalene#368]
**Describe the bug**
I have a ~200 mb .json file created from profiling my code. Yesterday I was able to load this into the scalene GUI and view it just fine. Today when I try and load the same file I am getting an out-of-memory issue on chrome. I am using the Chrome web browser to view the files on Windows. The laptop I am using has 16 GB of ram and never exceeded 60% usage. 

**To Reproduce**
1. Upload the 200 MB .json file 
2. Get an our of memory issue on chrome

**Expected behavior**
No memory error and the file to load normally. 

**Screenshots**
<img width="843" alt="OOMerror" src="https://user-images.githubusercontent.com/93589198/156771773-b5a1617f-cc4e-4f1a-bac3-7dae5f553422.PNG">

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 
 - Browser Chrome Version 98.0.4758.102 (Official Build) (64-bit)
 - scalene 1.5.4
 - Python 3.8.8

**Comment by emeryberger** [comment]
Can you share the profile file somewhere? (zip should do wonders in terms of compression) Thanks!

**Comment by JCrane512** [comment]
Update on this issue. 

I am able to load the above file in GUI (http://plasma-umass.org/scalene-gui/) in firefox but not in chrome. 

When I load it in firefox the tab takes up 10 GB of RAM.

I then did some investigating and downloaded a copy of this commit: https://github.com/plasma-umass/scalene/commit/a007605f05efb167b1fe5dc975b8c7223c8519a9 

When I use this commit instead of the publicly available master version I found that the same file used 7.5 GB of ram. 

I have no baseline on what is acceptable here, but I think one of the more recent commits changed the GUI significantly.

**Comment by emeryberger** [comment]
I'm honestly surprised that makes as much of a difference as it does! The core issue is that I added the ability to examine the individual points on the memory timelines. (I am assuming you are running this with WSL2.) The current version in the repo now changes how memory timelines are stored (it compresses them - quite drastically - so the resulting profile files will be smaller and should also be easier on the GUI). I hate to make you do this, but you probably want to run your code on that version - please try `python3 -m pip install git+https://github.com/plasma-umass/scalene`. Thanks!

**Comment by JCrane512** [comment]
Thanks very much for the reply, I'll re-profile with the latest version of scalene and let you know how it goes.

**Comment by JCrane512** [comment]
Oh and not sure if it makes any difference but I am profiling scalene on a linux machine running 

NAME="Rocky Linux"
VERSION="8.5 (Green Obsidian)"

But I am opening the profile.json files on a windows machine (as it has enough RAM to open it)

**Comment by emeryberger** [comment]
I had never previously heard of Rocky Linux, but it seems like that should not be an issue. Thanks!

**Comment by JCrane512** [comment]
I can confirm that all new profiles created with the latest version of scalene do not have this problem. 

The size of the files has now dropped to less than 1MB. 

I believe this issue can be closed. 

Also, I would like to thank you, Scalene is by far the best python profiler I have ever used. I hope that you continue to develop it!
