### ISSUE TITLE
AttributeError: module 'signal' has no attribute 'raise_signal'

### ISSUE THREAD

**Issue by arvind-k-singh** [plasma-umass/scalene#372]
**Describe the bug**
I get the AttributeError: module "signal' has no attribute 'raise_signal" error when I try to use scalene for my code.
I did try to find the solution but could not  fix it.

**Expected behavior**
It should run the profile without any error

[**Screenshots**]
![Scalene_Error](https://user-images.githubusercontent.com/95620797/157028937-d14e0fe2-ddc7-44f8-9c9b-e66e70a1b52e.PNG)

**Desktop (please complete the following information):**
 - OS: Linux 18.04 with Nvidia GPU
 - Browser Microsoft Edge
 - Version 1.5.4
 - Python 3.7.2

**Comment by sternj** [comment]
We do not support any Python versions below 3.8. Please upgrade and create a new issue if you have further problems.
