### ISSUE TITLE
scalene-gui files missing from 1.5.7 manylinux wheels

### ISSUE THREAD

**Issue by Chroxvi** [plasma-umass/scalene#390]
**Describe the bug**
The `scalene-gui` folder is not included in the [1.5.7 manylinux wheels on PyPi](https://pypi.org/project/scalene/1.5.7/#files). Thus, the web-server is unable to start when running `scalene`.

**To Reproduce**
Steps to reproduce the behavior (on linux):
1. pip install scalene=1.5.7
2. scalene <my_script.py>

**Expected behavior**
I expect the `scalene-gui` folder to be included in the 1.5.7 manylinux wheels such that the web-server is able to start when running `scalene`.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 LTS
 - Browser: Chromium
 - Version 100

**Additional context**
The following (somewhat misleading) error is shown when running `scalene <my_script.py>` using the 1.5.7 manylinux wheels:

```bash
Scalene: unable to run the Scalene GUI on port 8088.
Possible solutions:
(1) Use a different port (with --port)
(2) Use the text version (with --cli)
(3) Upload a generated profile.json file to the web GUI: https://plasma-umass.org/scalene-gui/.
```

This error message is emitted from:
https://github.com/plasma-umass/scalene/blob/0a57470404494ce902d2698df3e4b9b052390b1a/scalene/scalene_profiler.py#L1644-L1653

due to an `OSError` occurring in the file copy of the `scalene-gui` files in:
https://github.com/plasma-umass/scalene/blob/0a57470404494ce902d2698df3e4b9b052390b1a/scalene/scalene_profiler.py#L1614-L1619

since the files are missing from the installation.

Thus, the fix seems to be to include the `scalene-gui` files in the 1.5.7 manylinux files. Also, the above `shutil.copytree` exception should probably be handled separately from any `TCPServer` port error.

**Comment by jaltmayerpizzorno** [comment]
I can reproduce the problem, and am looking into why it's happening.

**Comment by jaltmayerpizzorno** [comment]
I believe the files were being omitted because of this GitHub problem: https://github.com/actions/checkout/issues/766.
I added a workaround.  @Chroxvi, could you please test with `pip install -i https://test.pypi.org/simple/ scalene==1.5.7.dev202204281304` and re-open the issue if it doesn't solve it?

**Comment by Chroxvi** [comment]
@jaltmayerpizzorno, I can confirm that the package installed with `pip install -i https://test.pypi.org/simple/ scalene==1.5.7.dev202204281304` works as expected. Thanks!

**Comment by jaltmayerpizzorno** [comment]
Thank you for reporting it!
