### ISSUE TITLE
Running scalene when running python in modular mode

### ISSUE THREAD

**Issue by mkhoshle** [plasma-umass/scalene#391]
Hi,

I run my python code in the following way `python -m HumanObj.train --configs_yml='configs/v1.yml'`.  If I do not use the `-m` option python will not find my code. If I want to use `scalene` to run my code I get the following error:
`Scalene: could not find input file -m`. 
What do I need to do to get my code running and profile it?

```
python -m scalene HumanObj.train --configs_yml='configs/v1.yml'
Scalene: could not find input file HumanObj.train
```
However, this `python -m HumanObj.train --configs_yml='configs/v1.yml'` works totally fine.

Thanks,

**Comment by fanninpm** [comment]
See also #244

**Comment by mkhoshle** [comment]
@fanninpm So this is not an existing feature right now? Is there a workaround to get my package running?

**Comment by fanninpm** [comment]
> Is there a workaround to get my package running?

Try writing a wrapper script using the [`runpy` library](https://docs.python.org/3/library/runpy.html#runpy.run_module). If that doesn't work, perhaps @emeryberger could help. (By the way, [that issue currently has the most thumbs-up reactions of any issue in this repository](https://github.com/plasma-umass/scalene/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).)
