### ISSUE TITLE
When runnung scalene in a GPU machine although the python code does not use GPU it reports GPU time.

### ISSUE THREAD

**Issue by Nuwan1654** [plasma-umass/scalene#396]
**Describe the bug**
I am using scalene to profile CPU time in a simple OpenCV function.  I ran it on both CPU machine and GPU machine with 4 RTX 3090 GPUs. Although I didn't build my OpenCV with CUDA support this should not use any GPU. but when looking at the HTML files generated by scalene it shows GPU time. and it is also colored in red which means it uses most of the time in GPU. I don't understand that behavior. Any help would be greatly appreciated

The code being profiled `test.py`
```
import cv2

cap = cv2.VideoCapture("/home/nsight/yolox-infer/layerx.mp4")

if (cap.isOpened()== False): 
  print("Error opening video stream or file")

while(cap.isOpened()):
  ret, frame = cap.read()
  if ret == True:
    k=1
 
  else: 
    break

cap.release()
```

**To Reproduce**
run : `scalene --html --outfile out_test.html test.py`

**Expected behavior**
 Since I didn't build my OpenCV with CUDA support this should not use any GPU. both of the following screenshots should be the same.

**Screenshots**
[here](https://drive.google.com/file/d/1zjiSakPI6_3ZZBAFP2WFW2Yio9AQ-NGX/view?usp=sharing) is the HTML view of the same command used in the CPU machine. 

[here](https://drive.google.com/file/d/1LaWs1VwLeIFUmz-nqCtQSL60Ipr5TgjS/view?usp=sharing) is the HTML view of the same command used in the GPU machine. 

**Desktop**
 - OS: [Ubuntu 20.04]
 - Browser [firefox]

**Comment by emeryberger** [comment]
Please try the current repo version and see if it solves your problem. NOTE that you may need to run Scalene as root exactly once to get the desired behavior. `python3 -m pip install git+https://github.com/plasma-umass/scalene`. Thanks!

**Comment by emeryberger** [comment]
This should be addressed in the latest release, which enables per process GPU accounting.
