### ISSUE TITLE
Using scalene programatically fails with argument error

### ISSUE THREAD

**Issue by CatalinMustata** [plasma-umass/scalene#397]
**Describe the bug**
Trying to run scalene programmatically results in an error - this happens only when I use `from scalene import profile, scalene_profiler`.

```
usage: scalene.profile [-h] [--pid PID] (--on | --off)
scalene.profile: error: one of the arguments --on --off is required
Scalene: Program did not run for long enough to profile.
```

**To Reproduce**
- add `from scalene import profile, scalene_profiler`
- try to run program (`scalene --on test.py` or `python -m scalene --on test.py` yield the same result)

**Expected behavior**
For it to run, like it does without the import in my code.

**Desktop (please complete the following information):**
 - MacOS Monterey / Python 3.9.1
 - Scalene 1.5.8

**Comment by emeryberger** [comment]
I can reproduce this but it works if you do not import `profile` (which you should not import!).

This example (`programmatic-test.py`) produces the expected results.

```Python
from scalene import scalene_profiler

x = 0
for i in range(10000):
    for j in range(1000):
        x += 1

# Turn profiling on
scalene_profiler.start()

x = 0
for i in range(10000):
    for j in range(1000):
        x += 1
        
# Turn profiling off
scalene_profiler.stop()
```

```shell
% python3 -m scalene --cli  --off ./programmatic-test.py
```

**Comment by NivekT** [comment]
> I can reproduce this but it works if you do not import `profile` (which you should not import!).

Hi, I just found this issue because I ran into the same problem. I think some IDEs are prompting users to import `profile` with a red underline when `@profile` is used, so as a new user, I did. 

Perhaps nothing needs to be done about this, but if it is easy to tell users (or the IDEs) not to somewhere, it might be helpful.
