### ISSUE TITLE
HowTo start via c code

### ISSUE THREAD

**Issue by jbleyel** [plasma-umass/scalene#410]
Can you please help me?

I'm starting my python module inside of a c++ binary like this.

```
	FILE *fp = fopen("/xx/program.py", "r");
	if (!fp)
		return -ENOENT;
	int ret = PyRun_SimpleFile(fp, file);
	fclose(fp);
	return ret;

```

Is it possible to profile the python module using scalene?
I can't run program.py from the command line because the main program is the c++ binary.

**Comment by emeryberger** [comment]
This is unfortunately not possible right now.

**Comment by jbleyel** [comment]
Hello @emeryberger , are there any news here or other ways to use scalene to profile python code which is startet like this.
