### ISSUE TITLE
LD_PRELOAD variable should also work with other libraries

### ISSUE THREAD

**Issue by hpham** [plasma-umass/scalene#418]
**Describe the bug**
I wonder that I scalene doesn't monitor the memory consumption of our application in WSL2. I use this command to start:
`scalene --cli --outfile result.txt --reduced-profile  app.py`
I also try to monitor this app https://github.com/plasma-umass/scalene/blob/master/test/testme.py and here it works fine.

Our python version also uses the LD_PRELOAD variable to preload an external library. I have read that Scalene also set this variable. Maybe our python version overrides  LD_PRELOAD   variable and causes the problem that the memory consumption doesn't get monitored ?
Our custom python version uses:
`export LD_PRELOAD=${SQLITE_HOME}/lib/libxxx_sqlite3_crypto.so:${SQLITE_HOME}/lib/libxxx_sqlite3.so`

**To Reproduce**
Monitor a application that also use LD_PRELOAD to load external library. 

**Expected behavior**
LD_PRELOAD also work with other library.

**Screenshots**
https://files.slack.com/files-pri/T02LECNDG6S-F03NLD6LK6K/image.png

**Desktop (please complete the following information):**
 - OS: Windows WSL2

**Comment by emeryberger** [comment]
Thanks for the report! This should now work - you can install from the repo as follows: `python3 -m pip install git+https://github.com/plasma-umass/scalene`. The fix will be included in the next release. (I just tested it and verified that it preserves existing `LD_PRELOAD` libraries.)
