### ISSUE TITLE
Possible incompatibility with zipapp

### ISSUE THREAD

**Issue by Commaster** [plasma-umass/scalene#420]
**Describe the bug**
Attempting to profile an app built with zipapp breaks scalene initialization.

**To Reproduce**
1. Create a multifile project
2. "compile" it using `python3 -m zipapp -p '/usr/bin/env python3' -m 'mainclass:mainfunc' -c mydir -o myapp.py`
3. Attempt to profile

**Expected behavior**
A working profiling

**Output**
```
scalene --html --outfile prof.html --cli -- ../myapp.py --myarg1 -myarg2
Scalene failed to initialize.
Traceback (most recent call last):
  File ".../lib/python3.8/site-packages/scalene/scalene_profiler.py", line 1779, in run_profiler
    code = compile(
ValueError: source code string cannot contain null bytes
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.4
 - Python 3.8.10
 - Version 1.5.9 (pypi)

**Comment by emeryberger** [comment]
I tried to do this with some existing profilers and this seems to be unsupported everywhere. There's an easy workaround: unzip the `.pyz` file into a directory and profile that code there.

**Comment by Commaster** [comment]
https://github.com/pythonspeed/filprofiler (a memory-only profiler) works properly with a zipapp, but maybe related to the call hijacking approach.
Alrighty, thank you!
