### ISSUE TITLE
Error getting real path: 2; Scalene error: received signal SIGABRT

### ISSUE THREAD

**Issue by ezyang** [plasma-umass/scalene#425]
**Describe the bug**
A program using importlib to import a module that imports request from urllib fails, when run with scalene.

**To Reproduce**
1. Create two folders: `benchmark/torchbenchmark` and `foo`
2. In `benchmark/torchbenchmark/__init__.py` put

```
from urllib import request
```

3. In `foo/c.py` put

```
import importlib
import os

os.chdir("../benchmark")
sys.path.append(os.getcwd())
module = importlib.import_module(f"torchbenchmark")
```

**Expected behavior**
Program passes with scalene

Actual behavor:
```
(/scratch/ezyang/pytorch-scratch2-env) ezyang@devfair040:/scratch/ezyang/torchdynamo$ python c.py
(/scratch/ezyang/pytorch-scratch2-env) ezyang@devfair040:/scratch/ezyang/torchdynamo$ scalene c.py
Error getting real path: 2
Scalene error: received signal SIGABRT
NOTE: The GPU is currently running in a mode that can reduce Scalene's accuracy when reporting GPU utilization.
Run once as root (i.e., prefixed with `sudo`) to enable per-process GPU accounting.
```

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: na
 - Version: na

**Comment by emeryberger** [comment]
This should be fixed in the repository version: `python3 -m pip install git+https://github.com/plasma-umass/scalene`. (Please re-open if not!)

**Comment by ezyang** [comment]
Looks like it is working now, thanks!
