### ISSUE TITLE
Notebook profiling results don't render in VS Code Jupyter

### ISSUE THREAD

**Issue by ma-sadeghi** [plasma-umass/scalene#440]
**Describe the bug**
Notebook profiling results don't render in VS Code Jupyter

**To Reproduce**
1. Open VS Code
2. Create a notebook and open it inside VS Code using the Jupyter extension
3. Profile some random code using `%scrun`
4. The profiling seems to have completed, but the results are shown as an empty box

**Expected behavior**
To see the actual profiling results

**Screenshots**
![image](https://user-images.githubusercontent.com/14086031/192111709-b461324b-2b1c-4756-9069-d9f3adca045d.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: NA
 - Version: NA

**Additional context**
NA

**Comment by emeryberger** [comment]
This now (almost) works on VS Code / Mac, and in theory should work on Ubuntu as well. Please try again but install using this command in Jupyter to install from the current repository version:

```
%pip install git+https://github.com/plasma-umass/scalene
```

Then try this (instead of using `%scrun`, use `%%scalene`).

```
%%scalene
np.random.rand(200, 200, 2000000).mean()
```

**Comment by ma-sadeghi** [comment]
Thank you for your reply. I just tried, but I still see a white box as the output.

**Comment by ma-sadeghi** [comment]
@emeryberger Thanks, it's fixed now, I don't know why it didn't work before, but I tried it on a fresh conda env and it's working! Thanks!
