### ISSUE TITLE
Make the Jupyter notebook output full width

### ISSUE THREAD

**Issue by ma-sadeghi** [plasma-umass/scalene#441]
**Is your feature request related to a problem? Please describe.**
Currently, the output in Jupyter notebooks is not full width and has a horizontal scroll bar.

**Describe the solution you'd like**
To make the output in Jupyter notebooks full width.

**Describe alternatives you've considered**
NA

**Additional context**
![image](https://user-images.githubusercontent.com/14086031/193911151-522db456-b2e1-4b7d-afbf-6643d3453ca6.png)

**Comment by ma-sadeghi** [comment]
Edit: this happens in VS Code (haven't tried in browser, so it might be fine there)

**Comment by emeryberger** [comment]
I just pushed a (minor) change that should allow Jupyter to show full-width output automatically. I don't yet see how to disable the scrollbar. Please give it a whirl: `%pip install git+https://github.com/plasma-umass/scalene`.
