### ISSUE TITLE
With --profile-all Scalene profiles itself, not the code

### ISSUE THREAD

**Issue by EsbernTK** [plasma-umass/scalene#457]
**Describe the bug**
Im not sure if this is a a feature request or a bug report, there is no error, but it feels more like a bug than a feature. When running my script with --profile-all option, scalene only profiles itself. Im running with this option as i want to profile my entire call chain, not just the script im running.
My project structure looks like this
```
project
|
└───src
│   │   my_func.py
│   
└───tests
    │   my_test.py (imports functions to be tested from ../src/my_func.py)
```

I have a /src folder where all my functionality scripts are, and then at the same level a /tests folder where all tests scripts are.
So a script in /test which imports a function i want to profile from /src.
However when I run scalene on it without --profile-all,  scalene just tells me that all my time is spent in the imported function, which I of course already know, and it doesn't tell me which line it is in.
However when I then run with --profile-all to get the actual numbers per line in the function, then it only gives me back a profile of scalene itself.

The code in my_test.py looks like this

```
from scr.my_func import foo

def profile_foo(num_runs=100):
    for num_runs in range(num_runs):
        foo()

if __name__ == '__main__':
    profile_foo()
```

**To Reproduce**
1. make project structure like shown above
2. import function from my_func.py into my_test.py
3. make a test function which calls the functions from my_func.py.
4. run scalene on my_test.py

**Expected behavior**
I expect Scalene to point me into the call chain, to the specific lines of code which take up a lot of time, no matter where they are. Except of course if they are within scalene itself... this is not useful info. 
I also do not want to profile my_func.py directly, since i want to keep it entirely about functionality and not also testing. And i do not want to put the profile decorator in my code either, since that kind of defeats the purpose of the profiler, if i have to find the functions that take up time.

**Screenshots**
<img width="1321" alt="scalene_profile_all" src="https://user-images.githubusercontent.com/10596719/197227802-61316af9-33e7-44e0-aba0-f82abc35bf38.png">

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python 3.10
 - Scalene v1.5.13

**Comment by emeryberger** [comment]
Hi - thanks for the report! There is logic in Scalene to prevent it from profiling itself, but it failed to take into account Windows backslash directory separators. This is now fixed. Please try to install from the repo: `python3 -m pip install git+https://github.com/plasma-umass/scalene` and let us know how it went (and re-open if it didn't solve your problem)!
