### ISSUE TITLE
Scalene: Program did not run for long enough to profile. MDVWhole package

### ISSUE THREAD

**Issue by BartBruininks** [plasma-umass/scalene#458]
**Describe the bug**
$ scalene mdvwhole.py -f em.gro -x em.gro -o whole.gro
-> Scalene: Program did not run for long enough to profile.

This is a rather long program which takes a point cloud in a periodic space and represents it as whole as possible. There is quite some IO, matrix generation, segmentation, graph theory etc involved. I'm trying it on a dataset for which the whole process takes half a minute. I would say more than enough time to profile.

**To Reproduce**
mkvirtualenv mdvwhole
pip install mdvwhole
# Obtain a GRO file (fixed file format)
vi em.gro
====== from here ====
A simple GRO file
19
    1POPC   NC3    1  31.936   4.196  22.457
    1POPC   PO4    2  31.541   4.233  22.666
    1POPC   GL1    3  31.638   4.615  22.469
    1POPC   GL2    4  31.752   4.606  22.206
    1POPC   C1A    5  31.496   5.025  22.366
    1POPC   D2A    6  31.347   5.397  22.514
    1POPC   C3A    7  31.463   5.800  22.398
    1POPC   C4A    8  31.632   6.206  22.491
    1POPC   C1B    9  31.862   4.990  22.025
    1POPC   C2B   10  31.735   5.434  22.093
    1POPC   C3B   11  31.756   5.863  21.985
    1POPC   C4B   12  31.444   6.198  21.995
    1POPC   NC3   13  31.392   4.260  22.146
    1POPC   PO4   14  30.962   4.189  21.912
    1POPC   GL1   15  30.851   4.579  22.077
    1POPC   GL2   16  31.151   4.705  22.168
    1POPC   C1A   17  30.758   5.001  21.936
    1POPC   D2A   18  30.553   5.404  21.993
    1POPC   C3A   19  30.736   5.822  21.982
  62.62701  62.62701  44.28398   0.00000   0.00000   0.00000   0.00000  31.31350  31.31350
===== to here ======

scalene whole.py -f em.gro -x em.gro -o whole.gro

**Expected behavior**
Scalene creating a report.

**Screenshots**
the error says it all

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 20
 - Browser [e.g. chrome, safari] Firefox

**Additional context**
Very hard to say as there is no clear error.

**Comment by emeryberger** [comment]
It probably is spawning a process whose creation Scalene is not intercepting. Please see if you can provide a minimal working example, we can try to reproduce the issue so we can fix it - thanks.

**Comment by kdebrab** [comment]
This looks very similar (the same?) as reported in #337, which seems to be solved (for me) since v1.5.14 or v1.5.15.

**Comment by sumit1000** [comment]
I am testing the small script test2.py. And also showing same error: 

"Scalene: Program did not run for long enough to profile."

Note: test2.py in attachment.
[test2.py.zip](https://github.com/plasma-umass/scalene/files/10335794/test2.py.zip)

**Comment by emeryberger** [comment]
Feature, not a bug. Quoting from my response to the comment.

> This is expected behavior. This script takes 3.0333000000000443e-05 seconds. This is far too little time for Scalene to profile. If a program takes less than 1/100th of a second, it's really (a) not appropriate for profiling and (b) not going to result in any samples taken by Scalene.

**Comment by emeryberger** [comment]
@BartBruininks would love an update with a new version of Scalene. Thanks.

**Comment by BartBruininks** [comment]
It seems to still have the same issue.

With respect to recreating it, I think the original post is reasonably clear. I could try to find the minimal example which still fails, but it could take me a long time as I have no idea, what is causing Scalene to fail.
