### ISSUE TITLE
Conda install doesn't work

### ISSUE THREAD

**Issue by ArneBachmannDLR** [plasma-umass/scalene#461]
**Describe the bug**
When running `conda install -c conda-forge scalene` (or `mamba install ...` for that matter), I get no results:

```
PackagesNotFoundError: The following packages are not available from current channels:

  - scalene

Current channels:

  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/dlr-sc/win-64
  - https://conda.anaconda.org/dlr-sc/noarch
```

**Expected behavior**
Scalene gets installed.

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2
 - mambaforge Python 3.10 in a conda environment

**Additional context**

**Comment by emeryberger** [comment]
Thanks for the report. Verified that `conda install` works for me on Mac and confirmed that it fails on Windows (11), not yet clear why.

**Comment by ArneBachmannDLR** [comment]
This is my `.condarc`: 

```yaml
show_channel_urls: true

channels:
  - dlr-sc
  - conda-forge
#  - defaults
report_errors: false
```

Nothing fancy, just avoiding the Anaconda default repo for business compliance.

**Comment by nikonyrh** [comment]
I am a fresh face here, but [Anaconda](https://anaconda.org/conda-forge/scalene) doesn't mention any Windows installers for scalane. It seems that they are available only for Linux & OS X for a few architectures.

**Comment by ArneBachmannDLR** [comment]
Ah that's true: https://anaconda.org/conda-forge/scalene
So no luck under Windows then

**Comment by emeryberger** [comment]
If anyone knows what I need to do to enable a Scalene build on Anaconda for Windows, please let me know!
