### ISSUE TITLE
Cannot run on byte compiled  code

### ISSUE THREAD

**Issue by jwmonaco** [plasma-umass/scalene#464]
When I try to run on byte compiled code I get:
```
Scalene failed to initialize.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/scalene/scalene_profiler.py", line 1845, in run_profiler
    code = compile(
ValueError: source code string cannot contain null bytes
```

Reproduce with [Dockerfile.txt](https://github.com/plasma-umass/scalene/files/9891152/Dockerfile.txt) as follows:

* Copy Dockerfile.txt to some directory and perform the following in that working directory
* Build a test environment `docker build  . -t scalene_tst`
* Sanity check that the test environment works  via `docker run -it --rm scalene_tst scalene /scalene/benchmarks/pystone.py`
* Try to profile byte compiled version of the same python
```
docker run -it --rm scalene_tst scalene /scalene/benchmarks/__pycache__/pystone.cpython-38.pyc
Scalene failed to initialize.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/scalene/scalene_profiler.py", line 1845, in run_profiler
    code = compile(
ValueError: source code string cannot contain null bytes
```
I'd expect the profiler to produce a result of some sort (hopefully useful!) rather than fail.  For example, py-spy can handle byte compiled code and generate useful results.

**Comment by sternj** [comment]
At the moment, this is not a feature set that we have any plans to implement. If you'd like to contribute it, please feel free!
