### ISSUE TITLE
Document necessary GCC version

### ISSUE THREAD

**Issue by mrozekma** [plasma-umass/scalene#470]
It's uncommon for a Python project to also require a C compiler, and Scalene seems to require a relatively modern one, but doesn't mention it at all in the installation instructions. Attempting to install it via `pip install scalene` errored out because my system GCC (which is very old for reasons) doesn't recognize `-std=c++14`. I tried setting `CC` to a newer GCC and it errored out because a different component needed `-std=c++17`. I tried the newest GCC on my system and it printed a page of compiler errors. Finally I installed the newest version I had a package lying around for and it worked fine.

I can confirm it builds with GCC 10.2.0 and not with 7.3.0.

**Comment by emeryberger** [comment]
I just successfully built Scalene with a variety of releases of GCC (including gcc-7.5.0 (released Nov 2019), gcc-8.4.0 (released March 2020), and gcc-9.4.0 (released June 2021)). It's hard to tell which minimum versions are actually required. We would welcome more information.

**Comment by emeryberger** [comment]
Please re-open if/when you have more info, thanks!
