### ISSUE TITLE
Command-line options after script aren't ignored

### ISSUE THREAD

**Issue by ArneBachmannDLR** [plasma-umass/scalene#475]
**Describe the bug**
Scalene should not interpret command-line arguments and options after the Python script.

**To Reproduce**
Run scalene via `scalene <options-and-arguments> <package/script>.py <script-options-and-arguments>`.

If I use `--help` for my script's options, I see scalene's help instead.

**Expected behavior**
Options and arguments after the script should not be interpreted by scalene.

**Comment by emeryberger** [comment]
Scalene uses `---` to end consumption of arguments, as in:
`python3 -m scalene foo.py --- --my-arguments-here`.

**Comment by ArneBachmannDLR** [comment]
Ah yes, that works. Is that a common convention? I might adapt it into my own tools!

**Comment by emeryberger** [comment]
I don't know how common it is but we've used it in past projects (https://github.com/plasma-umass/coz) and it works like a charm... :).
