### ISSUE TITLE
When running on a remote with no UI forwarding, HTML output is just CLI-formatted text written as HTML

### ISSUE THREAD

**Issue by munael** [plasma-umass/scalene#476]
**Describe the bug**
I'm running the actual script on a remote machine for which I have only shell access. Scalene outputs the report by default as formatted text to CLI (presumably because it detects no desktop env?). Specifying `--html --outfile s.html` outputs the same static formatted text as seen in the terminal as an HTML file with the appropriate layout to make it formatted, but no interactivity whatsoever.

**To Reproduce**
1. Connect to a remote machine through SSH. I'm doing that on VS Code.
2. Specify `--html --outfile foo.html`.
3. Profile something.
4. Open `foo.html` in VS Code. It's a static document.

Please include a minimum working example if at all possible.

**Expected behavior**
The examples given in videos suggest different types of interactivity in the report document. This should (maybe?) still be output even if no UI/web browser support is detected on the machine.

**Screenshots**
![image](https://user-images.githubusercontent.com/5769148/200142885-262d1b28-9afb-4483-ba73-729b1e0b3c10.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 (remote); Windows 10, 19044 (local)
 - Browser: N/A
 - Version: 1.5.13

If you have not yet tried with the repository version (`python3 -m pip install git+https://github.com/plasma-umass/scalene`), please try that before reporting.

- Yes. Same thing.

**Additional context**

**Comment by emeryberger** [comment]
This is actually expected behavior. You need to produce a JSON file as follows:

`python3 -m scalene --cli --json --outfile my_profile.json`

and then you can view it by uploading it here:

https://plasma-umass.org/scalene-gui/

**Comment by emeryberger** [comment]
Just added these instructions to the README.
