### ISSUE TITLE
`py-spy` supports `multiprocessing`

### ISSUE THREAD

**Issue by Kobzol** [plasma-umass/scalene#482]
Hi, thanks for this great profiler. I just wanted to point out that `py-spy` does support profiling multiple processes using the `--subprocesses` flag (https://github.com/benfred/py-spy#how-can-i-profile-subprocesses). This is not a new feature and it has been in `py-spy` for a long time, so it should probably be corrected in the comparison with other tools.

(I noticed this while watching https://www.youtube.com/watch?v=vVUnCXKuNOg - great talk btw :) ).

**Comment by emeryberger** [comment]
Thanks for the note. However, py-spy doesn't work with `multiprocessing` even with that flag. If there's some other option, I'd love to hear about it.

```
% sudo py-spy record --subprocesses python3 ./test/multiprocessing_test.py
[many lines omitted]
Joining <Process name='Process-2' pid=38832 parent=38829 started>
Joining <Process name='Process-3' pid=38833 parent=38829 started>
Joining <Process name='Process-4' pid=38834 parent=38829 stopped exitcode=0>
Total time: 0.2148268329910934
Error: No python processes found in process 38829 or any of its subprocesses
% py-spy --version                                                        
py-spy 0.3.14
```

This error does not occur with `python3` or with `scalene`. This is on Mac OS X.

**Comment by Kobzol** [comment]
I sometimes get this error too, but the results are gathered correctly even with the error. I created a flamegraph for multiple processes created with multiprocessing with py-spy and I could see the stack traces of all created processes correctly (on Linux).

**Comment by benfred** [comment]
Can you try with python < 3.11 ?  There is an issue with python 3.11 support on OSX https://github.com/benfred/py-spy/issues/536 - but should work well on other versions of python on OSX =(.  I've tried your test script just now on python v3.9.1 on OSX and py-spy worked correctly.

Its also worth noting that py-spy handles both lines and functions by the `--function` and `--nolineno` flags, instead of only by line number as indicated in the comparison table.

**Comment by emeryberger** [comment]
Hi @benfred - verified, it doesn't produce the same error message on Python 3.9 or 3.10. Thanks for the info! I also verified that Austin is now working for multiprocessing. I'll update the table (it has a few updates pending).

**Comment by dralley** [comment]
Looks like this still needs doing ^

**Comment by emeryberger** [comment]
Fixed with https://raw.githubusercontent.com/plasma-umass/scalene/master/docs/images/profiler-comparison.png

**Comment by Kobzol** [comment]
Thanks!

**Comment by emeryberger** [comment]
I just noticed that the line+function profiling is not there. py-spy profiles either lines or functions but not both; not sure what the best way to describe that is in the table without an explanatory asterisk...

**Comment by Kobzol** [comment]
Yeah, that's always an issue with a comparison table :) `py-spy` also supports profiling native code, which can be then visually compared in the flamegraph to see a baseline ratio of Python vs C code, so maybe even `Python vs C time` could be ticked.
