### ISSUE TITLE
Scalene cannot profie your program

### ISSUE THREAD

**Issue by mattangus** [plasma-umass/scalene#488]
**Is your feature request related to a problem? Please describe.**
Trying to profile my code, I get the error:
```
Error: Scalene cannot profile your program because it (or one of its packages) uses timers or signals that Scalene depends on. If you have encountered this warning, please file an issue using this URL: https://github.com/plasma-umass/scalene/issues/new/choose 
```

**Describe the solution you'd like**
print the package that uses the timer/signal, to give the user an easy option to remove. If that is not feasible, print out the timer/signal in conflict.

**Describe alternatives you've considered**
Add debugging print statments during imports to track down when the error occurs
step through program line by line until error occurs

**Additional context**
I believe this error is coming from using pytorch_lightning but I cannot confirm that.

**Comment by emeryberger** [comment]
The latest repository version now prints the first offending signal found; please let us know what you find (`python3 -m pip install git+https://github.com/plasma-umass/scalene`). Thanks!

**Comment by emeryberger** [comment]
Closing for lack of response.
