### ISSUE TITLE
Running a subprocess that invokes "python -c <cmd>" breaks said subprocess.

### ISSUE THREAD

**Issue by maarten-dp** [plasma-umass/scalene#489]
**Describe the bug**
Profiling when using the [pyGLFW](https://pypi.org/project/glfw/) library, results in a SyntaxError.

pyGLFW is using a subprocess call to determine the GLFW version and then `eval`s the output. In the subprocess, scalene raises an error, which is then returned to the main process as `Scalene: could not find input file -c`. When `eval`ing this string, the main process crashes.

[pyGLFW line in question](https://github.com/FlorianRhiem/pyGLFW/blob/master/glfw/library.py#L118)

**To Reproduce**
1. pip install glfw
2. make a python file with the content `import glfw`
3. run `scalene test_scalene.py`
4. View the traceback
```python
Error in program being profiled:
 invalid syntax (<string>, line 2)
Traceback (most recent call last):
  File ".../lib/python3.10/site-packages/scalene/scalene_profiler.py", line 1629, in profile_code
    exec(code, the_globals, the_locals)
  File "test_scalene.py", line 1, in <module>
    import glfw
  File ".../lib/python3.10/site-packages/glfw/__init__.py", line 40, in <module>
    from .library import glfw as _glfw
  File ".../lib/python3.10/site-packages/glfw/library.py", line 194, in <module>
    glfw = _load_library(['glfw', 'glfw3'], ['.so', '.dylib'],
  File ".../lib/python3.10/site-packages/glfw/library.py", line 59, in _load_library
    version = version_check_callback(filename)
  File ".../lib/python3.10/site-packages/glfw/library.py", line 118, in _glfw_get_version
    return eval(out)
  File "<string>", line 2
    Scalene: could not find input file -c
    ^^^^^^^
SyntaxError: invalid syntax
```

**Expected behavior**
I would expect code using GLFW to be profile-able.

**Desktop:**
 - OS: ArchLinux
 - Browser: Not applicable
 - Version: 
   * Python: 3.10
   * pyGLFW: tested on 2.5.3 and the latest 2.5.5
   * Scalene: 1.5.14 and the latest master branch

Unfortunately this is my first experience with scalene, but I'm loving what you're doing, so keep it up!

**Comment by maarten-dp** [comment]
After digging a bit deeper, I'm able to provide more context. I'll keep the original issue description for context, but below you'll find a more direct way of recreating the issue.

The problem is that scalene expects there to be a file, to profile, when forking. But invoking a subprocess with `python -c <cmd>` breaks the scalene bootcode in the child process, [as it's incorrectly adding "-c" as the file to profile](https://github.com/plasma-umass/scalene/blob/master/scalene/scalene_profiler.py#L1797)

To recreate, you can do the following
```python
import sys
import subprocess

print(subprocess.check_output([sys.executable, "-c", "print('hello!')"]))
```

What is expected:
`b'hello!\n'`

What is actually happening:
`b'23804\nScalene: could not find input file -c\n'`

I'll dig a bit further, and complete the issue as I go along.

**Comment by Cobular** [comment]
Any update on this? Just hit it myself

**Comment by talebzeghmi** [comment]
Any workarounds, I'm hitting myself too

**Comment by emeryberger** [comment]
If you install from the repository version, this should now work. (`python3 -m pip install git+https://github.com/plasma-umass/scalene`) Thanks for your reports!
