### ISSUE TITLE
The scalene module is not an IPython extension

### ISSUE THREAD

**Issue by deadsoul44** [plasma-umass/scalene#495]
**Describe the bug**
Using `%load_ext scalene` in Kaggle notebook gave the following error

`The scalene module is not an IPython extension.`

**To Reproduce**
1. Execute `%load_ext scalene` in a Kaggle notebook.

**Expected behavior**
Module should be loaded.

**Comment by emeryberger** [comment]
Scalene requires Python 3.8 or higher. The version of Python being used on Kaggle.com is 3.7 (as on Google Cloud notebooks).

<img width="792" alt="Screenshot 2022-11-27 at 10 25 06 AM" src="https://user-images.githubusercontent.com/1612723/204143253-4631d78f-1e97-4888-8cb6-d25e798b9212.png">

Version 3.7 was released in 2018, is many versions behind the current release, and is [nearing its end of life support](https://endoflife.date/python) (in June 2023). I am cautiously hopeful they will soon (finally) upgrade to version 3.8 or higher, which Scalene supports.
