### ISSUE TITLE
Time in ms

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [plasma-umass/scalene#500]
Hey guys,

what about having the time also `ms` instead of only `%`?

Cheers,

Fra

**Comment by emeryberger** [comment]
Good idea! Added that, along with improved logic that adjusts the units as the size gets larger (e.g., starts in `ms`, moves to `s`, `m`, etc.); same for memory. This is currently only in the repository version: `python3 -m pip install git+https://github.com/plasma-umass/scalene`.

**Comment by FrancescoSaverioZuppichini** [comment]
you guys rock! :rocket: thanks :)

**Comment by emeryberger** [comment]
For future reference, this new logic corresponds to this commit: https://github.com/plasma-umass/scalene/commit/2041b10cfaf63363fe4792c05470e06c9d3ebe81

**Comment by battaglia01** [comment]
Where is the time shown in ms? After installing in pip using the repo above, I still get this:

<img width="1132" alt="image" src="https://user-images.githubusercontent.com/1020594/221800569-7a313bde-5d26-4ca7-98ee-9131467a8f58.png">

**Comment by emeryberger** [comment]
It shows 5.748s out of 12.751s at the top, but you must mean somewhere else - in the per-line bars?

**Comment by battaglia01** [comment]
Ah, yeah, thought it was going to be there.
