### ISSUE TITLE
Scalene fails to profile internals of imported function.

### ISSUE THREAD

**Issue by IavTavares** [plasma-umass/scalene#504]
### Describe the bug
Scalene fails to profile internals of imported function, even evoking scalene programatically!

### To Reproduce
```
# my_script.py

import <class>
from <path.to.module>  import  <function>
from scalene import scalene_profiler

var_1 = class.method() # -> outputs a list of dict-like  objects

# Turn profiling on
scalene_profiler.start()
var_2 = function(var_1)
# Turn profiling off
scalene_profiler.stop()
```
Run `scalene my_script.py` from bash.

### Desktop 

OS: Ubuntu 22.04
Browser: chrome

![Screenshot from 2022-12-07 11-28-59](https://user-images.githubusercontent.com/91806073/206168652-14d7ba8a-039e-4c3f-a5a7-2bc80a9174fd.png)

The last line is the imported function...

**Comment by emeryberger** [comment]
By default, Scalene only profiles code that is in the current subdirectory or its children. You can profile "everything" with `--profile-all` and then selectively include files with `--profile-include` and `--profile-exclude`.

**Comment by IavTavares** [comment]
Thanks for the help. I decided to put the script at the root level of the directory. It worked. ;)
