### ISSUE TITLE
Scrapy profiling not possible?

### ISSUE THREAD

**Issue by fer-zav** [plasma-umass/scalene#519]
**Describe the bug**
Hi there! While runnning

<code>scalene --outfile profiled.html --html --memory --profile-all run.py</code>

on a scrapy projects runner, I got the following error:

<blockquote>
Error: Scalene cannot profile your program because it (or one of its packages)<br/ >
uses timers or a signal that Scalene depends on (Terminated).<br/ >
If you have encountered this warning, please file an issue using this URL:<br/ >
</blockquote>

Since scrapy actually uses signals for various internal interactions, I'm not sure how to profile my code. Any help/tips/tricks is appreciated.

&nbsp;
**To Reproduce**
1. a few dependencies installed (I don't consider this error to be version specific, nor I will paste the whole <code>pip freeze</code> for brievity's sake:
- beautifulsoup4
- fastapi
- Jinja2
- python-dotenv
- requests
- scrapy
- ipython
- scalene
2. run the command <code>scalene --outfile profiled.html --html --memory --profile-all run.py</code>
3. No output, until scrapy kicked in and saw the usual
<blockquote>
2022-12-18 23:00:06 [scrapy.utils.log] INFO: Scrapy 2.7.0 started (bot: ...)<br/ >
2022-12-18 23:00:06 [scrapy.utils.log] INFO: Versions: lxml 4.9.1.0, libxml2...<br/ >
...<br/ >
2022-12-18 23:00:07 [scrapy.core.engine] INFO: Spider opened<br/ >
2022-12-18 23:00:07 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)<br/ >
2022-12-18 23:00:07 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6028<br/ >
<b>Error: Scalene cannot profile your program because it (or one of its packages)<br/ >
uses timers or a signal that Scalene depends on (Terminated).<br/ >
If you have encountered this warning, please file an issue using this URL:<br/ >
https://github.com/plasma-umass/scalene/issues/new/choose<br/ ></b>
</blockquote>

&nbsp;
**Please include a minimum working example if at all possible.**

So, basically run.py looks like this:

```
... (redacted internal imports)
from scrapy.crawler import CrawlerProcess
from scrapy.utils.project import get_project_settings
if __name__ == "__main__":
    settings_payload = {
        (redacted, irrelevant settings)
    }
    settings = get_project_settings()
    settings.update(settings_payload)
    process = CrawlerProcess(settings)
    for spider in (...):
        name = spider.__name__.split(".")[-1]
        print(f"########################-Starting Scraping of {name}-########################")
        process.crawl(spider, settings={**settings_payload, "spider_name": name})
    process.start()
```

&nbsp;
**Expected behavior**
To be able to see the profiling of the whole app (runner and all it's dependencies). Interestingly, I got a veeeeeery short HTML tmp output, but nothing relevant (it dyied before outputing something useful)

&nbsp;
**Screenshots**
None

&nbsp;
**Desktop (please complete the following information):**
 - OS: Win 10 22H2 (v19045.2130)
 - Browser: not aplicable
 - IDE: VSC v1.73
 - Terminal: cmder v22.8.7.0
 - scalene: version 1.5.16 (2022.12.08)

&nbsp;
**_If you have not yet tried with the repository version (`python3 -m pip install git+https://github.com/plasma-umass/scalene`), please try that before reporting._**
It appears I'm using the latest release

&nbsp;
**Additional context**
None. Ask away to fill in as much detail as possible!

**Comment by emeryberger** [comment]
I believe this problem can be eliminated straightforwardly by eliminating support for the `--on` and `--off` switches for Windows (which I see does not actually currently work). Sound reasonable?

**Comment by emeryberger** [comment]
Please give it a try now with the latest repo version (`python3 -m pip install git+https://github.com/plasma-umass/scalene`) and let us know how it works - thanks!

**Comment by fer-zav** [comment]
Hi there @emeryberger,
Thanks for the suggestion! I tried them, first and foremost upgrading to latest (already on latest version), tried as normal, same error; tried with --on flag, error; tried with --off flag, error.
I'm not entirely sure if you were referring to a specific branch or something, but so far I'm getting the same error, along with something related to the GPU (not sure which command to run to avoid this, but since I'm not using the GPU, is the least of my concerns):

```
NOTE: The GPU is currently running in a mode that can reduce Scalene's accuracy when reporting GPU utilization. Run once as Administrator or root (i.e., prefixed with `sudo`) to enable per-process GPU accounting.
```
Thanks again, and happy holidays ") !
