### ISSUE TITLE
Error with code containing "±" character: SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0xb1 in position 0: invalid start byte

### ISSUE THREAD

**Issue by TeamDman** [plasma-umass/scalene#520]
**Describe the bug**
Scalene fails when source code contains unicode symbols

**To Reproduce**
1. run
```python
%%scalene
print("±")
```

Please include a minimum working example if at all possible.

**Expected behavior**
no error

**Screenshots**

![image](https://user-images.githubusercontent.com/9356891/209051602-b3e4e1ea-76f0-42dc-8abf-589ff81238ba.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Microsoft Windows 10.0.19044
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] Scalene Version: 1.5.16
- VSCode
```
Version: 1.74.0 (system setup)
Commit: 5235c6bb189b60b01b1f49062f4ffa42384f8c91
Date: 2022-12-05T16:38:16.075Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No
```

**Comment by emeryberger** [comment]
Thanks for the bug report. This should now be fixed in the repository version: please test by installing from there (`pip install git+https://github.com/plasma-umass/scalene`).

**Comment by TeamDman** [comment]
Confirmed working, thanks!

![image](https://user-images.githubusercontent.com/9356891/209449925-2445060e-0009-4c12-9a9b-3f4a838906d5.png)
