### ISSUE TITLE
Error Msg: Scalene: Program did not run for long enough to profile.

### ISSUE THREAD

**Issue by sumit1000** [plasma-umass/scalene#533]
I am testing the small script test2.py. with command line

python3 -m scalene --cli test2.py

And showing error: 

"Scalene: Program did not run for long enough to profile."

Note: test2.py in attachment.
[test2.py.zip](https://github.com/plasma-umass/scalene/files/10335794/test2.py.zip)

_Originally posted by @sumit1000 in https://github.com/plasma-umass/scalene/issues/458#issuecomment-1369604554_

**Comment by emeryberger** [comment]
This is expected behavior. This script takes 3.0333000000000443e-05 seconds. This is far too little time for Scalene to profile. If a program takes less than 1/100th of a second, it's really (a) not appropriate for profiling and (b) not going to result in any samples taken by Scalene.
