### ISSUE TITLE
Exclude imports from being profiled.

### ISSUE THREAD

**Issue by ialvata** [plasma-umass/scalene#535]
**Is your feature request related to a problem? Please describe.**
As it's been described [here](https://github.com/plasma-umass/scalene/issues/487), scalene_profiler methods start and stop don't seem to be working. 
This leaves me at a conundrum... I have to import some weighty libraries.
However, they mask the RAM usage of the example data I'm trying to perform... In real life, these libraries are in a separate server, so their RAM usage is not important. 
Furthermore, scalene doesn't seem to have an exclude imports option for the profiler.
If I try to create more data to overshadow the imports, then I cease to be able to run the script on my laptop. 

**Describe the solution you'd like**
from cli, a `--no-imports` option would exclude the imports from the profiler.

**Describe alternatives you've considered**
fix scalene_profiler start and stop methods, and then I would do the following

```
## main.py
from module_1 import main_function
scalene_profiler.start()
module_1_function()
scalene_profiler.stop()

## module_1.py
scalene_profiler.stop()
import heavy_module
scalene_profiler.start()

def module_1_function():
(...)

```

**Comment by nickpowersys** [comment]
I find that imports can account for a significant percentage of the total time.

Having the option to exclude them could give better insight into where there is potential for optimization.

**Comment by emeryberger** [comment]
https://github.com/plasma-umass/scalene/issues/487 has now been fixed, so you can surround your import statements with `stop` and `start` as above and it should no longer profile memory consumption (or CPU activity) when profiling disabled.

**Comment by emeryberger** [comment]
@nickpowersys I hope this solves your issue as well.
