### ISSUE TITLE
Scalene `SIGABRT`s with "libscalene.dylib could not be loaded" if there are spaces in the virtualenv path

### ISSUE THREAD

**Issue by edmorley** [plasma-umass/scalene#537]
**Describe the bug**
If there are spaces in the path of the Python virtual environment into which Scalene is installed, Scalene errors at runtime with the following error:

```
dyld[63707]: terminating because inserted dylib '/Users/emorley/src/foo\ bar/.venv/lib/python3.11/site-packages/scalene/libscalene.dylib' could not be loaded: tried: '/Users/emorley/src/foo\ bar/.venv/lib/python3.11/site-packages/scalene/libscalene.dylib' (no such file), '/usr/local/lib/libscalene.dylib' (no such file), '/usr/lib/libscalene.dylib' (no such file)
dyld[63707]: tried: '/Users/emorley/src/foo\ bar/.venv/lib/python3.11/site-packages/scalene/libscalene.dylib' (no such file), '/usr/local/lib/libscalene.dylib' (no such file), '/usr/lib/libscalene.dylib' (no such file)
Scalene error: received signal SIGABRT
```

...even though the `libscalene.dylib` file does actually exist at the location mentioned in the error message.

If the virtualenv path does not contain spaces, then Scalene works as expected.

**To Reproduce**
1. `mkdir 'foo bar' && cd "$_"`
2. `python -m venv .venv && source .venv/bin/activate`
3. `pip cache purge`
4. `pip install scalene`
5. `scalene --version`
6. `curl -sSO https://raw.githubusercontent.com/plasma-umass/scalene/master/test/testme.py`
7. `scalene testme.py`

**Expected behavior**
The `scalene testme.py` command successfully starts the script (it will still error out unless `numpy` is also installed, but Scalene itself shouldn't `SIGABRT`).

**Actual behaviour**

```term
src $ mkdir 'foo bar' && cd "$_"
foo bar $ python -m venv .venv && source .venv/bin/activate
(.venv) foo bar $ pip cache purge
Files removed: 26
(.venv) foo bar $ pip install --progress-bar off scalene
Collecting scalene
  Downloading scalene-1.5.18-cp311-cp311-macosx_10_9_universal2.whl (507 kB)
Collecting wheel>=0.36.1
  Downloading wheel-0.38.4-py3-none-any.whl (36 kB)
Collecting rich>=10.7.0
  Downloading rich-13.0.0-py3-none-any.whl (238 kB)
Collecting cloudpickle>=1.5.0
  Downloading cloudpickle-2.2.0-py3-none-any.whl (25 kB)
Collecting pynvml>=11.0.0
  Downloading pynvml-11.4.1-py3-none-any.whl (46 kB)
Collecting Jinja2>=3.0.3
  Downloading Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting MarkupSafe>=2.0
  Downloading MarkupSafe-2.1.1.tar.gz (18 kB)
  Preparing metadata (setup.py) ... done
Collecting commonmark<0.10.0,>=0.9.0
  Downloading commonmark-0.9.1-py2.py3-none-any.whl (51 kB)
Collecting pygments<3.0.0,>=2.6.0
  Downloading Pygments-2.14.0-py3-none-any.whl (1.1 MB)
Installing collected packages: commonmark, wheel, pynvml, pygments, MarkupSafe, cloudpickle, rich, Jinja2, scalene
  DEPRECATION: MarkupSafe is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for MarkupSafe ... done
Successfully installed Jinja2-3.1.2 MarkupSafe-2.1.1 cloudpickle-2.2.0 commonmark-0.9.1 pygments-2.14.0 pynvml-11.4.1 rich-13.0.0 scalene-1.5.18 wheel-0.38.4
(.venv) foo bar $ scalene --version
Scalene version 1.5.18 (2023.01.02)
(.venv) foo bar $ curl -sSO https://raw.githubusercontent.com/plasma-umass/scalene/master/test/testme.py
(.venv) foo bar $ scalene testme.py
dyld[63707]: terminating because inserted dylib '/Users/emorley/src/foo\ bar/.venv/lib/python3.11/site-packages/scalene/libscalene.dylib' could not be loaded: tried: '/Users/emorley/src/foo\ bar/.venv/lib/python3.11/site-packages/scalene/libscalene.dylib' (no such file), '/usr/local/lib/libscalene.dylib' (no such file), '/usr/lib/libscalene.dylib' (no such file)
dyld[63707]: tried: '/Users/emorley/src/foo\ bar/.venv/lib/python3.11/site-packages/scalene/libscalene.dylib' (no such file), '/usr/local/lib/libscalene.dylib' (no such file), '/usr/lib/libscalene.dylib' (no such file)
Scalene error: received signal SIGABRT
```

However notice that the file does actually exist at the location the error message mentions:

```
(.venv) foo bar $ stat /Users/emorley/src/foo\ bar/.venv/lib/python3.11/site-packages/scalene/libscalene.dylib
  File: /Users/emorley/src/foo bar/.venv/lib/python3.11/site-packages/scalene/libscalene.dylib
  Size: 346434    	Blocks: 680        IO Block: 4096   regular file
Device: 1,18	Inode: 41733360    Links: 1
Access: (0755/-rwxr-xr-x)  Uid: (  502/ emorley)   Gid: (   20/   staff)
Access: 2023-01-06 11:57:16.961924827 +0000
Modify: 2023-01-06 11:57:16.958134310 +0000
Change: 2023-01-06 11:57:16.958216143 +0000
 Birth: 2023-01-06 11:57:16.957435315 +0000
```

**Additional context**
 - macOS 12.6 Monterey, on an M1 MacBook Pro
 - Homebrew Python 3.11.1
 - pip 22.3.1 and setuptools 65.6.3 (inside the virtualenv)
 - The error occurs with both Scalene 1.5.18 installed via wheel (per the steps to reproduce above), and also if I install from `main` of the GitHub repository (which not only tests `main`, but also that the issue still occurs when not using the pre-built wheel).
 - I've not seen this error with any other projects that contain compiled components (though from searching my projects, I see most of the dependencies with compiled components use `.so` files in `site-packages` not `.dylib` files). I also couldn't find any similar issues in the pip or setuptools repositories.
 - In my case, there are spaces in the virtualenv path, since I'm using [Hatch](https://github.com/pypa/hatch) to manage my virtual environments, and on macOS Hatch stores the environments in `/Users/USER/Library/Application Support/hatch/env/virtual/`. I've not used Hatch in the STR above (and instead created a venv manually) to simplify the bug report.

**Comment by emeryberger** [comment]
Thanks for your report! I've reproduced and apparently debugged this. Please test the repository version and let me know!

**Comment by edmorley** [comment]
@emeryberger Thank you - that fix worked :-)
