### ISSUE TITLE
Profiling using `-m mypackage` fails if the module's `__main__.py` contains relative imports

### ISSUE THREAD

**Issue by edmorley** [plasma-umass/scalene#539]
**Describe the bug**
Support for profiling modules that would ordinarily be run via the `-m mypackage` syntax (which uses a package's `__main__.py` entry point) was added recently in #484, fixing #244.

However, if this feature is used with a package whose `__main__.py` file contains relative imports, then profiling fails with `ModuleNotFoundError`.

I believe this is due to the approach used to load modules - which is to convert the `-m mypackage` argument to instead reference the `__main__.py` file directly - which bypasses the usual module loading process.

**To Reproduce**
1. `mkdir testcase && cd $_`
2. `python -m venv .venv && source .venv/bin/activate`
3. `pip install scalene==1.5.18 salesforce-functions==0.2.0`
4. `scalene -m salesforce_functions`

**Expected behavior**

Scalene successfully runs. (With the reduced example above, a profile won't actually be created since the program doesn't run for long enough, but Scalene itself shouldn't error.)

Or as a last resort, Scalene should gracefully handle the `ModuleNotFoundError` and warn that relative imports in `__main__.py` aren't currently supported.

**Actual behavior**

```
(.venv) testcase $ scalene -m salesforce_functions
Error in program being profiled:
 No module named 'scalene._internal'
Traceback (most recent call last):
  File "/Users/emorley/src/testcase/.venv/lib/python3.11/site-packages/scalene/scalene_profiler.py", line 1784, in profile_code
    exec(code, the_globals, the_locals)
  File "/Users/emorley/src/testcase/.venv/lib/python3.11/site-packages/salesforce_functions/__main__.py", line 3, in <module>
    from ._internal import cli
ModuleNotFoundError: No module named 'scalene._internal'
Scalene: Program did not run for long enough to profile.
```

The failing line corresponds to:
https://github.com/heroku/sf-functions-python/blob/v0.2.0/salesforce_functions/__main__.py#L3

Note the `scalene._internal` part of the error message, which comes from the `__main__.py` file's `from ._internal import cli` line being incorrectly treated as relative to the `scalene` package, not the `salesforce_functions` package.

If I change that line to be an absolute import (ie: `from salesforce_functions._internal import cli`), then Scalene works. (Relative imports can be left as is in the rest of the `salesforce_functions` project, just not `__main__.py`)

**Additional context**
 - macOS 12.6 Monterey, on an M1 MacBook Pro
 - Homebrew Python 3.11.1
 - The error occurs with both Scalene 1.5.18 (per the steps to reproduce above), and also if I install from `main` of the GitHub repository.
 - The error occurs with both the `scalene` and `python -m scalene` CLI syntax styles.

**Comment by sternj** [comment]
Replicated, working on it

**Comment by sternj** [comment]
I've tracked down the issue, basically we're just neglecting to set the variable `__package__` in the dict we're passing into the `exec` call! PR forthcoming (after I eat some dinner)

**Comment by emeryberger** [comment]
Please try with the repo version (`python3 -m pip install -U git+https://github.com/plasma-umass/scalene`). This now works on our end - thanks!

**Comment by edmorley** [comment]
Thank you - confirmed fixed on `master`.

**Comment by emeryberger** [comment]
Thanks! This fix is now in the latest release.
