### ISSUE TITLE
scalene does not work on colab, SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by qsh-zh** [plasma-umass/scalene#543]
I attached a [colab](https://colab.research.google.com/drive/1d7muipMmF919VgP5xU89unIZrEs-bG6D?usp=sharing) to reproduce the error.

![image](https://user-images.githubusercontent.com/28699575/211970025-5270e6c8-3a75-4b9a-9f03-7afd906c47b1.png)

**Describe the bug**

**To Reproduce**

Please include a minimum working example if at all possible.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

If you have not yet tried with the repository version (`python3 -m pip install git+https://github.com/plasma-umass/scalene`), please try that before reporting.

**Additional context**

**Comment by qsh-zh** [comment]
@emeryberger  Thanks for your quick response. However, it seems there are no output/profiling results in colab?

![image](https://user-images.githubusercontent.com/28699575/212262067-c625ee11-8a07-4b5f-a7f5-3a9df762fce6.png)

**Comment by emeryberger** [comment]
Yes, working on getting the web UI working again in the notebook (Jupyter doesn't want to let me display anything with JavaScript...). In the interim, you can use `%%scalene --cli`, which I may end up just hard-coding as a temporary solution.

**Comment by emeryberger** [comment]
Web UI is now working for local colab notebooks.
