### ISSUE TITLE
Long Running scripts

### ISSUE THREAD

**Issue by Dave-DigiMim** [plasma-umass/scalene#549]
I have scripts that run continuously on a Raspberry PI. 
Most of these scripts never close. Maybe get an hourly output to compare  if say memory usage is growing etc.
I could use scalene_profiler.start() and scalene_profiler.stop() in all scripts but as the PyCon presenter said it's easier if we don't need  to modify scripts..
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sternj** [comment]
Please elaborate further on what you want to see after reading the entirety of the README. I suspect the profile_interval argument may be to your liking.

**Comment by Dave-DigiMim** [comment]
Wow it is there already.. This is the most amazing python package I have ever encountered
