### ISSUE TITLE
Not able to use the memory profiling functionality when "sys.platform == "win32""

### ISSUE THREAD

**Issue by Kujo-Jotaro-sama** [plasma-umass/scalene#555]
It seems the argument for memory profiling is initialised to be false when sys.platform == "win32". I have tried with the following variations of the command line code, but none were able to return output on the memory usage of my python code:

`python -m scalene my_code.py`
`python -m scalene --memory --cpu --gpu my_code.py`
`python -m scalene --memory True --cpu --gpu my_code.py`
`python -m scalene --memory true --cpu --gpu my_code.py`

It would be hugely appreciated if more instructions could be given on how to turn on the memory profiling functionality in this case, as the command lines from the readme file do not seem to work.

**Comment by emeryberger** [comment]
Memory profiling is not currently available for Windows. This is on the web page:
>  (Note: the Windows version isn't yet complete; it currently only supports CPU profiling.)
