### ISSUE TITLE
Disagreement between "elapsed_time_sec" in the json and html output

### ISSUE THREAD

**Issue by Kujo-Jotaro-sama** [plasma-umass/scalene#557]
**Describe the bug**
As stated in the title the time elapsed reported in the html and json files are different. The one in the json file is exactly 60s shorter than one reported in html.

**To Reproduce**
Please try to run any code that would take more than 2mins. When runtime < 2mins the html file would report time in seconds rather than in ?m:??.???s format. Seems the html file could be converting the time wrong.

**Screenshots**
<img width="548" alt="Screenshot 2023-01-30 at 02 08 54" src="https://user-images.githubusercontent.com/50580256/215410469-ddd8b0ab-b6ce-44a0-95e5-59b79b6aee61.png">
<img width="374" alt="Screenshot 2023-01-30 at 02 09 15" src="https://user-images.githubusercontent.com/50580256/215410524-5a9b7db1-2a06-4d39-b177-4f71c1606256.png">

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.1
 - Browser: Chrome
 - Version: scalene 1.5.19 (2023.01.06)

**Comment by emeryberger** [comment]
Thanks for the report! This _should_ be fixed in the repository version now.
