### ISSUE TITLE
Following issue of 556

### ISSUE THREAD

**Issue by easonwang717** [plasma-umass/scalene#558]
See the description in issue 556 to reproduce...

When I just want to profile the cpu using:

scalene --cpu --json --outfile fedcor_cpu.json src/federated_main.py --GPU=2 --dataset=cifar --model=cnn --kernel_sizes 3 3 3 --num_filters 32 64 64 --mlp_layer 64 --epochs=10 --num_user=100 --frac=0.05 --local_ep=5 --local_bs=50 --lr=0.01 --lr_decay=1.0 --optimizer=sgd --reg=3e-4 --iid=0 --unequal=0 --alpha=0.2 --verbose=1 --seed 1 --gpr --gpr_selection --discount_method=time --discount=0.9 --GPR_interval=5 --group_size=51 --GPR_gamma=0.97 --poly_norm=0 --warmup=2

I got the error: unrecognized arguments: src/federated_main.py

I doubt the is there any bugs in scalene when parsing arguments into the python file?

**Comment by emeryberger** [comment]
You need to list all Scalene's arguments first, then `---`, and then any arguments for the Python program being profiled.
