### ISSUE TITLE
Scalene HTML missing CPU and Memory data with multiple files

### ISSUE THREAD

**Issue by matteoacrossi** [plasma-umass/scalene#560]
**Describe the bug**
HTML output misses CPU info and memory info on M1 Mac when code is on more than one python file.

**To Reproduce**
Create a `test_module.py` file with content:

```python
import numpy as np

def profile_me():
    for i in range(6):
        x = np.array(range(10**7))
        y = np.array(np.random.uniform(0, 100, size=(10**8)))
```

And a file `scalene_test.py` with content:
```python
from test_module import profile_me

if __name__ == "__main__":
    profile_me()
```

These two files reproduce the standard scalene code example. But if I run `scalene scalene_test.py` I obtain an HTML result like in the screenshot, without any time or memory data. If I run `scalene scalene_test.py --cli`, then I obtain the expected results.

If I put everything is in one file `scalene_test.py` I obtain the expected output in the HTML page:
```python
import numpy as np

def profile_me():
    for i in range(6):
        x = np.array(range(10**7))
        y = np.array(np.random.uniform(0, 100, size=(10**8)))

if __name__ == "__main__":
    profile_me()
```

**Expected behavior**

I should be able to see CPU and memory info in the HTML with separate python modules, like in the CLI case.

**Screenshots**
<img width="1159" alt="Screenshot 2023-02-02 at 22 05 05" src="https://user-images.githubusercontent.com/9745862/216439025-cf5c90b9-a15b-4757-8430-c3c7d1a7a478.png">

<img width="1419" alt="Screenshot 2023-02-02 at 22 13 33" src="https://user-images.githubusercontent.com/9745862/216439593-c51b433b-85e5-4b84-897e-13a251df9e30.png">

**Desktop (please complete the following information):**
 - OS: MacOS 13.1 (M1 Pro)
 - Browser: Safari, Firefox
 - Version: 16.2, 109

I tried with the repository version too. Same issue.

**Comment by emeryberger** [comment]
Does not reproduce (tested with Chrome and Safari), using current repository version on M1, same OS. What version of Python are you using? Also, does the word `scalene` happen to appear in the directory where you are executing this code?

**Comment by matteoacrossi** [comment]
Now that I recreated a fresh python environment in a new folder, I figured out that the problem is actually due to the presence of spaces in the path.
<img width="1118" alt="image" src="https://user-images.githubusercontent.com/9745862/217014299-f753a3ff-a412-4d4c-ba50-8f298c6bc63c.png">
<img width="982" alt="image" src="https://user-images.githubusercontent.com/9745862/217014400-d6ad09bd-9d1d-4f87-9eec-f16d793a2af7.png">

**Comment by emeryberger** [comment]
Thanks! That report helped me quickly zero in on the issue. Please try again from the repo version.
