### ISSUE TITLE
Could this package work with newer versions of nvidia-ml-py?

### ISSUE THREAD

**Issue by DManowitz** [plasma-umass/scalene#563]
I see from looking at previous issues that there was an issue with certain versions of nvidia-ml-py causing a problem because of a use of a print statement instead of a function.  However, has anyone checked to see if newer versions of nvidia-ml-py still have this problem?

The reason I ask is that it looks like the nvida-ml-py package is being maintained more regularly than pynvml at this point (https://pypi.org/project/nvidia-ml-py/#history vs https://pypi.org/project/pynvml/#history), and I'm trying to set up an environment primarily using conda, which explicitly blocks installation of both pynvml and nvidia-ml-py (whereas I believe pip would just have the later install clobber the prior install).

**Comment by emeryberger** [comment]
Thanks for letting us know; it had for long time seemed like `nvidia-ml-py` was in effect abandonware. IIRC the API is the same, but I have no idea if they have fixed the previous issues.

**Comment by emeryberger** [comment]
I just tested this and it appears to work fine. Can you verify on your end? (Just uninstall `pynvml`)

**Comment by yonil7** [comment]
Another impact of depending on `pynvml` instead of `nvidia-ml-py` is that the latest versions of `scalene` cant be installed together with `ray` because ray depends on `gpustat` that depends on `nvidia-ml-py` that cant be installed together with `pynvml`

For example, creating a simple using `conda create -n test_env python=3.9.18 ray-default=2.8.1 scalene=1.5.31.1` fails.

**Comment by DManowitz** [comment]
Actually, at the moment, `pynvml` has not been updated in a while, but `nvidia-ml-py` is getting regular updates.

**Comment by yonil7** [comment]
Yes, it seems that its better to depend on `nvidia-ml-py` instead of `pynvml`

**Comment by DManowitz** [comment]
@emeryberger Any thoughts about reverting this package to use `nvidia-ml-py` at this point?  As a couple of us have mentioned, it seems to be getting updated much more regularly than `pynvml` at this point.

**Comment by emeryberger** [comment]
As of the latest release (1.5.42), Scalene is back to using `nvidia-ml-py`.

**Comment by DManowitz** [comment]
@emeryberger I just noticed that both `nvidia-ml-py` and `nvidia-ml-py3` are specified as dependencies now.  Why is that?  From PyPi, it looks like `nvidia-ml-py3` only had a single release 7 years ago.  It seems that only `nvidia-ml-py` should be a dependency.

**Comment by DManowitz** [comment]
@emeryberger Sorry to bother you, but could you release 1.5.42.3 (ideally to both PyPi and conda-forge) without the `nvidia-ml-py3` dependency?  Thanks.
