### ISSUE TITLE
Proposed optimizations bug

### ISSUE THREAD

**Issue by rezasalehichegeni** [plasma-umass/scalene#570]
**Describe the bug**
There's an advanced option when locally running a code but no option when the same code is run remote on a server. What should I do to see proposed optimizations?

my script to run scalene:
scalene my_code.py

**Comment by emeryberger** [comment]
I'm assuming you mean that the viewer (https://plasma-umass.org/scalene-gui/) was not updated; it is now! If you mean something else, please let me know and we'll re-open.

**Comment by rezasalehichegeni** [comment]
Thanks for your response,
Unfortunately, I still can't use these features on the remote server and "advanced options" isn't shown . Is there a way to solve this problem?

**Comment by emeryberger** [comment]
If you look closely, you should be able to see the "advanced options" triangle. Click on the triangle.

<img width="1007" alt="Screenshot 2023-02-27 at 12 39 31 PM" src="https://user-images.githubusercontent.com/1612723/221640938-48a6652b-3688-4229-9a38-7978da270e2b.png">
