### ISSUE TITLE
Scalene cannot profile your program because it uses timers or a signal that Scalene depends on

### ISSUE THREAD

**Issue by victorapostol** [plasma-umass/scalene#574]
**Describe the bug**
Scalene cannot profile programs using PyTorch Lightning. Trying to run a simple program, results in this error:
```
Error: Scalene cannot profile your program because it (or one of its packages)
uses timers or a signal that Scalene depends on (Illegal instruction).
```

**To Reproduce**

You can use [this](https://gist.github.com/rain1024/8ea4c2f56aa4c9ba0e1cbf35edb68eca) to reproduce the error.
```
import pytorch_lightning as pl
import numpy as np
import torch
from torch.nn import MSELoss
from torch.optim import Adam
from torch.utils.data import DataLoader, Dataset
import torch.nn as nn


class SimpleDataset(Dataset):
    def __init__(self):
        X = np.arange(10000)
        y = X * 2
        X = [[_] for _ in X]
        y = [[_] for _ in y]
        self.X = torch.Tensor(X)
        self.y = torch.Tensor(y)

    def __len__(self):
        return len(self.y)

    def __getitem__(self, idx):
        return {"X": self.X[idx], "y": self.y[idx]}


class MyModel(pl.LightningModule):
    def __init__(self):
        super().__init__()
        self.fc = nn.Linear(1, 1)
        self.criterion = MSELoss()

    def forward(self, inputs_id, labels=None):
        outputs = self.fc(inputs_id)
        loss = 0
        if labels is not None:
            loss = self.criterion(outputs, labels)
        return loss, outputs

    def train_dataloader(self):
        dataset = SimpleDataset()
        return DataLoader(dataset, batch_size=1000)

    def training_step(self, batch, batch_idx):
        input_ids = batch["X"]
        labels = batch["y"]
        loss, outputs = self(input_ids, labels)
        return {"loss": loss}

    def configure_optimizers(self):
        optimizer = Adam(self.parameters())
        return optimizer


if __name__ == '__main__':
    model = MyModel()
    trainer = pl.Trainer(max_epochs=20, gpus=1)
    trainer.fit(model)
```
Run it with 
```
python -m scalene pytorch_lightning_simplest_example.py 
```
After a few seconds when the training it's done, the error message is printed (2 times):
```
Error: Scalene cannot profile your program because it (or one of its packages)
uses timers or a signal that Scalene depends on (Illegal instruction).
If you have encountered this warning, please file an issue using this URL:
https://github.com/plasma-umass/scalene/issues/new/choose
Error: Scalene cannot profile your program because it (or one of its packages)
uses timers or a signal that Scalene depends on (Illegal instruction).
If you have encountered this warning, please file an issue using this URL:
https://github.com/plasma-umass/scalene/issues/new/choose
```

The profiling info from `profile.html` does not display any information for most of the lines.

**Expected behavior**
Explicitly state the library that's causing the error, or point to the piece of code that has conflicting signals/ timers.

**Desktop:**
 - OS: Ubuntu 20.04
 - Browser Firefox 110.0
 - PyTorch 1.11.0
 - PyTorch-Lightning 1.7.7
 - Python 3.8

If you have not yet tried with the repository version (`python3 -m pip install git+https://github.com/plasma-umass/scalene`), please try that before reporting.

I've tried both pip installing the latest version of `scalene` (`1.5.20`) and the repository version. Both give the same results.

**Additional context**
When I try to run scalene with my code that uses pytorch-lightning, the only lines that are profiled are the imports.

Related to #488

**Comment by anjaliagarwal8** [comment]
I am also encountering the same error for my code that uses PyTorch lightning.

**Comment by sternj** [comment]
I haven't dealt with Pytorch Lightning specifically, but Scalene uses some (uncommonly used) signals that, unfortunately, we need to reserve for Scalene's functionality. I'll dig into whether there's any way to use a different signal in Pytorch Lightning, or if there's an even less commonly used signal common to all UNIX-like systems that we can replace `SIGILL` with, but unfortunately this might just be intractable as long as Lightning uses that signal.

**Comment by kunaltyagi** [comment]
Any updates or workarounds for this?

**Comment by vitkl** [comment]
Same issue. Which profiler would you recommend using to detect memory leaks if any solutions to this are impossible?

**Comment by emeryberger** [comment]
This should be fixed with the repo version: `python3 -m pip install git+https://github.com/plasma-umass/scalene` (this fixes the repro case above). Please let us know if it works for you or if you encounter other problems. Expected behavior is now a warning message rather than an exit.

```
WARNING: signal Illegal instruction: 4 is used to
enable or disable Scalene. Starting or stopping Scalene with
`--start` or `--stop` will be disabled.
WARNING: Scalene uses Alarm clock: 14 to profile.
If your code raises Alarm clock: 14 from non-Python code, use SIGUSR1.
Code that raises signals from within Python code will be rerouted.
```

**Comment by victorapostol** [comment]
I confirm that I can reproduce the expected output with the repository version.

**Comment by emeryberger** [comment]
This change has been incorporated in the latest release. Thanks again for your reports!
