### ISSUE TITLE
Aarch64 architectures

### ISSUE THREAD

**Issue by ismetdagli** [plasma-umass/scalene#580]
Is this safe to use on aarch64 architectures? For example, can we use scalene for NVIDIA Xavier AGX or AGX Orin etc.?

Note: I guess it is enabled on arm, i.e raspberry pi, but I don't know about aarch64.

**Comment by emeryberger** [comment]
I don't have any such system at my disposal. There's no a priori reason I can think of why it wouldn't work. It works fine on the M1, for example. Please try and build from source and let us know what happens. Thanks.

**Comment by mevinbabuc** [comment]
yeah, it works fine on ARM processors. We have used this on ARM processors on EC2.
Scalene builds from source on ARM and requires git as a dependency among others.

This can be closed.

**Comment by emeryberger** [comment]
Thanks for the info, @mevinbabuc - please let me know if there’s anything I can do to make the process easier!
