### ISSUE TITLE
Daemon thread join timeout=0 behavior differs between ordinary python and scalene

### ISSUE THREAD

**Issue by maximilianmordig** [plasma-umass/scalene#597]
Here is an example program (`test_threads.py`):
```
import threading
import time

def do_work():
    print("Starting work")
    time.sleep(5)
    print("Finishing work after 5 seconds")
    
t1 = threading.Thread(target=do_work, args=(), daemon=True)
t1.start()
time.sleep(1)
print("Finished sleeping 1 second")
t1.join(timeout=0)
# t1.join(timeout=0.01)
print("Program done")
```
Executing it as `python test_threads.py` gives expected output:
```
Starting work
Finished sleeping 1 second
Program done
```

Running `scalene --html --outfile scalene_profiler_report.html --- test_threads.py` gives:
```
Starting work
Finished sleeping 1 second
Finishing work after 5 seconds
Program done
```
which means that the join timeout was ignored.

If I replace `t1.join(timeout=0)` by `t1.join(timeout=0.01)`, the scalene output agrees with the ordinary python script output.

I have attached the output of `pip freeze`.
[pipfreeze_scalenejointimeout.txt](https://github.com/plasma-umass/scalene/files/11221810/pipfreeze_scalenejointimeout.txt)

`uname -a`:
Linux someHostname 5.4.0-146-generic #163-Ubuntu SMP Fri Mar 17 18:26:02 UTC 2023 x86_64 GNU/Linux

**Comment by emeryberger** [comment]
Thanks for the report! This should now work correctly (verified locally).
