### ISSUE TITLE
Report directory relative to python script cwd at exit

### ISSUE THREAD

**Issue by maximilianmordig** [plasma-umass/scalene#598]
Consider the file `myfile.py`:
```
import os
from pathlib import Path
import time

dir = Path("test123")
dir.mkdir(exist_ok=True)
print(f"Changing to directory {os.getcwd()}")
os.chdir(dir)
print(f"Changed to directory {os.getcwd()}")
# wait so that enough time to sample
time.sleep(5)
print("Program done")
```

Executing it as `scalene --html --outfile report.html --- myfile.py` creates a report at `test123/report.html` rather than in the current working directory `./report.html`.

pip freeze:
[pipfreeze_scalenejointimeout.txt](https://github.com/plasma-umass/scalene/files/11222150/pipfreeze_scalenejointimeout.txt)

`uname -a`:
Linux someHostname 5.4.0-146-generic #163-Ubuntu SMP Fri Mar 17 18:26:02 UTC 2023 x86_64 GNU/Linux

**Comment by emeryberger** [comment]
Thanks for the report! This should now work as expected (verified locally).
