### ISSUE TITLE
Jupyter magic %scrun ignores html command line argument

### ISSUE THREAD

**Issue by maximilianmordig** [plasma-umass/scalene#600]
The following code in Jupyter should output to a html file, but instead outputs to a json:
```
import numpy as np

def f():
    x = np.array(range(10**7))
    print("H")
%scrun --html --outfile scalene_profiler_report.html --- f()
```

## Why this happens

Currently, the `web` argument is always set to True: https://github.com/plasma-umass/scalene/blob/9bc73df080fdf766537a9266ba24171a2963d9f4/scalene/scalene_parseargs.py#L149.

Running it in a Jupyter session (from VSCode with remote ssh plugin), there is no webbrowser available in my case (`webbrowser.get()` returns `<webbrowser.GenericBrowser at 0x14e2cd40abe0>`), so the following changes output to json https://github.com/plasma-umass/scalene/blob/9bc73df080fdf766537a9266ba24171a2963d9f4/scalene/scalene_profiler.py#L1689, which is undesired because I get no useful output in the end.
I solved it temporarily by uncommenting this if-block.
```
@staticmethod
    def stop() -> None:
        """Complete profiling."""
        Scalene.__done = True
        Scalene.disable_signals()
        Scalene.__stats.stop_clock()
        if (
            Scalene.__args.web
            and not Scalene.__args.cli
            and not Scalene.__is_child
        ):
            # since web argument is always True
            # if Scalene.in_jupyter():
            #     # Force JSON output to profile.json.
            #     Scalene.__args.json = True
            #     Scalene.__output.html = False
            #     Scalene.__output.output_file = Scalene.__profile_filename
            
            # Check for a browser.
            try:
                if (
```

**Comment by emeryberger** [comment]
Thanks for the report! This should now be fixed in the repo version. Please try:

`!pip install -U git+https://github.com/plasma-umass/scalene`

Thanks!
