### ISSUE TITLE
Numpy related Error

### ISSUE THREAD

**Issue by aspirin-1218** [plasma-umass/scalene#602]
Has anyone encountered numpy related issue as the screenshot shows below? Same error with the latest scalene release. 
I am using python 3.8.10 in Windows 10.
numpy==1.22.4
scalene==1.5.18
![image](https://user-images.githubusercontent.com/54863614/234260062-f151cfd5-ed13-4406-aa92-1293b01d27d6.png)

**Comment by emeryberger** [comment]
Our tests with numpy work fine on Windows 11, numpy==1.24.3, scalene==1.5.21.2. If you can share the script, perhaps it will reveal an issue we are unaware of - thanks!

**Comment by emeryberger** [comment]
Closing for lack of response.
