### ISSUE TITLE
Build/install is not self-contained

### ISSUE THREAD

**Issue by fhriley** [plasma-umass/scalene#607]
**Describe the bug**
When doing a `pip install scalene`, it will run `setup.py`, which then grabs a repo from `github.com`. This makes it impossible to use scalene on networks that have a pypi mirror, but do not have access to the internet.

**To Reproduce**
1. Run `pip install scalene` on a network with a pypi mirror but no internet access.

**Expected behavior**
It installs successfully.

**Comment by emeryberger** [comment]
AFAICT the only alternative here is to package up the dependencies into the wheel. This is an unusual scenario and I don't think we will address it without a contributed PR to review, so I am closing. Again, I welcome a PR.

**Comment by fhriley** [comment]
It looks like pypi has a compatible wheel now where before it didn't. Now when I pip install it grabs the wheel. Thanks!
