### ISSUE TITLE
Cannot memory profile the scalene example on W11 + NVIDIA card

### ISSUE THREAD

**Issue by laurapons** [plasma-umass/scalene#609]
**Describe the bug**
If I use the example from the repository (test/testme.py) and run it on my computer.
1. If I run it directly using `python test.py`  command, it works.
2. If I run it with scalene: `scalene test.py` it breaks. This is the output error:

There seems to be an issue with the numpy version, I wonder if there is a minimum version to be used when using scalene. I got no errors or updates when installing scalene on my computer. I currently use numpy==1.18.5

![image](https://user-images.githubusercontent.com/1275184/236775668-78386c19-1a6a-49ca-b8ed-18f1fac63a14.png)

**Desktop (please complete the following information):**
- Scalene version 1.5.21.2 (2023.04.20)
- Python 3.8.10
- OS: Windows 11 Pro.
- CPU: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz   2.80 GHz
- NVIDIA GeForce MX450

**Comment by laurapons** [comment]
I just upgraded to numpy 1.24.2 (taken from the lock file) and that worked, but I couldn't access do the memory profiling (eventhough I have an NVIDIA graphics card).

![image](https://user-images.githubusercontent.com/1275184/236776564-01a376a4-5bdc-4013-ade3-f94051ab3775.png)

![image](https://user-images.githubusercontent.com/1275184/236776648-6aa72810-71b8-40ab-a30d-7666b935786c.png)

**Comment by emeryberger** [comment]
Unfortunately, Scalene does not yet support (CPU) memory profiling on Windows. However, it does work on WSL2, if that helps.

**Comment by laurapons** [comment]
Thanks! Can't wait to test this on Windows! +1 to make it Windows compatible
