### ISSUE TITLE
memory profiling issue

### ISSUE THREAD

**Issue by Madeelajaib** [plasma-umass/scalene#611]
Hello,
I am trying to run this simple example in windows. However, when I run it, only the time column is displayed and memory profiling is not included in the output. Can you help me with this. Thanks

import random

def add(a, b):
      return a+b

def get_sum_of_list():
    final_list = []
    for i in range(100000):
        rand1 = random.randint(1,100)
        rand2 = random.randint(1,100)
        out = add(rand1, rand2)
        final_list.append(out)
    return final_list

if __name__ == "__main__":
    l = get_sum_of_list()

**Comment by emeryberger** [comment]
Unfortunately, Scalene does not yet support memory profiling on Windows. However, it works on WSL2.
