### ISSUE TITLE
Why does Scalene uses universal environment and not the local virtual environment?

### ISSUE THREAD

**Issue by adnaneGdihi** [plasma-umass/scalene#622]
**Describe the bug**
when running scalene it doesn't recognize installed packages in local virtual env. and one has to install those packages as globals in order for scalene to continue.

**To Reproduce**
1. install numpy on local venv
2. run scalene on a simple numpy program
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: w10
 - Python 3.8.10

**Comment by sternj** [comment]
Scalene is in and of itself a Python package, if you did not install it separately in the virtual environment, then the Scalene executable on your `$PATH` is probably the one associated with the global environment. Install it in the local venv!

**Comment by adnaneGdihi** [comment]
yes, It was a windows issue, where if users are separated changing the environment using user B while user A owns the folder. does not work.
