### ISSUE TITLE
scalene only report time and GPU usage

### ISSUE THREAD

**Issue by adnaneGdihi** [plasma-umass/scalene#626]
**Describe the bug**
Scalene does not measure CPU and memory

**To Reproduce**
1. profile a given program that uses all component (CPU, GPU, MEM)
2. Profiling should show only GPU and GPU memory

Please include a minimum working example if at all possible.

**Expected behavior**
The profiler should return measurements for all component (Time, CPU, Mem, Copy etc.)
expected columns
![image](https://github.com/plasma-umass/scalene/assets/28161107/88232160-eac4-4c94-9367-c7fa70ef6520)

**Screenshots**
Problem: I only get Time or (Time, GPU, GPU Memory)
![image](https://github.com/plasma-umass/scalene/assets/28161107/75140a15-92c2-4159-8ea1-b6980c045840)

**Desktop (please complete the following information):**
 - OS:WIN10
 - Browser chrome
 - Version 1.5.21.4+

**Comment by emeryberger** [comment]
Scalene does not support memory profiling for Windows. I thought this was on the home page somewhere... sorry. Windows makes this difficult.

**Comment by LucaMaurelliC** [comment]
Does it work if we profile an application with scalene on docker?

**Comment by emeryberger** [comment]
If it is running on Linux or Mac, it should work fine.

**Comment by emeryberger** [comment]
Closing as this is mentioned on the home page.
