### ISSUE TITLE
How to report a security vulnerability in Scalene?

### ISSUE THREAD

**Issue by davidfstr** [plasma-umass/scalene#628]
I have a security vulnerability to report in Scalene that I'd prefer to report privately. Does Scalene have an existing process for reporting security vulnerabilities privately?

If there is no existing process, GitHub has a new feature for [enabling security vulnerability reports](https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository) that you could enable on the Scalene repository.

**Comment by emeryberger** [comment]
Thanks for the note. I have enabled these reports.
