### ISSUE TITLE
HTML output breaks when profiled program contains line with `</script>`

### ISSUE THREAD

**Issue by davidfstr** [plasma-umass/scalene#629]
**Describe the bug**
Scalene's HTML output contains a JSON blob that is directly executed inside of a `<script>` block. The blob contains lines of source code from the program being profiled. However Scalene does not escape `</script>` tags that appear inside the JSON blob. Therefore profiling a Python library containing a line like `do_expensive_calculation()  # </script><script>alert("Oops");</script>` will break the page.

Additionally, hypothetically, a malicious program being profiled could inject HTML+JavaScript into the profiler's output HTML page which executes immediately, however any such malicious program would be executing (in Python) anyway. More details RE security implications in [GHSA-w8x2-7pp8-xphr](https://github.com/plasma-umass/scalene/security/advisories/GHSA-w8x2-7pp8-xphr) .

**To Reproduce**
* Write a Python program containing a line like:

```python
do_expensive_calculation()  # </script><script>alert("Oops");</script>
```

* ...or install the Python program [Crystal Web Archiver](https://dafoster.net/projects/crystal-web-archiver/) locally, which [contains such a line](https://github.com/davidfstr/Crystal-Web-Archiver/blob/6632b0ecb04af8568e5b4ef1e184b174cc5b0f71/src/crystal/doc/html/soup.py#L124). 
* Use Scalene to run the program and profile it.
* When the program exits, Scalene generates a profile.html and opens it in the user's web browser automatically.
* The rendered HTML page is broken. Also, any injected HTML code executes immediately.

**Expected behavior**
The rendered HTML page should not be broken.

**Screenshots**
Here's what a broken HTML page looks like:
<img width="1009" alt="Screen Shot 2023-06-20 at 9 06 11 PM" src="https://github.com/plasma-umass/scalene/assets/764688/a14d4be5-475b-4ab4-a9b5-4dbeb051c64f">

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7
 - Browser: Chrome 114
 - Version: scalene==1.5.21.4

**Suggested Fix**
Escape all JSON output that is dumped into HTML. Django's [json-script](https://docs.djangoproject.com/en/4.2/ref/templates/builtins/#json-script) filter escapes JSON data for inclusion to HTML by making the following substitutions:

```python
_json_script_escapes = {
    ord(">"): "\\u003E",
    ord("<"): "\\u003C",
    ord("&"): "\\u0026",
}
```

**Comment by sternj** [comment]
I can confirm that I've seen this happen myself but didn't quite have the time to dig into it! Thanks for the report, I'll hopefully have a fix in by tomorow!

**Comment by emeryberger** [comment]
Hi @davidfstr. Thanks for reporting. The latest version of the repo now includes a fix for this issue.
