### ISSUE TITLE
BUG: AI-powered proposed optimizations did not run on windows anymore.

### ISSUE THREAD

**Issue by 17Reset** [plasma-umass/scalene#642]
After using scalene on windows, the path of the file displayed on the html is '\', not '/', when clicking on explosion or lightning bolt, it doesn't work as expected, but after I change the path symbols in the html file, it works fine!

**Comment by emeryberger** [comment]
Could you provide some more details? I can't currently build Scalene on Windows due to some unknown issues... Thanks!

**Comment by 17Reset** [comment]
![屏幕截图 2023-07-26 103943](https://github.com/plasma-umass/scalene/assets/122418720/6c0f7b0d-4e9f-494e-b057-075f3636a7f2)
Ok, this is what it looks like after running it on windows, clicking on the lighting bolt or explosion on the ui will not work properly due to the path symbols.

**Comment by emeryberger** [comment]
Fixed in the repo version. We will issue a new release soon. Thanks for the report!

**Comment by 17Reset** [comment]
Not everyone may have a gpt-4 api, but the api must support 3.5

**Comment by emeryberger** [comment]
(If you are unable to use GPT-4, I'd like to know!)

**Comment by 17Reset** [comment]
> (If you are unable to use GPT-4, I'd like to know!)

Yes, my API key still only supports gpt-3.5 at the moment

**Comment by emeryberger** [comment]
Did you get it quite recently? Just trying to assess whether I need to add a command-line flag.

**Comment by emeryberger** [comment]
I just added an option to select the language model (in the UI, under advanced options). The default is GPT-4 (which produces better results than GPT-3.5) but you can now change it back.

<img width="564" alt="Screenshot 2023-07-28 at 12 13 39 PM" src="https://github.com/plasma-umass/scalene/assets/1612723/6631f2e3-e8df-4371-b172-d83c5db29406">

**Comment by 17Reset** [comment]
> I just added an option to select the language model (in the UI, under advanced options). The default is GPT-4 (which produces better results than GPT-3.5) but you can now change it back.
> 
> <img alt="Screenshot 2023-07-28 at 12 13 39 PM" width="564" src="https://user-images.githubusercontent.com/1612723/256875059-6631f2e3-e8df-4371-b172-d83c5db29406.png">

Thanks for adding the feature which will better enhance the experience.
