### ISSUE TITLE
BUG：Uncaught TypeError: Cannot read properties of undefined (reading 'lines')

### ISSUE THREAD

**Issue by 17Reset** [plasma-umass/scalene#643]
![0880edf53c29a7f5151ab8dd21ac3d8](https://github.com/plasma-umass/scalene/assets/122418720/5a44195a-3c33-49cb-b4a5-a2fdae18d801)
![8f01be417aa50f6ed399c97676809f8](https://github.com/plasma-umass/scalene/assets/122418720/dc8dfc4e-f932-49b7-960a-8be190158741)
When I click on the lighting bolts marked by arrows, I get the error shown above, and when my project is larger, all of the lighting bolts are in the upper row position of the function, and all of them will give me an error when clicked on.

**Comment by emeryberger** [comment]
Fixed in the repo version. We will issue a new release soon. Thanks for the report!

**Comment by emeryberger** [comment]
Please let me know if this fixes the UI problem, which looks like maybe a DOS newline issue (the latest release should solve the clicking on lightning bolt issue).
