### ISSUE TITLE
Help！How do I turn off automatic Web Mode?

### ISSUE THREAD

**Issue by 17Reset** [plasma-umass/scalene#645]
When I use the --html or --json command, it still opens the Web automatically after execution, and I would like to know how to control that it does not automatically open the Web using the browser, other than the --cli mode?

**Comment by emeryberger** [comment]
You can specify: `--cli --json --outfile foo.json` and it will not open a browser or print anything.

**Comment by 17Reset** [comment]
> You can specify: `--cli --json --outfile foo.json` and it will not open a browser or print anything.

Thank you for your reply, but using this mode, I found some more bugs, now feedback to you, I hope you also go to test, if it is my mistake, I hope your correction: 
1. open the json, click on the lighting bolt, there will be a console error message, the four arrows show the bolt, I clicked on it (default web mode does not have this error, you can click on it) I have clicked all of them (default web mode does not have this error, you can click it). 
3. there will still be empty lines marked lighting bolt, which is obviously incorrect.
![9QE~0$EG4@RD5F@ QL58YOC](https://github.com/plasma-umass/scalene/assets/122418720/46cba460-ff93-4b1d-94e5-07958b448d6e)

**Comment by emeryberger** [comment]
If you are using the Scalene GUI viewer on the web (http://plasma-umass.org/scalene-gui/), I've just updated that, so please try again. Thanks!

**Comment by emeryberger** [comment]
Closing for lack of response (should have been just an artifact of an old GUI script).
