### ISSUE TITLE
Unpickling error when using `--profile-all` and multiprocessing.

### ISSUE THREAD

**Issue by ibrarmalik** [plasma-umass/scalene#647]
When the code to profile is using a multiprocessing Pool, scalene throws an unpickling related error.

```python-traceback
Scalene failed to initialize.
Traceback (most recent call last):
  File "/Users/myUser/.virtualenvs/myVirtualEnv/lib/python3.9/site-packages/scalene/scalene_profiler.py", line 2059, in run_profiler
    exit_status = profiler.profile_code(
  File "/Users/myUser/.virtualenvs/myVirtualEnv/lib/python3.9/site-packages/scalene/scalene_profiler.py", line 1861, in profile_code
    did_output = Scalene.output_profile()
  File "/Users/myUser/.virtualenvs/myVirtualEnv/lib/python3.9/site-packages/scalene/scalene_profiler.py", line 933, in output_profile
    json_output = Scalene.__json.output_profiles(
  File "/Users/myUser/.virtualenvs/myVirtualEnv/lib/python3.9/site-packages/scalene/scalene_json.py", line 226, in output_profiles
    stats.merge_stats(python_alias_dir)
  File "/Users/myUser/.virtualenvs/myVirtualEnv/lib/python3.9/site-packages/scalene/scalene_statistics.py", line 405, in merge_stats
    value = unpickler.load()
  File "/Users/myUser/.virtualenvs/myVirtualEnv/lib/python3.9/site-packages/scalene/hashablelist.py", line 56, in extend
    self.__hash__()
  File "/Users/myUser/.virtualenvs/myVirtualEnv/lib/python3.9/site-packages/scalene/hashablelist.py", line 30, in __hash__
    if not self._hash:
AttributeError: 'HashableList' object has no attribute '_hash'
```

To reproduce, try running `scalene --profile-all example.py` with the following code:

```python
import multiprocessing

if __name__ == "__main__":
    with multiprocessing.Pool() as pool:
        pass
```

I have solved this, by modifying [`HashableList`](https://github.com/plasma-umass/scalene/blob/70c274b07b93d36d335fc0b0d9570424258a4cbc/scalene/hashablelist.py#L4) to inherit from `collections.UserList` instead of the built-in `list`. I can create a PR if someone can reproduce this issue.

**Comment by emeryberger** [comment]
Could not reproduce on Mac. What version of `cloudpickle` are you using? This was the culprit in the past.

```
% python3 -m pip freeze | grep cloudpickle
cloudpickle==2.2.1
```

**Comment by ibrarmalik** [comment]
Same version. Weird...

```bash
» pip freeze | grep cloudpickle
cloudpickle==2.2.1
```

**Comment by emeryberger** [comment]
Too bad. Can you go ahead and upgrade to the latest version of Scalene and try that? Also, what OS / platform are you on? Thanks.

**Comment by ibrarmalik** [comment]
Just installed the latest [release](https://github.com/plasma-umass/scalene/releases/tag/v1.5.23) from github, on a clean python env. Same issue persists.

I'm on MacOS Big Sur 11.6, x86-64.

**Comment by emeryberger** [comment]
Got it. Can you try `python3 -m pip install -U git+https://github.com/plasma-UMass/scalene` (to get the repo version)?

**Comment by ibrarmalik** [comment]
Just did it. Same issue, when running `scalene --profile-all example.py` with the snippet I shared before.

**Comment by ibrarmalik** [comment]
I can reproduce this on a Google Colab: https://colab.research.google.com/drive/1lCECdr6f9N0U7NDcc-2SB47UlpBVV2OV
I hope this helps.

**Comment by sroener** [comment]
I have the same problem in python3.10. 

```
scalene=1.5.21.4
cloudpickle=2.2.1
```

packages were installed via conda

**Comment by emeryberger** [comment]
I've just pushed the change suggested by @ibrarmalik. Please give it a try! (Conda users will have to wait for a new release, which I will push out if this resolves the issue.)

`python3 -m pip install -U git+https://github.com/plasma-UMass/scalene`

**Comment by emeryberger** [comment]
Verified that this fixes the issue on the colab notebook, @ibrarmalik.

**Comment by ibrarmalik** [comment]
Great! Thanks @emeryberger

**Comment by emeryberger** [comment]
I've now pushed a new release (installable via `pip`). I'm not sure why conda versions are not being updated...

**Comment by emeryberger** [comment]
Hi @ibrarmalik - would you mind checking this branch, which replaces HashableList with a tuple? `python3 -m pip install git+https://github.com/plasma-umass/scalene@remove_hashable_list`

I just verified that it works fine on the colab notebook you shared. Thanks!

**Comment by ibrarmalik** [comment]
@emeryberger It works in my local machine. Also, that's a much cleaner way to solve it, thanks!

**Comment by emeryberger** [comment]
Super! Thanks so much for your quick response!
