### ISSUE TITLE
There is no output on windows!

### ISSUE THREAD

**Issue by 17Reset** [plasma-umass/scalene#654]
Hi, when I update to the latest version of scalene, no matter what what command mode I use (web, cli), I don't get any result output.（Nothing has changed in my project, just updated to the latest version of scalene）

**Comment by 17Reset** [comment]
It may have something to do with my project, but since nothing is output, I can't tell, and my project works fine.

**Comment by emeryberger** [comment]
I just ran Scalene on Windows (Windows 11, Python 3.10, Scalene 1.5.25) and it produced the expected results. If you can provide a minimum working example (ideally), or share your project, I'd like to try it to see if I can reproduce your issue.

**Comment by emeryberger** [comment]
Bump @17Reset

**Comment by 17Reset** [comment]
> Bump @17Reset

Thanks，I solved it, it wasn't a problem with scalene, sorry, it was a little problem in my own program.
