### ISSUE TITLE
Program did not run for long enough to profile

### ISSUE THREAD

**Issue by aj-in** [plasma-umass/scalene#656]
I can't even install scalene on MacOS X, i used 
`pip install scalene`  it gives me the 1.5.21 version by default
I tried 
`pip install scalene==1.5.22.2`. it gives me an error "pip install scalene==1.5.22.2
ERROR: Could not find a version that satisfies the requirement scalene==1.5.22.2 (from versions: 0.1, 0.2a0, 0.2b0, 0.2, 0.3, 0.3.1, 0.3.2, 0.3.3, 0.4.0, 0.4.1, 0.4.2, 0.5.0, 0.5.1, 0.5.2,"

So I installed the default version 1.5.21, then tried profiling 
The main issue is I tried to profile a .json file using      
`scalene test.json`      this gave me an error "Program did not run for long enough to profile."

**Comment by emeryberger** [comment]
There was an issue with the Mac builds that hopefully is now addressed. I'll issue a new release to see what happens. In the interim, please try `python3 -m pip install -U git+https://github.com/plasma-umass/scalene` to install the repo version. Scalene cannot profile JSON files (I'm not sure what that would even look like). You should run it as `scalene my_prog.py` or `python3 -m scalene my_prog.py`.

**Comment by aj-in** [comment]
Hi , Tried writing a python script to read my .Json file. Scalene did
produce an HTML output but, It *didn't give me statistics for all lines of
code*. Could you please help me profile my JSON file? Below are the
attached files

**Comment by emeryberger** [comment]
Hi - no files were attached. You should probably drag and drop them in the Github web interface. (Also, it's unlikely that Scalene will provide statistics for _every_ line of code given that most lines of code don't consume >1% of execution time.)

**Comment by aj-in** [comment]
Hi, I did attach files to the previous email. Could you please help me?

**Comment by emeryberger** [comment]
Those attachments did not come through. I think you have to attach them from the web (go to https://github.com/plasma-umass/scalene/issues/656 and then drag and drop the files into the comment window).

**Comment by aj-in** [comment]
[https://github.com/aj-in/AttachedData](url)
Hi, this link contains the JSON file I am trying to profile. It also contains the Python file which can read the JSON data. So that I can execute `scalene skl_config copy.py`

**Comment by emeryberger** [comment]
I renamed the file and invoked `python3 skl_config.py` and it failed (which may explain why Scalene reported it took no time):

```
[...]
Algorithm: df_clsf
Dataset:
  Source: npy
Traceback (most recent call last):
  File "/xxx/AttachedData-main/./config2.py", line 49, in <module>
    main()
  File "/xxx/AttachedData-main/./config2.py", line 45, in main
    processed_data = process_json(json_data)
                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/xxx/AttachedData-main/./config2.py", line 23, in process_json
    print("  Training Samples:", dataset["training"]["n_samples"])
                                 ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'n_samples'
```

**Comment by emeryberger** [comment]
I modified the code somewhat (I suspect your issue was that you have a space in the file name and didn't escape it with a backslash) and it runs in far too little time for Scalene to profile it (0.03 seconds).
