### ISSUE TITLE
Installing with Poetry fails

### ISSUE THREAD

**Issue by robertodr** [plasma-umass/scalene#662]
**Describe the bug**
I'm trying to install scalene >=1.5.20 in a project managed with Poetry. Here is the `pyproject.toml`:

```toml
[tool.poetry]
name = "floof"
version = "0.3.0"
description = ""
authors = ["me"]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
scalene = "^1.5.20"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

Running `poetry install` gives me the following error:

```
The current project's Python requirement (>=3.10,<3.12) is not compatible with some of the required packages Python requirement:
  - scalene requires Python >=3.8,!=3.11.0, so it will not be satisfied for Python 3.11.0
  - scalene requires Python >=3.8,!=3.11.0, so it will not be satisfied for Python 3.11.0
  - scalene requires Python >=3.8,!=3.11.0, so it will not be satisfied for Python 3.11.0
  - scalene requires Python >=3.8,!=3.11.0, so it will not be satisfied for Python 3.11.0
  - scalene requires Python >=3.8,!=3.11.0, so it will not be satisfied for Python 3.11.0
  - scalene requires Python >=3.8,!=3.11.0, so it will not be satisfied for Python 3.11.0
  - scalene requires Python >=3.8,!=3.11.0, so it will not be satisfied for Python 3.11.0
  - scalene requires Python >=3.8,!=3.11.0, so it will not be satisfied for Python 3.11.0
  - scalene requires Python >=3.8,!=3.11.0, so it will not be satisfied for Python 3.11.0
  - scalene requires Python >=3.8,!=3.11.0, so it will not be satisfied for Python 3.11.0
  - scalene requires Python >=3.8,!=3.11.0, so it will not be satisfied for Python 3.11.0

Because no versions of scalene match >1.5.20,<1.5.21 || >1.5.21,<1.5.21.1 || >1.5.21.1,<1.5.21.2 || >1.5.21.2,<1.5.21.3 || >1.5.21.3,<1.5.21.4 || >1.5.21.4,<1.5.22.2 || >1.5.22.2,<1.5.23 || >1.5.23,<1.5.24 || >1.5.24,<1.5.25 || >1.5.25,<1.5.26 || >1.5.26,<2.0.0
 and scalene (1.5.20) requires Python >=3.8,!=3.11.0, scalene is forbidden.
And because scalene (1.5.21) requires Python >=3.8,!=3.11.0, scalene is forbidden.
And because scalene (1.5.21.1) requires Python >=3.8,!=3.11.0
 and scalene (1.5.21.2) requires Python >=3.8,!=3.11.0, scalene is forbidden.
And because scalene (1.5.21.3) requires Python >=3.8,!=3.11.0
 and scalene (1.5.21.4) requires Python >=3.8,!=3.11.0, scalene is forbidden.
And because scalene (1.5.22.2) requires Python >=3.8,!=3.11.0
 and scalene (1.5.23) requires Python >=3.8,!=3.11.0, scalene is forbidden.
And because scalene (1.5.24) requires Python >=3.8,!=3.11.0
 and scalene (1.5.25) requires Python >=3.8,!=3.11.0, scalene is forbidden.
So, because scalene (1.5.26) requires Python >=3.8,!=3.11.0
 and floof depends on scalene (^1.5.20), version solving failed.
```

which I don't quite understand, since I can see the wheels for Python 3.11 are available on PyPI: https://pypi.org/project/scalene/#files

Note that unpinning the version of `scalene` does work, but picks up v1.5.19 The only difference I can see is that newer versions of scalene do not have a wheel available for Windows.

**To Reproduce**
1. Take `pyproject.toml` above
2. Run `poetry install`

**Desktop (please complete the following information):**
 - OS: Linux

**Comment by emeryberger** [comment]
There was a bug in Python 3.11.0; can you update your version of Python and see what happens?

**Comment by robertodr** [comment]
Modifying my required Python version as: `python = ">=3.10,<3.12,!=3.11.0"` did work. It seems a problem with Poetry.

**Comment by emeryberger** [comment]
Great! Looks like Poetry has a surprisingly naive algorithm for deciding what version to use. Just curious: why the exclusion of version 3.12? (I myself have seen a number of packages that are incompatible with 3.12, and I wonder which issues others are hitting).

**Comment by robertodr** [comment]
The project I'm working on enforces support for the latest two released Python versions and 3.12 is still release candidate. Once 3.12 is out, the pin will likely be `python = ">=3.11,<3.13"`. It will probably take a while to support 3.12, since the project in question uses numba.

By the way, it seems that this is expected behavior with Poetry: https://github.com/python-poetry/poetry/issues/8355

**Comment by ab93** [comment]
Hi @emeryberger! Is there a reason why we have this line in `setup.py`? 
`python_requires=">=3.8,!=3.11.0"`

**Comment by emeryberger** [comment]
Yes, there are actually two reasons.

`>=3.8`: Python depends on language features in Python 3.8 or above.
`!=3.11.0`: There was a [bug introduced in 3.11.0](https://github.com/python/cpython/commit/2182a71eedbc8e95c3cf2d8c0aa2fd66c7a93db4
) that caused Scalene to crash. That bug was fixed in 3.11.1 and thus in later versions.

**Comment by ab93** [comment]
Oh, had no idea. Thanks a lot for the explanation @emeryberger !

**Comment by nchammas** [comment]
> Looks like Poetry has a surprisingly naive algorithm for deciding what version to use.

I think the idea is that if you are declaring that your project can run on Python 3.11.0, but one of your dependencies specifically says it _cannot_ run on that version of Python, then your compatibility declaration is incorrect.

The version of Python you are currently running -- say, Python 3.11.7 -- may work fine, but if you publish your library to the world then someone else may try to run it with Python 3.11.0 and have a problem. Poetry prevents this problem.

I think Poetry's behavior is correct, though when I hit this error today I also found it confusing at first (which led me to this issue). Poetry's dependency solver is [anything but naive][1].

[1]: https://python-poetry.org/docs/dependency-specification/
