### ISSUE TITLE
Use manylinux_2014 for linux wheels instead of manylinux_2_24

### ISSUE THREAD

**Issue by pankajp** [plasma-umass/scalene#670]
**Is your feature request related to a problem? Please describe.**
Manylinux_2_24 wheels are not installable on some older machines. As per https://github.com/pypa/manylinux/issues/1332 manylinux_2_24 is already EOL and as per https://github.com/pypa/manylinux/issues/1332#issuecomment-1147968366 it is not useful

**Describe the solution you'd like**
Build the linux binary wheels on manylinux_2014 instead.

**Describe alternatives you've considered**
Compiling from source, but it too much hassle to just try it out

**Comment by emeryberger** [comment]
Thanks for the heads-up. We are looking into it now.
