### ISSUE TITLE
ERROR: Do not try to invoke `start` when you have not called Scalene using...

### ISSUE THREAD

**Issue by Gabriel-p** [plasma-umass/scalene#672]
**Describe the bug**
Immediately get the error:

```
ERROR: Do not try to invoke `start` when you have not called Scalene using one of the methods in https://github.com/plasma-umass/scalene#using-scalene
Traceback (most recent call last):
  File "/home/gabriel/Descargas/test.py", line 6, in <module>
    scalene_profiler.start()
  File "/home/gabriel/miniconda3/envs/py3/lib/python3.11/site-packages/scalene/scalene_profiler.py", line 146, in start
    Scalene.start()
  File "/home/gabriel/miniconda3/envs/py3/lib/python3.11/site-packages/scalene/scalene_profiler.py", line 1708, in start
    sys.exit(1)
SystemExit: 1
```

**To Reproduce**
Run example below

Please include a minimum working example if at all possible.

```
from scalene import scalene_profiler

# Turn profiling on
scalene_profiler.start()

print("hello")

# Turn profiling off
scalene_profiler.stop()
```

**Desktop (please complete the following information):**
 - OS: elementary OS 7 (based on Ubuntu 22.04.2 LTS)
 - Browser Google Chrome
 - Version (of Chrome?) 115.0.5790.170 (Build oficial) (64 bits)

If you have not yet tried with the repository version (`python3 -m pip install git+https://github.com/plasma-umass/scalene`), please try that before reporting.

**Additional context**
Running `Python 3.11.3` in `conda 23.5.0` environment

**Comment by emeryberger** [comment]
Did you invoke this with `scalene` as directed?

**Comment by Gabriel-p** [comment]
Ooh I see that now. I was just running the script as I used to do with other profilers. Thank you!
