### ISSUE TITLE
Possible Windows 11 Incompatibility Issue

### ISSUE THREAD

**Issue by peacefulstreamdev** [plasma-umass/scalene#675]
**Describe the bug**
While testing a Django Application using 'scalene manage.py runserver', I receive an error 'This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher'.

**To Reproduce**
1. Create a basic Django Application
2. Run 'scalene manage.py runserver'

**Expected behavior**
I should be able to test all parts of the project, hit Ctrl+C and view the Scalene report.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 116.0.5845.111

**Comment by emeryberger** [comment]
I could not reproduce this. Could you please attach your app or a minimal working example?

**Comment by peacefulstreamdev** [comment]
[sample-app.zip](https://github.com/plasma-umass/scalene/files/12620241/sample-app.zip)

I get the same error when I create a brand new project like the one attached and runserver with scalene.

**Comment by emeryberger** [comment]
I now can reproduce your error, thanks. Looking into it.

**Comment by emeryberger** [comment]
FWIW this has been reproduced on Windows 10, so it looks like a general Windows issue, not version specific.

**Comment by emeryberger** [comment]
Just verifying: are you running on x86-64 or ARM64 (or, unlikely, x86 32 bits)?

**Comment by peacefulstreamdev** [comment]
x64

**Comment by emeryberger** [comment]
I found and fixed the issue, with the caveat that hitting Ctrl-C to interrupt Django currently causes two profiles to be output. Please try installing from the repo: `python3 -m pip install git+https://github.com/plasma-umass/scalene`.

**Comment by peacefulstreamdev** [comment]
That seems to have fixed the issue, thank you

**Comment by emeryberger** [comment]
Thanks for your report and for your cooperation!
