### ISSUE TITLE
Document that memory profiling is not supported on Windows in Readme and --help

### ISSUE THREAD

**Issue by odemarto** [plasma-umass/scalene#690]
**Describe the bug**
Memory profiling is not supported on Windows.
This should be clearly documented in Readme and --help to avoid a wild goose chase.

**To Reproduce**
NA

**Expected behavior**
NA

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
NA

**Comment by emeryberger** [comment]
This _is_ documented on the README. That said, I will add something to the Scalene CLI to make this clear. 

https://github.com/plasma-umass/scalene#installation

<img width="829" alt="Screenshot 2023-09-08 at 12 29 00 PM" src="https://github.com/plasma-umass/scalene/assets/1612723/38e03b73-7a41-464b-9b99-78ec6ad55939">

**Comment by odemarto** [comment]
Sorry, missed the part in the Readme (it was not expanded, so I couldn't search for it).
Thanks for the quick response.
