### ISSUE TITLE
Bring CRDP into compliance with 3.8

### ISSUE THREAD

**Issue by sternj** [plasma-umass/scalene#710]
PyCRDP uses the function `Py_EnterRecursiveCall`, which was first introduced in 3.9. It is used [here](https://github.com/plasma-umass/crdp/blob/1a25a6cd4abfbe5c53eccbd1c2da01d57e988a28/crdp.c#L3609), [here](https://github.com/plasma-umass/crdp/blob/1a25a6cd4abfbe5c53eccbd1c2da01d57e988a28/crdp.c#L3688), and [here](https://github.com/plasma-umass/crdp/blob/1a25a6cd4abfbe5c53eccbd1c2da01d57e988a28/crdp.c#L3708). To maintain Scalene's usability with 3.8, PyCRDP should either be forked from an older version or that function call should be changed.

**Comment by emeryberger** [comment]
In fact, `Py_EnterRecursiveCall` has been in the ABI for quite a long time, and Cython has been using it since forever. For posterity: not sure what the issue was, but the original poster of this issue (on the Slack channel) was able to resolve it by upgrading their version of Python.
