### ISSUE TITLE
Display percentage and absolute time *values* in the html report

### ISSUE THREAD

**Issue by dhirschfeld** [plasma-umass/scalene#717]
**Is your feature request related to a problem? Please describe.**

The bar charts showing the percentage of time on each line are useful to visually identify and quickly hone in on the problematic lines.

Once you've identified the problematic lines you want to get details such as the percentage time and the absolute time spent on each line in the function. This information is missing from the HTML report. The percentage time you can get from hovering over the bar chart, but that's extremely cumbersome to do for each line and doesn't let you see all the data at once. Also I would like to see the absolute times - for me, they're more important than the percentages, but both are useful to have.

**Describe the solution you'd like**
Show `time %` and `time (ms)` as columns in the HTML report next to each line.

**Comment by ioannis-vm** [comment]
This is a much needed feature. It seems straightforward to have a command line flag that controls this behavior, chosing between percentages or valusees.

**Comment by mucmch** [comment]
Fully agree with @dhirschfeld.
Having `time %` and `time (ms)` as extra columns would be very helpful.
Currently, this information is not available at all for me as hovering over does not work.

**Comment by emeryberger** [comment]
Time is now visible when hovering over the graphical time bars.
