### ISSUE TITLE
Handle browsers not in cpython's webbrowser.py

### ISSUE THREAD

**Issue by Jeremiah-England** [plasma-umass/scalene#723]
**Describe the bug**

Browsers that aren't explicitly handled in [`webbrowser.py`](https://github.com/python/cpython/blob/main/Lib/webbrowser.py) end up as `GenericBrowser` objects when the BROWSER environment variable is set. Scalene won't open the web UI for those browsers because we try to avoid opening in text browsers and it seemed like `GenericBrowser` was for those.

https://github.com/plasma-umass/scalene/blob/master/scalene/scalene_profiler.py#L1768-L1775

This is probably why @munael's [comment](https://github.com/plasma-umass/scalene/issues/383#issuecomment-1299123915) has upvotes.

**To Reproduce**

1. Set the BROWSER environment variable to vivaldi (or brave probably too).
2. Run `scalene --viewer`

**Desktop:**
 - OS: Archlinux
 - Browser: Vivaldi
 - Version: 1.5.31.1

**Additional context**

Lines in webbrowser.py that create the `GenericBrowser`: https://github.com/python/cpython/blob/main/Lib/webbrowser.py#L528-L540

When I remove the BROWSER environment variable, I get a `BackgroundBrowser` object with a name of `xdg-open`.

I'm happy to write up a patch for this if you want. I think we should probably just explicitly list out the common text browsers and ignore them. We could start with the list from `webbrowser.py` [here](https://github.com/python/cpython/blob/main/Lib/webbrowser.py#L511-L526).

**Comment by Jeremiah-England** [comment]
@emeryberger, I submitted a PR (#724). Let me know if you see anything I should change!

Also, thanks for working on scalene!

**Comment by Jeremiah-England** [comment]
Thanks for the merge @emeryberger!

I'm going to close this now. Feel free to re-open if you like to leave things open till an actual release.

**Comment by emeryberger** [comment]
Thanks for the contribution!
