### ISSUE TITLE
`--json` arg ignored without `--cli`

### ISSUE THREAD

**Issue by Samir-Rashid** [plasma-umass/scalene#725]
**Describe the bug**
Running `scalene --json --no-browser --outfile ./profile.json ./main.py` causes HTML to be outputted to `./profile.json`. Adding `--cli` fixes this.

**To Reproduce**
1. I was in [this](https://github.com/Samir-Rashid/pytrail/tree/main/tasks) directory, but this bug should be triggered by anything.
2. Run `scalene --json --no-browser --outfile ./profile.json ./main.py`
3. Open `./profile.json` and see that its contents are HTML.

**Expected behavior**
Should have put the json output in the specified file.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: on NixOS in a Python 3.10.13 virtualenv
- Version: 1.5.31.1 (2023.09.15)
  - I also reproduced the issue with Scalene's repository version

**Comment by sarahec** [comment]
Looking at it.
