### ISSUE TITLE
Provide a "rich" html when no browser is available

### ISSUE THREAD

**Issue by rben-dev** [plasma-umass/scalene#739]
**Is your feature request related to a problem? Please describe.**
It is frustrating to stick to CLI or "simple" HTML output when no browser is available (i.e. do not have HTML with embedded javascript GUI). This is a limitation that should not exist since we could want to open the produced file on another machine. This is particularly convenient when e.g. we use `scalene` in a minimal `Docker` environment (with no graphical browser) in order to export the produced HTML file to analyze it on the host machine.

**Describe the solution you'd like**
Add a dedicated option to export the javascript GUI in the produced HTML file even if no graphical webbrowser is detected.

**Describe alternatives you've considered**
No specific alternative.

**Additional context**
No other context.

**Comment by emeryberger** [comment]
Have you tried `--cli --json --outfile profile.json`? You can then view the generated JSON file locally by invoking `scalene --viewer`.

**Comment by rben-dev** [comment]
This works great! Sorry for having missed this `--viewer` option allowing to locally get the "rich" html view.

Closing the issue as `scalene` already allows the asked feature.
