### ISSUE TITLE
Scalene does not work out of the box with sage

### ISSUE THREAD

**Issue by rben-dev** [plasma-umass/scalene#740]
**Describe the bug**
Using `scalene` with `sage-math` (https://www.sagemath.org/index.html) does not work as the process immediately exits at the `import` of `sage`.

**To Reproduce**
1. Install `sage`
2. Execute the simplest script with e.g. `from sage.all import matrix` and a `print` after this import with `scalene`
3. Observe the early exit (the `print` is never reached)

**Expected behavior**
`scalene` should be able to monitor the whole execution and not early exit.

**Desktop (please complete the following information):**
 - OS: Linux (Debian and Ubuntu)
 - Browser: chrome and firefox
 - Version: 1.5.32.1

**Additional context**
The main issue seems to be related to the fact that `sage` somehow diverts some signals during its initialization (see https://github.com/sagemath/cysignals that is part of the package). Since `scalene` makes use of signals to perform profiling, this is no surprise that that some issues arise ... However, it could be worth investigating some solutions on the `scalene` side to deal with such cases (through signals masking or override?).

**Comment by emeryberger** [comment]
I took a look at this and there is no obvious fix on the Scalene side.

**Comment by rben-dev** [comment]
Hi,

Thanks for your investigation and your feedback :+1:  

For those stumbling upon this issue and having to deal with a solution, a quick and dirty fix is to comment the `init_cysignals()` call in the `__init__.py`  file of the `cysignals` package in the `sage` install path. Although I do not completely get the implications of removing signals initialization in `sage`, this allows - at least for my usage of  `sage`  (fields, rings and matrices) - to remove the issue with `scalene`.

Regards,

**Comment by emeryberger** [comment]
Thanks for the deeper investigation! I found that if I put this at the top of `scalene/scalene_profiler`, I was also able to get your example to work. If you can verify this, I'd appreciate it. It's a bit of a hack but easy to include, so if it works, I will just roll it into Scalene.

```
try:
    import cysignals
    cysignals.init_cysignals = lambda x: None
except ModuleNotFoundError as e:
    pass
```

**Comment by rben-dev** [comment]
Thanks a lot @emeryberger! This works great (I have been able to confirm this as working on various versions of `sage`).
Nice trick to early import the module so that `sage` signals manipulation is no more an issue for `scalene` :-)

Closing the issue as it is properly resolved :+1:
