### ISSUE TITLE
Run scalene run_profile programmatically

### ISSUE THREAD

**Issue by suranap** [plasma-umass/scalene#749]
Hi, I'd like to use scalene to profile a <https://github.com/nv-legate|runtime system> that hosts Python. I can't call `scalene mycode.py` , I call `myruntime mycode.py`. I'd like to do this programmatically, but the start &amp; stop commands require that scalene sets everything up in `run_profiler`. Is there a way to run scalene's init code in my script?

[Slack Message](https://scaleneprofil-jge3234.slack.com/archives/C02LJ52BM9B/p1703085641313049)

**Comment by emeryberger** [comment]
Unfortunately, Scalene needs to run first so it can interpose on memory operations. You can't start it after Python has begun execution.
