### ISSUE TITLE
No longer running on Python 3.8 

### ISSUE THREAD

**Issue by AvdN** [plasma-umass/scalene#753]
`scalene` 1.5.33` no longer works on Python 3.8, although that version is being advertised as supported and EOL for 3.8 has not been reached (scheduled for 2024-10-31)

To reproduce create a Python 3.8 virtualenv ( I used 3.8.18 ), and install scalene:
```
/opt/python/3.8.18/bin/python -m venv /opt/util/scalene38
/opt/util/scalene38/bin/pip install -U pip setuptools
/opt/util/scalene38/bin/pip install scalene
cat >> hello.py << EOF
print('Hello world!')
EOF
/opt/util/scalene38/bin/python hello.py
/opt/util/scalene38/bin/scalene hello.py 
```
This last command throws and error on line 189 because of typing info (and on 881 if you fix that line):
```
Traceback (most recent call last):
  File "/opt/util/backupmanager1/bin/scalene", line 5, in <module>
    from scalene.__main__ import main
  File "/opt/util/backupmanager1/lib/python3.8/site-packages/scalene/__main__.py", line 4, in <module>
    from scalene import scalene_profiler
  File "/opt/util/backupmanager1/lib/python3.8/site-packages/scalene/scalene_profiler.py", line 156, in <module>
    class Scalene:
  File "/opt/util/backupmanager1/lib/python3.8/site-packages/scalene/scalene_profiler.py", line 189, in Scalene
    __windows_queue: queue.Queue[
TypeError: 'type' object is not subscriptable
```
and on 881 if you remove the typing info from the 189-191 (collapsing those lines to one):
```
Traceback (most recent call last):
  File "/opt/util/backupmanager1/bin/scalene", line 5, in <module>
    from scalene.__main__ import main
  File "/opt/util/backupmanager1/lib/python3.8/site-packages/scalene/__main__.py", line 4, in <module>
    from scalene import scalene_profiler
  File "/opt/util/backupmanager1/lib/python3.8/site-packages/scalene/scalene_profiler.py", line 156, in <module>
    class Scalene:
  File "/opt/util/backupmanager1/lib/python3.8/site-packages/scalene/scalene_profiler.py", line 881, in Scalene
    ) -> Generator[Tuple[list[str], int], None, None]:
TypeError: 'type' object is not subscriptable
``` 

This was done on Ubuntu 22.04 with Python 3.8.18 downloaded and compiled from source.

The direct cause for this is the usage of [PEP 585](https://peps.python.org/pep-0585/) like type hinting generics, it can be solved by adding 
```
from __future__ import annotations
```
Although only `scalene_profiler.py` threw an error, **this line should be added to all `.py` files,** not just to this file as a bridge until supprot for 3.8 is dropped because of EOL. This also allows use of class names in the typing information of the methods of those classes on versions later than 3.8. E.g. in `adaptive.py`:
```
from __future__ import annotations

class Adaptive:
<snip>
    def __add__(self: Adaptive, other: Adaptive) -> Adaptive:   # quotes can be removed
<snip>
    def get(self) -> list[float]:
        return self.sample_array
```

The indirect cause for this is that scalene is probably not testedfor the whole range of supported Python versions before creating a version ( (I use  tox for that on `ruamel.yaml` and all other packages I create, highly recommended)

**Comment by emeryberger** [comment]
Thanks for the issue; I had already identified the need for the `from __future__ import annotations` line in `scalene_profiler.py` but will see about adding it to the other files.

**Comment by emeryberger** [comment]
Fixed with https://github.com/plasma-umass/scalene/commit/8a2802f86fb4d0812a6e4b15fe7682fb7835e82f.
