### ISSUE TITLE
Build fails with a GCC error ("unused result" in the printf redefinition)

### ISSUE THREAD

**Issue by sarahec** [plasma-umass/scalene#777]
**Describe the bug**

Running `python3 setup.py build` may result in a broken GCC build (on older compiler versions). See PR #776 that adds a GCC flag to disable this.

**Comment by emeryberger** [comment]
Should be fixed by your PR - https://github.com/plasma-umass/scalene/pull/776. (Please confirm - thanks!)

**Comment by sarahec** [comment]
Confirmed, and thank you! 

Next step: OpenAI supports CORS now, so it should be possible to simplify the browser launching code. (I'm on NixOS and Chrome wasn't launching. A quick edit and it works; now I have to make sure the OpenAI integration still works.)
