### ISSUE TITLE
Python 3.11 support

### ISSUE THREAD

**Issue by fehtemam** [plasma-umass/scalene#796]
**Describe the bug**
Installing Scalene under 3.11 now fails.

**To Reproduce**
python3 -m pip install scalene==1.5.35
where python3 executable redirects to python3.11 executable

Error message:

 7.563 ERROR: Ignored the following versions that require a different python version: 0.52.0 Requires-Python >=3.6,<3.9; 0.52.0rc3 Requires-Python >=3.6,<3.9; 0.53.0 Requires-Python >=3.6,<3.10; 0.53.0rc1.post1 Requires-Python >=3.6,<3.10; 0.53.0rc2 Requires-Python >=3.6,<3.10; 0.53.0rc3 Requires-Python >=3.6,<3.10; 0.53.1 Requires-Python >=3.6,<3.10; 0.54.0 Requires-Python >=3.7,<3.10; 0.54.0rc2 Requires-Python >=3.7,<3.10; 0.54.0rc3 Requires-Python >=3.7,<3.10; 0.54.1 Requires-Python >=3.7,<3.10; 0.55.0 Requires-Python >=3.7,<3.11; 0.55.0rc1 Requires-Python >=3.7,<3.11; 0.55.1 Requires-Python >=3.7,<3.11; 0.55.2 Requires-Python >=3.7,<3.11; 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11; 1.5.20 Requires-Python >=3.8,!=3.11.0; 1.5.21 Requires-Python >=3.8,!=3.11.0; 1.5.21.1 Requires-Python >=3.8,!=3.11.0; 1.5.21.2 Requires-Python >=3.8,!=3.11.0; 1.5.21.3 Requires-Python >=3.8,!=3.11.0; 1.5.21.4 Requires-Python >=3.8,!=3.11.0; 1.5.22.2 Requires-Python >=3.8,!=3.11.0; 1.5.23 Requires-Python >=3.8,!=3.11.0; 1.5.24 Requires-Python >=3.8,!=3.11.0; 1.5.25 Requires-Python >=3.8,!=3.11.0; 1.5.26 Requires-Python >=3.8,!=3.11.0; 1.5.27 Requires-Python >=3.8,!=3.11.0; 1.5.28 Requires-Python >=3.8,!=3.11.0; 1.5.29 Requires-Python >=3.8,!=3.11.0; 1.5.30 Requires-Python >=3.8,!=3.11.0; 1.5.31.1 Requires-Python >=3.8,!=3.11.0; 1.5.33 Requires-Python >=3.8,!=3.11.0; 1.5.33.1 Requires-Python >=3.8,!=3.11.0; 1.5.34 Requires-Python >=3.8,!=3.11.0; 1.5.35 Requires-Python >=3.8,!=3.11.0; 1.5.36 Requires-Python >=3.8,!=3.11.0; 1.5.37 Requires-Python >=3.8,!=3.11.0
 7.563 ERROR: Could not find a version that satisfies the requirement scalene==1.5.35

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 in Docker

**Comment by emeryberger** [comment]
You need to upgrade to a higher version of Python 3.11. Version 3.11.0 has a known bug that interfered with Scalene's operation.
