### ISSUE TITLE
defaults to cli

### ISSUE THREAD

**Issue by do8tsy** [plasma-umass/scalene#797]
scalene defaults to cli.
in the latest version find_browser returns webbrowser.get().name. On my windows machine this is an empty string, that evaluates to False and hence web is set to false in scalene_profiler.py and cli to true.
The behaviour comes from the webbrowser library and seems to be consistent over all Windows machines I had access to.

**To Reproduce**
just run 
scalene *insert any program*

**Desktop (please complete the following information):**
 - Windows
 - edge and firefox - I changed default browser
 - Version 1.5.37

**Additional context**
It worked in 1.5.34

**Comment by emeryberger** [comment]
Thanks for the report! I've just verified that a fix for this works on Mac (as before; this affected 3.12 as well) and Windows. I'll be releasing a new version momentarily (1.5.38).

**Comment by sarahec** [comment]
@do8tsy my apologies -- it was my change that broke it.
