### ISSUE TITLE
Wheel missing for Python 3.12

### ISSUE THREAD

**Issue by kinoute** [plasma-umass/scalene#807]
Hello,

I can't find wheels for Python 3.12 on Pypi: https://pypi.org/project/scalene/#files. Therefore, I need to "compile" the package by myself. Any chance to get this on Pypi? 

Thanks a lot!

**Comment by kinoute** [comment]
@emeryberger Thanks for the merge! Any chance you could make a release to trigger the build & upload workflow (or do it manually?)

Thanks a lot!

**Comment by emeryberger** [comment]
Just issued a new release - thanks again!

**Comment by emeryberger** [comment]
Closed with https://github.com/plasma-umass/scalene/commit/0ac9a1c22186f985a076ce49c26ed6843bf8b004
