### ISSUE TITLE
Discrepency between online GUI and the generated HTML

### ISSUE THREAD

**Issue by volovikariel** [plasma-umass/scalene#815]
**Describe the bug**
Not sure if this is a bug or intended, but the HTML file generated locally differs from what is available here: http://plasma-umass.org/scalene-gui/ 

**To Reproduce**
1. Profile *anything* with scalene
2. Open the `.html` output in Firefox or Chrome
3. Compare it to the output on http://plasma-umass.org/scalene-gui/ 

**Expected behavior**
I would expect them to be the same. In particular, I would expect to be able to hover over the bars and see a popup with %native %python, etc. Instead of nothing showing up

**Screenshots**
The output generated from running scalene with: `python -m scalene  src/main.py ` is as follows (note that I'm hovering on the "bar"):
![image](https://github.com/plasma-umass/scalene/assets/16262535/aec64ca0-b362-4b66-8c0a-8ea5c3eb35b1)

On http://plasma-umass.org/scalene-gui/  it's as follows:
![image](https://github.com/plasma-umass/scalene/assets/16262535/5df771ef-cd45-4f5e-b2b8-1732f07d70e2)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: Both Chrome and Firefox(125.0.1)
 - Version: Scalene version 1.5.39 (2024.04.15)
 
(I also tried it with python3 -m pip install git+https://github.com/plasma-umass/scalene`)

**Additional context**

**Comment by emeryberger** [comment]
Thanks for the note. The online viewer has now been updated. Note that the hover-tips are currently disabled, replaced with numbers in the bars.
