### ISSUE TITLE
Ollama server is not detected

### ISSUE THREAD

**Issue by volovikariel** [plasma-umass/scalene#816]
**Describe the bug**
The scalene local language model option is not detecting my locally running ollama model.

**To Reproduce**
1. Run the `llama3:8b` model locally, and have it be exposed on http://localhost:11434/
2. Open an `.html` file generated by running scalene on any python code
3. Select "AI service provider" = local
4. Receive error message of: "Server not found or no language models installed."

**Expected behavior**
There should be no error message, the Ollama server should be detected.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: Firefox v. 125.0.2
 - Scalene version 1.5.39 (2024.04.15)

**Additional context**
I visited localhost:11434 and it says that Ollama is running.
I have tried restarting the server and re-opening the HTML page, the issue persists.
I ran `ollama run` and was able to interact with the model, so it seems to be working fine.

**Comment by emeryberger** [comment]
Just loaded that model and I can't reproduce on Mac at least - what happens when you run `scalene --viewer`?

**Comment by volovikariel** [comment]
That one seems to detect it just fine :open_mouth:
