### ISSUE TITLE
Is there a way to not use GPU monitoring and pynvml?

### ISSUE THREAD

**Issue by Wizard1209** [plasma-umass/scalene#829]
**Describe the bug**
Hi, I'm trying to optimize memory usage of our framework and keep getting pynvml in report using around 100M of memory, is there a way to exclude this module as I'm only optimizing CPU and memory with corresponding arguments?
By the way, I wasn't able to exclude it with `--profile-exclude`.

**To Reproduce**
It's not easy to provide an example I'm working with, but here is the command
`scalene --cpu --memory --allocation-sampling-window 2097152 --profile-all /root/.pyenv/versions/3.12.2/envs/dipdup/bin/dipdup -e .env -c dipdup.yaml -c configs/dipdup.sqlite.yaml run`

**Expected behavior**
It would be nice not to load GPU modules and monitoring code when only CPU and memory profilers are enabled.

**Screenshots**
![image](https://github.com/plasma-umass/scalene/assets/34334729/edd1198a-28e0-4097-b914-72024ede1ac1)

**Desktop (please complete the following information):**
 - OS: WSL2
 - Python 3.12.2, Scalene version 1.5.42.2 (2024.06.18)

**Comment by emeryberger** [comment]
Please install the latest version from the repository (`python3 -m pip install git+https://github.com/plasma-umass/scalene`); in theory, it should solve this problem.
