### ISSUE TITLE
Unable to export scalene summary as a Json output

### ISSUE THREAD

**Issue by abhishek-gupta-01** [plasma-umass/scalene#852]
**Describe the bug**
I am unable to download the json output of the profiler summary. 

**To Reproduce**
1. I am running this command in my WSL - scalene  --json --outfile report.json sample_code.py
2. A report.json is generated which actually contains HTML information and not just the json output.
3. I have tried --json-only also but still html information.
<img width="788" alt="Json_issue" src="https://github.com/user-attachments/assets/9dca3462-fd0e-4abd-85af-ad5e02443169">

**Expected behavior**
When I run "scalene sample_code.py" 2 files are generated automatically - profile.html and profile.json 
I am trying to get a similar file as profile.json.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] WSL- Ubuntu-20.04
 - Browser [e.g. chrome, safari] Microsoft edge
 - Version [e.g. 22] Scalene version 1.5.43.2 (2024.07.23)

**Additional context**
I am trying to profile my sample.py script with multiple iteration using a bash script that runs this command 100 times.
"scalene  --no-browser --json --outfile report.json sample_code.py" 
I am trying to store the json response of each iteration in a folder for further analysis.

**Comment by emeryberger** [comment]
Thanks for reporting. This should be fixed in the current repo and in an upcoming release.
