### ISSUE TITLE
Pinning `setuptools` is causing build failures in nixpkgs

### ISSUE THREAD

**Issue by sarahec** [plasma-umass/scalene#853]
A recent automatic update to `scalene` broke in the `nixpkgs` build:
https://github.com/NixOS/nixpkgs/issues/335882

The problem stems from pinning `setuptools<71` (per `requirements.txt`). While I could pin setuptools in the derivation (nix for "makefile"), this is highly discouraged. 

There seems to be a simpler answer -- give `setuptools` the dependencies it needs:
https://github.com/pypa/setuptools/issues/4483#issuecomment-2236528158

Apologies for not supplying a PR. I'm doing something wrong with pytest and am having trouble remembering the appropriate incantation.

**Comment by sarahec** [comment]
@emeryberger is this a good time to publish another release? It would help some people who are waiting to have the fix in nixpkgs.

**Comment by emeryberger** [comment]
I'm having issues with Conda for some reason; if you could lend a hand that'd be great, but I'll issue a release now anyway.
