### ISSUE TITLE
Scalene error: received signal SIGSEGV when --memory is set

### ISSUE THREAD

**Issue by auderson** [plasma-umass/scalene#869]
```bash
python3 -m scalene  --memory untitled.py
```
gives:
```
Scalene error: received signal SIGSEGV
```
untitled.py is an empty .py script

```bash
cat /proc/version
```
```
Linux version 5.15.0-122-generic (buildd@lcy02-amd64-034) (gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #132-Ubuntu SMP Thu Aug 29 13:45:52 UTC 2024
```
Python version 3.10
Without  --memory option it works fine.

**Comment by sternj** [comment]
Thank you for the reproduction information! Which version of 3.10 are you on?

**Comment by emeryberger** [comment]
Does not reproduce on Mac. Which version of Scalene? (`scalene --version`)

**Comment by sternj** [comment]
I'm also not able to reproduce on an Ubuntu 22.04 VM with Scalene installed from Pip

**Comment by sternj** [comment]
Also fails to reproduce with Scalene installed from git@HEAD

**Comment by auderson** [comment]
Found it...The cause is that my path contains Chinese characters, mv the file to `~` and the error is gone:
![image](https://github.com/user-attachments/assets/e307482c-485a-4b11-a938-c3b4cceafb29)

**Comment by emeryberger** [comment]
Thanks for isolating the problem - this should now be fixed.
