### ISSUE TITLE
Scalene error: received signal SIGSEGV

### ISSUE THREAD

**Issue by snooppr** [plasma-umass/scalene#876]
By default, Scalene returns the error: "**Scalene error: received signal SIGSEGV**".

The mistake of the last decade.
Scalene does not work with projects if the path contains **Cyrillic**, as soon as you move a project where the path contains only Latin, Scalene will work.

An example of reproducing the error (suffix - Cyrillic):
$ cd '/home/user/Desktop/test/херовая ошибка'
$ python -m scalene --cli program.py
>Scalene error: received signal SIGSEGV

Working example:
$ cd '/home/user/Desktop/test'
$ python -m scalene --cli program.py

The solution is to move the project, if the path contains Cyrillic, to a location where the path contains only Latin.
Fix it so that Scalene understands Cyrillic in the path, or notify users in the documentation how to fix this problem.

**Desktop (please complete the following information):**
 - OS: GNU/Linux
 - Version 1.5.45 (2024.10.01)

**Comment by emeryberger** [comment]
Thanks for the report. This was already fixed by https://github.com/plasma-umass/scalene/pull/870 and will be incorporated in the next release.

<img width="889" alt="Screenshot 2024-11-02 at 8 44 18 AM" src="https://github.com/user-attachments/assets/4e9acb23-5f79-4fc8-852e-02bedde47138">
