### ISSUE TITLE
Have questions about the content generated in the graph

### ISSUE THREAD

**Issue by ZHANG-SH97** [plasma-umass/scalene#880]
I have some questions regarding the content generated in the "timeline/%" column in the chart and hope to get some clarification:

1、What is the meaning behind the length of the sparklines? Even with the same 1%, some are longer and some are shorter.
2、Some sparklines display percentages, while others do not. What is the criterion for this distinction?
![image](https://github.com/user-attachments/assets/dceb9e61-1dc1-4c54-abf7-0ab21f5b9c80)

Looking forward to your reply！

**Comment by emeryberger** [comment]
I recommend using the web-based UI instead of the CLI; it's much more clear and hopefully will answer your questions.

**Comment by emeryberger** [comment]
The text-based UI is no longer being actively developed and may even end up getting removed; it's certainly deprecated at this point.
