### ISSUE TITLE
Are measures "fuzzy"?

### ISSUE THREAD

**Issue by hmijail** [plasma-umass/scalene#89]
**Describe the bug**
Not sure I'd call it a bug, but it'd be good to have some explanation on this.
The reported time in each line is sometimes heavily suspicious. My feeling is that when one line has a heavy time, it can bleed off onto neighboring lines. Example:
```
   119 │    2% │        │     │   91% │   30 │▁▁▁▁          │       │        for i in range(0, max_hash_in_level + 1):             
   120 │    3% │     1% │     │   93% │    9 │▁▁▁▁▁         │       │            siblings_start = i * arity                        
   121 │    3% │     1% │     │   92% │   25 │▁▁▁▁▁▁▁▁▁     │       │            siblings_end = siblings_start + arity             
   122 │       │        │     │       │      │              │       │            #if not map.isdisjoint(merklizators[i]):          
   123 │   11% │     2% │     │   92% │   -3 │▁▁▁▁▁         │       │            overlap = map.clamp(siblings_start, siblings_e…   
   124 │    7% │     1% │     │   91% │   26 │▁▁▁▁▁▁▁▁▁     │       │            lo = len(overlap)                                 
   125 │       │        │     │       │      │              │       │            if lo == 0:                                       
   126 │       │        │     │       │      │              │       │                # these siblings' parent is not present in…   
   127 │       │        │     │       │      │              │       │                continue                                      
   128 │       │        │     │   90% │  -18 │▁▁▁▁          │       │            bits.append(i)                                    
   129 │       │        │     │       │      │              │       │            if lo == arity:                                   
   130 │       │        │     │       │      │              │       │                # we have all the data to recreate the has…   
   131 │       │        │     │       │      │              │       │                continue                                      
   132 │       │        │     │       │      │              │       │            hashes_missing = arity - lo                       
   133 │       │        │     │  100% │    1 │▁             │       │            num_hashes += hashes_missing                      
```

`map` in line 123 uses an external library (Cython RoaringBitmaps), and I fully expect it to be a time sink.
The surprise is in lines 120 and 121, which seem to spend 3% of time each (everything is ints in there). I am no expert on Python internals, but I would bet that this makes no sense by itself.

Relatedly, the percentages in the memory column are hard to make sense of. Is "100%" good or bad? Why is it reported in line 133? Why appending items to a list in 128 is reported as reducing memory?
Again, I can guess that this is actually a side effect of what happens in the previous execution, but would be good to have a real explanation.
I have looked into the paper but doesn't seem to address this.

**To Reproduce**
This happened while profiling the project at https://github.com/ConsenSys/code_merklization_of_traces

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7
 - Version : Scalene 1.1.8, Python 3.8.6

**Comment by emeryberger** [comment]
The percentages in the memory column have been fixed in recent versions. Please update and see if this resolves your issue. As for the time spent, Python is interpreted and int operations can certainly consume a surprising amount of time just because of interpreter overhead...

**Comment by hmijail** [comment]
The project in which I was using Scalene was finished months ago, so I'm afraid I can't test this any more. I assume it's best to close this issue and someone else will reopen if it still exists.
