### ISSUE TITLE
The color choice in the "performance and features" table is CVD unfriendly

### ISSUE THREAD

**Issue by JobLeonard** [plasma-umass/scalene#92]
**Describe the bug**

The yellow and green in [`profiler-comparison.png`](https://github.com/emeryberger/scalene/blob/5288089fdafc3d3bf5ccd858ef352f57950d9988/images/profiler-comparison.png) are not really distinguishable to me, a person with [protanomally](https://en.wikipedia.org/wiki/Color_blindness#Classification).

![](https://raw.githubusercontent.com/emeryberger/scalene/5288089fdafc3d3bf5ccd858ef352f57950d9988/images/profiler-comparison.png)

It is almost guaranteed to also affect people with protanopia, and likely those with deuteranomaly and deuteranopia as well. These forms of color-vision deficiency (CVD) affect somewhere between 5% to 10% of all males.

**To Reproduce**

Steps to reproduce the behavior if you have have one of the aforementioned forms of CVD:

1. Look at picture

Steps to reproduce the behavior if you don't have one of the aforementioned forms of CVD:

1. Look at picture below, which was generated by a CVD simulator, and get a feeling for what the image may look like to someone with protanopia:

![image](https://user-images.githubusercontent.com/259840/100097691-31f66680-2e5d-11eb-8a7f-8635a83a8201.png)

**Expected behavior**

Being able to distinguish "fast", "slower" and "slowest" in the above image

**Screenshots**
See above

**Desktop (please complete the following information):**
Not relevant

**Additional context**

Since it's not really possible to get a color profile that works for *every* form of color vision deficiency, I suggest replacing the colors in this instance with symbols like +, - and --. This has the side-benefit of making the image black and white printer friendly, and it will be more accessible in text-to-speech contexts if the table ever used in textual form.

**Comment by emeryberger** [comment]
Thanks for the feedback. I myself have ("strong") protanopia and I can see the original colors fine, so I didn't realize there'd be any issue. Will see what I can do.

**Comment by JobLeonard** [comment]
> I myself have ("strong") protanopia and I can see the original colors fine, so I didn't realize there'd be any issue. 

Wow, I didn't know there might be situations where someone with protanomaly would have a harder time distinguishing two colors than someone with protanopia! That's really fascinating

(Either that or I have been misdiagnosed and have even worse protanopia than you)

Thanks for looking into it!

PS: love this project btw, hope there will be some kind of JavaScript support at some point!

**Comment by emeryberger** [comment]
Fixed with https://github.com/plasma-umass/scalene/commit/8d9f936f264ae1f4bb9cac8ff74f918f29431aad

**Comment by emeryberger** [comment]
Colors remain but text (numbers) are added, so it's readable. Explanations are in text and thus also accessible.
